### ISSUE TITLE
More than one slickgrid on a page breaks styling

### ISSUE THREAD

**Issue by mpGitHub** [6pac/SlickGrid#1]
The formatting of the columns in the first slickgrid is broken after loading the second slickgrid on the page. The column widths are uneven/overlapping.

See the picture.  I used the simplest example from mleibman's examples, but just put a second grid in there.

**Comment by mpGitHub** [comment]
Uploading the picture wasn't working...  Here is the test code.

NOTE: Broken in Chrome/Firefox.  IE seems to work for this example, but it is broken in some of the more involved examples.  One of the changes that were merged in must have broken this ability.

Let me know what you think.

<!DOCTYPE HTML>
<html>
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
   <title>SlickGrid example 1: Basic grid</title>

   <link rel="stylesheet" href="/main/SlickGrid-2-2-0/slick.grid.css" type="text/css" />
   <link rel="stylesheet" href="/main/jquery/jquery-ui-1-11-4/jquery-ui.structure.min.css"  />
   <link rel="stylesheet" href="/main/jquery/jquery-ui-1-11-4/jquery-ui.theme.min.css"  />

   <script src="/main/jquery/jquery-1.11.2.min.js"></script>
   <script src="/main/jquery/jquery-ui-1-11-4/jquery-ui.min.js"></script>

   <script src="/main/SlickGrid-2-2-0/lib/jquery.event.drag-2.2.js"></script>
   <script src="/main/SlickGrid-2-2-0/slick.core.js"></script>
   <script src="/main/SlickGrid-2-2-0/slick.grid.js"></script>

<script>
   var grid;
   var columns = [
      {id: "title", name: "Title", field: "title"},
      {id: "duration", name: "Duration", field: "duration"},
      {id: "%", name: "% Complete", field: "percentComplete"},
      {id: "start", name: "Start", field: "start"},
      {id: "finish", name: "Finish", field: "finish"},
      {id: "effort-driven", name: "Effort Driven", field: "effortDriven"}
   ];
   var options = {
      enableCellNavigation: true,
      enableColumnReorder: false
   };
   $(function ()
   {
      var data = [];
      for (var i = 0; i < 500; i++) {
         data[i] = {
            title: "Task " + i,
            duration: "5 days",
            percentComplete: Math.round(Math.random() * 100),
            start: "01/01/2009",
            finish: "01/05/2009",
            effortDriven: (i % 5 == 0)
         };
      }
      grid = new Slick.Grid("#myGrid", data, columns, options);

      setTimeout("secondGrid()", 1000);

   })
   // ------------------------------------
   // setting up the second grid in a timeout to make sure it wasn't a timing issue
   function secondGrid()
   {

      var columnsX = [
         {id: "title", name: "Title", field: "title"},
         {id: "%", name: "% Complete", field: "percentComplete"}
      ];
      var optionsX = {
            enableCellNavigation: true,
            enableColumnReorder: false
      };


      var dataX = [];
      for (var i = 0; i < 500; i++) {
         dataX[i] = {
            title: "Task " + i,
            percentComplete: Math.round(Math.random() * 100)
         };
      }

      new Slick.Grid("#myGrid2", dataX, columnsX, optionsX);
   }
</script>
</head>

<body>
<table width="100%">
   <tr>
      <td valign="top" width="50%">
         <div id="myGrid" style="width:600px;height:500px;"></div>
      </td>
      <td valign="top">
         <div id="myGrid2" style="width:600px;height:500px;"></div>
      </td>
   </tr>
</table>

</body>
</html>

**Comment by 6pac** [comment]
thanks for bringing that up. it should work. I'll get to this when I have time, but maybe not till next week.

**Comment by 6pac** [comment]
I've reverted one of the patches - the one for consolidating the one-stylesheet-per-grid into a single stylesheet. This was resetting the cached column style DOM nodes for all existing grids each time a new grid was initialized. There were complex issues as to why there was no workaround - see the commit.

I've added a 'example-multi-grid-basic.html' example for future use, and a test page that generates 40 grids (test/40 grids on a page test.html) for testing with IE versions for the original bug that patch was meant to fix.

The new release is 2.2.2, or you can use the patch on the wiki.

Again, thanks for the bug report.

**Comment by mpGitHub** [comment]
That did the trick.  Thanks!
