### ISSUE TITLE
Rectangular selection doesn't grow as expected with cellselectionmodel

### ISSUE THREAD

**Issue by pivotalgeorge** [6pac/SlickGrid#102]
In the example spreadsheet, when we try to grow a selection with Shift + arrow-keys:
- when we start with a rectangular selection, shift + an arrow-key does nothing
- when we start with a single cell selected, shift + an arrow-key works as expected
- when we start with a single cell selected, and then make a rectangular selection, shift + an arrow-key grows the original single-cell-based selection.

This appears to be an activeCell issue (rectangular drag-and-drop selections don't set activeCell).

**Comment by 6pac** [comment]
Thanks. Fixed in commit just now. Will leave for a little while before releasing.
