### ISSUE TITLE
Two minor, easily fixable issues

### ISSUE THREAD

**Issue by jhollandmcs** [6pac/SlickGrid#1056]
### Describe the bug

1. The file `dist/browser/controls/slick.columnpicker.js` has a typo. The function `setColumnVisibiliy` should be called `setColumnVisibility`.
2. This [example page](https://6pac.github.io/SlickGrid/examples/example-column-hidden.html) has a broken link. It should go to [this link](https://github.com/6pac/SlickGrid/blob/master/examples/example-column-hidden.html), but instead it goes to [this broken link](https://github.com/6pac/SlickGrid/blob/master/examples/example-column-visible.html).

### Reproduction

Self-explanatory.

### Which Framework are you using?

Browser

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| (framework used)    | VERSION |
| SlickGrid | VERSION |
| TypeScript          | VERSION |
| Browser(s)          | VERSION |
| System OS           | VERSION |
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/6pac/SlickGrid/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/6pac/SlickGrid/wiki).
- [X] Check that there isn't [already an issue](https://github.com/6pac/SlickGrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/6pac/SlickGrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
closed by #1057
