### ISSUE TITLE
Grid > Plugin: Row details - console.log

### ISSUE THREAD

**Issue by pejrak** [6pac/SlickGrid#1066]
### Describe the bug

There is a console.log leftover in [here](https://github.com/6pac/SlickGrid/blame/c171968f362834fd6c06196f4177d6b20f197066/src/plugins/slick.rowdetailview.ts#L585).

### Reproduction

Run the grid with RowDetails plugin, even the [example](http://6pac.github.io/SlickGrid/examples/example16-row-detail.html). Whenever you collapse / expand the row details, the console.log prints undefined for each row * column.

![image](https://github.com/user-attachments/assets/cf8ffa82-421a-46df-bf0f-02e0d16e0a25)

### Which Framework are you using?

Vanilla / Plain JS

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| (framework used)    | VERSION |
| SlickGrid | VERSION |
| TypeScript          | VERSION |
| Browser(s)          | VERSION |
| System OS           | VERSION |
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/6pac/SlickGrid/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/6pac/SlickGrid/wiki).
- [X] Check that there isn't [already an issue](https://github.com/6pac/SlickGrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/6pac/SlickGrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
closed by #1067
