### ISSUE TITLE
Missing minified slick js and css files

### ISSUE THREAD

**Issue by imsurinder90** [6pac/SlickGrid#107]
I keep slickgrid files under vendor directory but I only see slick non-minified JS and CSS files.
As files are big in size takes much time to load. 

Can you please add minified JS and CSS files ?

**Comment by 6pac** [comment]
https://github.com/6pac/SlickGrid/issues/8, https://github.com/6pac/SlickGrid/issue

also see [the manifesto](https://github.com/6pac/SlickGrid/wiki/The-SlickGrid-Manifesto)
