### ISSUE TITLE
plugin: CellExternalCopyManager, ctrl+v ，body's scroll bar to the bottom

### ISSUE THREAD

**Issue by xijinhua** [6pac/SlickGrid#1078]
### Describe the bug

version: SlickGrid-3.0.2
question: plugin: CellExternalCopyManager, ctrl+v ，body's scroll bar to the bottom
![image](https://github.com/user-attachments/assets/358dd185-8ea0-4aee-b0df-62384155e4a2)

layout example:
![Uploading image.png…]()
<div style="position:relative">
  <div style="width:600px;">
    <div id="myGrid" style="width:100%;height:300px;"></div>
  </div>
  <br/>
  <div style="width:600px;">
    <div id="myGrid2" style="width:100%;height:300px;" class="example-grid"></div>
  </div>
 <div style="height:900px"></div>
</div>

### Reproduction

When I do ctrl+v, the scroll bar of the body does not scroll

### Which Framework are you using?

Vue

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| (framework used)    | VERSION |
| SlickGrid | VERSION |
| TypeScript          | VERSION |
| Browser(s)          | VERSION |
| System OS           | VERSION |
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/6pac/SlickGrid/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/6pac/SlickGrid/wiki).
- [X] Check that there isn't [already an issue](https://github.com/6pac/SlickGrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/6pac/SlickGrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
You're running an old version of SlickGrid (v3.x) that we no longer support since we are now under 5.x. 
If you want us to help you, you will have to provide a full repro (the best way to do this now is to use the Stackblitz link from the main readme and modify the example to reproduce the error). A print screen is not enough as a repro
