### ISSUE TITLE
Rename DataView's `getItem()` to `getRow()`

### ISSUE THREAD

**Issue by tatsujin1** [6pac/SlickGrid#111]
It's a bit confusing that `getItem()` appears to operate on the same data set as `setItems()` `addItem()`, `updateItem()` and `deleteItem()`, which it actually does not. Especially confusing that there is a `getItems()` that *does* operate on the same data set.

In fact, `getItem()` retrieves a "row" which does not even exist until a `refresh()` has been processed (or actually `recalc()`). And if called between a`beginUpdate()`/`/endUpdate()` pair, this is not done synchronously.

For example, at first glance, this code might seem to be good:

```
view.beginUpdate();
view.addItem(theItem);
var firstItem = view.getItem(0);
```
But as you all know, the `getItem()` will fail. (assuming an empty view)

Suggest to rename `getItem()` to `getRow()`.

I realize this rename could also mean that other (public) methods should be renamed, ones that operate on the same data set (i.e. the `rows` member variable)`.

I know this is a breaking change. Deprecation is of course advised. At first merely in the documentation and later even a `console.warn()` could be added to the old method.

**Comment by tatsujin1** [comment]
I guess `getItem()` could also be changed to actually operate on `items` (the same as all other *item methods), but I suppose that's an even bigger breaking change.

**Comment by 6pac** [comment]
I hear you. On my private fork, one of the first things I did was clean up all these naming conventions, which are very confusing and quite inconsistent (a data row is called an 'item', a row index is called a 'row').

However then I rolled back all those changes because it was too hard to keep them in sync with the public fork.
I'd like to issue a v3 someday with all this stuff cleaned up, For now, really we have to live with it. We can't go breaking all the current users' use cases.

**Comment by tatsujin1** [comment]
I see :)
That sounds like a plan!

**Comment by 6pac** [comment]
While deprecation is an option, it's still disruptive in the end. What I tend to prefer is to release a new breaking version and then have an additional package to make it backwards compatible by overriding new features or mapping the old names to the new, like how ```jQuery-migrate``` worked in the old days. That said, it's hard to gauge how popular Slickgrid is, and therefore what impact breaking changes would have.

I have a private branch which may be able to feed back significant changes and improvements, but it's too early to tell yet how many resources I'm going to be able to devote to that - it's part of another project.

**Comment by 6pac** [comment]
I also want to significantly improve the documentation before any new major release. Let's check back here in 6 months.

**Comment by tatsujin1** [comment]
:+1:
