### ISSUE TITLE
checkboxSelectionFormatter function value is undefined 

### ISSUE THREAD

**Issue by srthakkar** [6pac/SlickGrid#113]
The checkbox selection plugin checkbox formatter value is undefined. 
```
function checkboxSelectionFormatter(row, cell, value, columnDef, dataContext) {
            // TODO : value undefined
            if (dataContext) {
                
                return _selectedRowsLookup[row]
                    ? "<input type='checkbox' checked='checked'>"
                    : "<input type='checkbox'>";
            }
            return null;
        }
```

**Comment by 6pac** [comment]
Is this a suggestion for the standard formatter? I can imagine that a developer might want to interpret an undefined value in several different ways. Perhaps best left to individual choice.

**Comment by srthakkar** [comment]
Actually, I need if the checkbox is checked or not in this Formatter.
Can you please guide us if it is possible to get checked is true or false in that value or in any other parameter?

**Comment by 6pac** [comment]
you should be asking on StackOverflow. here is for bug reports.
but

        function checkboxSelectionFormatter(row, cell, value, columnDef, dataContext) {
            if (dataContext) {
                return grid.getSelectedRows().indexOf(row) > -1
                    ? "<input type='checkbox' checked='checked'>"
                    : "<input type='checkbox'>";
            }
            return null;
        }
