### ISSUE TITLE
MultiSect: false option should disable SHIFT + Arrow keys

### ISSUE THREAD

**Issue by SatanEnglish** [6pac/SlickGrid#116]
The MultiSelect: false works well for the clicking version now however not working if you SHIFT up and down.

This is not the most elegant fix but

replace the rowselectionmodel line 123

    if (active >= 0 && active < _grid.getDataLength()) {
     _grid.scrollRowIntoView(active);
     var tempRanges = rowsToRanges(getRowsRange(top, bottom));
     setSelectedRanges(tempRanges);
    }

With the following which updates the top and bottom to the active if multi is false.

    if (active >= 0 && active < _grid.getDataLength()) {
        _grid.scrollRowIntoView(active);
        if (!_grid.getOptions().multiSelect) {
            top = active;
            bottom = active;
        }                    
        var tempRanges = rowsToRanges(getRowsRange(top, bottom));
        setSelectedRanges(tempRanges);                    
    }

**Comment by SatanEnglish** [comment]
@6pac 

Not sure if this is fixed in your current version but you may want to have a look.
Easy fix just don't have time to deal with it currently

**Comment by 6pac** [comment]
Ended up just putting

    function handleKeyDown(e) {
      var activeRow = _grid.getActiveCell();
      if (_grid.getOptions().multiSelect && activeRow 
      && e.shiftKey && !e.ctrlKey && !e.altKey && !e.metaKey 
      && (e.which == Slick.keyCode.UP || e.which == Slick.keyCode.DOWN)) {

at the start of the function instead. Committed. Release soon.
