### ISSUE TITLE
appendCellHtml ignores numeric value 

### ISSUE THREAD

**Issue by evil-shrike** [6pac/SlickGrid#123]
There was a feature added in `appendCellHtml` - supporting complex formatters results (`formatterResult`). When it returns an object instead of string. Nice but it breaks existing code when formatter returns simple non-string value, i.e. number or Date. In this case the value is just ignored.

Current code:
```
      var formatterResult =  getFormatter(row, m)(row, cell, value, m, item);
...
      // if there is a corresponding row (if not, this is the Add New row or this data hasn't been loaded yet)
      if (item) {
        stringArray.push(typeof formatterResult === 'string' ? formatterResult : formatterResult.text);
      }
```
if `formatterResult` is a Number then nothing happens.

**Comment by 6pac** [comment]
I did have a debate with myself over whether to check for a string or not-an-object. Clearly I lost the debate. I've pushed a commit so that any non-object is now treated the same as a string formatter return.

Anything else?

**Comment by evil-shrike** [comment]
It's not quite correct as `typeof null` is `"object"`.
I'd suggest to use `Object.prototype.toString.call` instead of `typeof` :
instead of:
```
    if (typeof formatterResult !== 'object') { 
        cellNode.innerHTML = formatterResult;
        return;
    }
    cellNode.innerHTML = formatterResult.text;
```
this:
```
    if (Object.prototype.toString.call(formatterResult)  !== '[Object object]') { 
        cellNode.innerHTML = formatterResult;
        return;
    }
    cellNode.innerHTML = formatterResult.text;
```

P.S. Please consider referencing issues in your commits as it'll make understanding commit history much easier.
(Just add a comment `#123` in a commit)

**Comment by 6pac** [comment]
Not real keen on that construct, and I note it's not used anywhere else in the code base.
How about:

       if (!formatterResult || typeof formatterResult !== 'object') { 
            cellNode.innerHTML = formatterResult;
            return;
        }

If you're OK with that I'll add the commit.

**Comment by evil-shrike** [comment]
Ok, in this case it will work.
But in general `Object.prototype.toString` is pretty common approach (`v === Object(v)` is another), see https://javascriptweblog.wordpress.com/2011/08/08/fixing-the-javascript-typeof-operator/ for details.

Also I noticed there're other checks with `typeof` for `selectable` and `focusable`. It's better to check for `!== undefined`, any value means it's specified, then convert it to a boolean:
instead 
```
      if (rowMetadata && typeof rowMetadata.selectable === "boolean") {
        return rowMetadata.selectable;
      }
```
do
```
      if (rowMetadata && rowMetadata.selectable !== "undefined") {
        return !!rowMetadata.selectable;
      }
```

**Comment by 6pac** [comment]
OK, you've convinced me. It's in the spec, and my suggestion doesn't cover a Date.
Also tweaked the other typeofs, that makes sense.

This has been committed and referenced to this issue.
Happy to take pull requests!
