### ISSUE TITLE
SlickGrid does not show all the columns when switching Bootstrap tabs

### ISSUE THREAD

**Issue by dad-exuan** [6pac/SlickGrid#125]
- there are two Bootstrap tabs and each tab has a SlickGrid, which are initialized together after the page is loaded
- the first visible grid shows properly, the second grid shows only one column when switching tab
- after tracing the source code, the cause is that viewportW is zero in grid.setColumns()
- our call flow are as follows:

1. call grid.init() explicitly and in finishInitialization(): viewportW is 0 at line 307 and be non-zero after createColumnHeaders()
2. the problem is restoreCssFromHiddenInit().  After the styles are restored, the viewportW in the closure is non-zero, but if you call grid.setColumns(), the viewportW is recalculated and be zero.
3. for we will set the columns dynamically, so after call the grid.setColumns() -> resizeCanvas(), the viewportW is zero.  When viewportW is zero, after the first column, SlickGrid thinks that the columns are out of visible area and does not show them.
- it seems that the jQuery css("width") may consider the visibility of the DOM element
- to solve the problem temporarily, we set the width explicitly. But it makes SlickGrid not responsive.

**Comment by 6pac** [comment]
Thanks for the report. I've not been aware of any problems with restoreCssFromHiddenInit(). Could you put together an example that runs in the Slickgrid example folder and attach it to a post in this thread?
Have you checked out the examples that show grid in tabs?

**Comment by maxim-s-barabash** [comment]
You can draw after Grid visibility. Method does not pretend to be correct :)

```
  grid = new Slick.Grid("#myGrid", dataView, columns, options);
  
  grid._render = grid.render;
  grid.render = function (){
    var $c = $(this.getContainerNode()),
        that = this;

    if ($c.is(':hidden') && !this.___hiddenTimer){
       this.___hiddenTimer = setInterval(function () {
           if (!$c.is(':hidden')) {
               clearInterval(that.___hiddenTimer);
               that.___hiddenTimer = null;
               that._render();
           }
       }, 300);
    }
  }

  grid._resizeCanvas = grid.resizeCanvas;
  grid.resizeCanvas = function (){
    var $c = $(this.getContainerNode()),
        that = this;

    if ($c.is(':hidden') && !this.___hiddenTimer){
       this.___hiddenTimer = setInterval(function () {
           if (!$c.is(':hidden')) {
               clearInterval(that.___hiddenTimer);
               that.___hiddenTimer = null;
               that._resizeCanvas();
           }
       }, 300);
    }
  }
```

And do not forget about the destroy.

```
grid._destroy = grid.destroy;
grid.destroy = function destroy() {
    if ( this.___hiddenTimer ) {
               clearInterval(that.___hiddenTimer);
               that.___hiddenTimer = null;
    }
}
```

**Comment by javastud** [comment]
Yes. I am facing same problem. +1

**Comment by 6pac** [comment]
Just checking that everyone interested in this thread has checked out http://6pac.github.io/SlickGrid/examples/example-dynamic-with-jquery-tabs.html
Does this example help?

If not, then, as requested, please
> put together an example that runs in the Slickgrid example folder and attach it to a post in this thread?
