### ISSUE TITLE
Column resize on cell drag

### ISSUE THREAD

**Issue by danmo** [6pac/SlickGrid#126]
Hi, currently a column width can be resized by dragging the column edge.

I need to do the same by dragging the cell, any idea on how I can achieve this ?

![image](https://user-images.githubusercontent.com/3957234/27768772-0f0493b0-5f24-11e7-823a-4f7fe14c7167.png)

**Comment by 6pac** [comment]
The code to create the column drag resizing in there in the initialise event. You'd need to apply it to all rendered rows. Given that the grid is constantly destroying and recreating rows during scrolling, it's going to be slow and you might have to keep track of and remove the hooks before removing rows to avoid a memory leak.

You might be best off using:
http://6pac.github.io/SlickGrid/examples/example10-async-post-render.html
and
http://6pac.github.io/SlickGrid/examples/example10a-async-post-render-cleanup.html
