### ISSUE TITLE
Toggle columns

### ISSUE THREAD

**Issue by clemorphy** [6pac/SlickGrid#127]
Hello

Is there a way to toggle columns visibility ?
Like having a list of all possible columns, with a checkbox for each, that would allow to hide / show ?
I quickly searched in the Columns part of the API reference, but didn't find any option that could toggle column visibility.

Thanx

**Comment by maxim-s-barabash** [comment]
If you want to hide a column, just remove it from the columns array you call grid.setColumns() again.

**Comment by maxim-s-barabash** [comment]
See context menu on grid header 
http://6pac.github.io/SlickGrid/examples/example-grouping-checkbox-row-select.html

**Comment by clemorphy** [comment]
@maxim-s-barabash  slick.columnpicker.js is exactly what I was looking for.
Thanx

**Comment by ghiscoding** [comment]
FYI guys, I reworked the column picker to make it more user friendly which I made a PR #159 just a few days ago (you can read the details inside the PR #159). 

I'm also currently working on a Grid Menu (top right corner Grid Menu, which also works better on a touch device I would assume). I hope to make this piece customizable to give flexibility to the user to add custom sub-menus as well (I'm working on the latter now). What I have achieved so far (I basically took the code from my PR #159, so I got the column picker in it), still working on the custom sub-menus part. 

See the result below of what is coming :)

![gridmenu](https://user-images.githubusercontent.com/643976/30791732-78f7bb9e-a182-11e7-8104-8d4691f5a259.jpg)

**Comment by ghiscoding** [comment]
Made PR #160 to add the Grid Menu functionality that I described in earlier post. It also includes an easy way to add custom command in it (for example add a "Clear Filters"). You can see a full description of it on the PR #160
