### ISSUE TITLE
Feature request: onBeforeAcitiveRowChanged\onAcitiveRowChanged Event

### ISSUE THREAD

**Issue by andyforever** [6pac/SlickGrid#13]
Hi, I need to know the event when the active row changed(like keyboard navigate or mouse click), so I can deal with the row validation. Could you please provide the onBeforeAcitiveRowChanged or onAcitiveRowChanged methods for me. THX.

**Comment by zoechi** [comment]
You could use `onActiveCellChanged`. 
Remember the last row and do validation when the row of the new cell (passed with the event) differs from the remembered row

**Comment by 6pac** [comment]
I agree this is the only option at the moment. SlickGrid uses a less 'row-based' paradigm than a lot of other grids. It does not impose a particular editing/validation strategy, so this is up to the developer to superimpose.

**Comment by manju-reddys** [comment]
See more in my (repo)[https://github.com/manju-reddys/SlickGrid], I had similar requirements

**Comment by andyforever** [comment]
@manju-reddys I don't get which change is related to my requirements in your repo. Could you explain it for me? Thx.

#### This repo made following changes

1. Column configuration have new property `preventClearOnEdit`.
    - This basically prevent the cell content get clear on editor get activate.
    - Helpful in case's like [here](https://github.com/6pac/SlickGrid/issues/11).

2. Now the editor will receive event as second parameter when available.

3. Two new events are added `onInitialize` and `onRendered`.
    - `onInitialize` will be get called when the actual init is finished (in case of lazy init enable it get called after that).
    - `onRendered` will be called after the `render' completes.
    
4. Exposed following 4 methods:
    - `getHeaderWidth` to get the header width.
    - `getCanvasWidth` return the canvas width.
    - `getViewportHeight` return viewport height.
    - `getUID` return the grid ID.

5. Added `minimumContainerHeight` grid option. This is particularly useful when the grid element (container) reveal/show/appear on click (or pragmatically). 
    - Example: carousel in bootstrap where the slides are hidden (have zero height?).
    
6. Implemented the total plugin (footer), its stays at the bottom (make sure to enable `enableAddRow` to prevent the last row hiding).
    - It fire `onRendered` event each time the footer created and recalculated (`onDataviewRefreshed` - DataView {insert, delete etc..}, `onColumnsReordered`, `onColumnsResized` and `onInitialize` Grid).
    - Pass `updateSummaryData` method in options and implement to calculate the total row columns values.
        - It it will receive 3 parameters `items`, `columns` and `callback`.
        - One must call the callback with data (see example in the totals plugin code for example).
    - You can pass `aggregator` for each column in the column definition.
        - Aggregator will receive 4 parameters `{sum: <<values>>, values: [<values>>]}, columnDef, event, args`.
        - It must return the value.
