### ISSUE TITLE
Tree Group with check box selections

### ISSUE THREAD

**Issue by harit2101** [6pac/SlickGrid#130]
Hi,

My requirement is like a tree with expand, collapse and checkbox functionality.
Done with display of tree with expand and collapse functionality .
Need help in implementation of checkbox functionality so that it covers below scenarios

parent node selected then all child nodes must be selected.
2)parent node unchecked then all child nodes must be unchecked.
if parent has 3 child node, out of which 1 child node is checked and 2 are unchecked then parent node must be in intermediate state of checkbox. Like half selected.
if user manually unchecked all child node then parent node must be unchecked.
Below is tree structure

rootNode
--child1
--child2
---childOFChild2
Followed below link for tree implementation.
https://github.com/mleibman/SlickGrid/blob/gh-pages/examples/example5-collapsing.html
Any help would be GREAT..

**Comment by 6pac** [comment]
This example might get you started:
http://6pac.github.io/SlickGrid/examples/example-grouping-checkbox-row-select.html

I considered the intermediate checkbox state when putting the example together, but it adds a huge amount of extra work. The example as it is just sets or clears the group.

**Comment by 6pac** [comment]
See #165 for more details.
