### ISSUE TITLE
Rails integration

### ISSUE THREAD

**Issue by ssnyder** [6pac/SlickGrid#134]
A couple of years ago we used the slick-grid-rails gem to use what was at that time the current SlickGrid code in our Ruby on Rails application.  I am in the process of updating our program, and all of the various gems, and was hoping to look into upgrading SlickGrid.  I see in the slick-grid-rails gem where to change the URL for the update task, so that's not an issue (That gem looks like it's no longer maintained).  I'm just wondering if there is anything I should look out for that might be obvious to a more experienced Ruby on Rails developer than I am.

**Comment by 6pac** [comment]
Hi @ssnyder, 
I'm the maintainer, but afraid I don't have any experience with Ruby on Rails. 

What I generally do in these situations is try to work out the fork point from the main Slickgrid code, and diff the files to see the changes that were made. If not too extensive, these can usually be reapplied to the most recent Slickgrid code without much pain. 
It's even possible to wrap the changes in a Git 'patch' so they can automatically be applied to the latest release by a build script. This can be less painful than maintaining a separate repo, but, as usual, 'it depends' (TM) on the changes necessary.

I'm happy to incorporate extra files into the main repo for compatibility, but there is a limit to this if it starts to make work for those who don't use that particular technology.

Ben McIntyre

**Comment by ssnyder** [comment]
Thanks!  I'll have to figure out just how old my code is and go from there :)

**Comment by erlingur** [comment]
I've created a Rails gem for the latest version of SlickGrid (2.3.16):

https://github.com/Reiknistofa/slickgrid

**Comment by 6pac** [comment]
I'll be putting up a SlickGrid web page soon. Have mentioned this in the web page.

**Comment by erlingur** [comment]
Awesome! Sounds good :) Also, if I can help with the web page let me know!

**Comment by 6pac** [comment]
If you're keen, that would be awesome! I'm just aiming for an effectively static site with maybe 5 pages, to clear up the confusion around the old MLeibman repo and give some basic guidance. Since dynamic sites are so easy, I was considering implementing a markdown interpreter. However, all this is flexible. I could send my markdown if you'd like to see it. What aspects are you up for?

**Comment by erlingur** [comment]
Sure! Send'em my way. I've recently been setting up my [personal site](https://erlingur.is) with [Hugo](https://gohugo.io). It's a static site generator that uses markdown files for the pages and posts. It's working fine enough, plenty of themes available if that's something you need. I'm not a huge designer (I can manage though) but I'm good with both backend and frontend programming.

**Comment by 6pac** [comment]
Will do. On another note, closing this issue.
