### ISSUE TITLE
Customize top right square

### ISSUE THREAD

**Issue by kofifus** [6pac/SlickGrid#135]
Is there a way or can there be away to customize the empty rectangle to the right of the rightmost column ?

I want to put a button there.

Thx!

**Comment by ghiscoding** [comment]
It's doable with jQuery, I'm working on a Grid Menu (which I will create a PR for in a week or 2) that will take that position. Let say your button is 14px wide.

The javascript looks like this:
```javascript
var buttonWidth = 16;
$header = $('.slick-header');

// resize headermenu minus the button size
$header.width($header.width() - buttonWidth);

// create button and insert it before the header
$button = $('<span class="my-custom-btn"><button onclick="doSomething()"></button><span>');
$button.insertBefore($header);
```
and a little bit of CSS
```css
.my-custom-btn {
  position: absolute;
  right: 2px;
  top: 0;
}
.my-custom-btn > button {
  border: 0;
  margin-top: 5px;
}
```

The end result is a button that stick to the top right, it never moves (because it is at position `right:2px` and this is only possible because i resized the `.slick-header` div. You could do it without the resize and add it at the end of the `.slick-header-columns` but it won't stick at the position. 

Here's the result in my case for my upcoming Grid Menu feature
![gridmenu](https://user-images.githubusercontent.com/643976/30791527-08dd3bbe-a181-11e7-98d6-1cd4892ad4a7.jpg)

**Comment by kofifus** [comment]
great ! thx, waiting for the PR ..

**Comment by ghiscoding** [comment]
I made PR #160 to add a Grid Menu functionality (aka hamburger menu) which was mentioned earlier. The neat thing is that you can also provide an array of your custom command :)

Until this is merge, you can download and provide feedback there. Thanks

**Comment by ghiscoding** [comment]
Side note, if my PR for the Grid Menu is what you were looking for, I suggest to close your issue ;)

**Comment by ghiscoding** [comment]
For reference purpose, the code that I mentioned earlier will break the grid auto-resize functionality as I found out while testing my new Grid Menu feature. A better way of dealing with the resize of the Header Row is to let CSS do the calculation against 100% and this calc will always recalculate which mean that if the grid size changes, the CSS calc will calculate again.
```javascript
$('.slick-header').attr('style', 'width: calc(100% - 18px)');
```
You could also avoid javascript completely and only use CSS this way
```css
.slick-header {
  width: calc(100% - 18px);
}
```

**Comment by kofifus** [comment]
Note that the scrollbar size is not always 18px as the scrollbar can be
changed to be narrower etc

see (merged) https://github.com/6pac/SlickGrid/pull/149

scrollbar width should be retrieved using scrollbarDimensions.width

**Comment by ghiscoding** [comment]
The width of 18px is just for demo purposes, I left it open as an option for the Grid Menu that I created. You can change it with the value you want.

**Comment by kofifus** [comment]
ah ok, but how can the PR be merged it breaks auto resizing ? can you explain what is the issue ?

**Comment by ghiscoding** [comment]
It doesn't break auto-resizing, or at least not anymore. The first portion of the code that I posted as an answer to you at the beginning had a flaw when combined with grid auto-resize on browser resize (which I made another [PR](https://github.com/6pac/SlickGrid/pull/157) recently for that feature). If you resize the header at a fixed width, then the header doesn't auto-resize anymore (while the rest of the grid does), to avoid this, it's better to use CSS width `calc(100% - 18px)`. This code will make sure that the header width follows the grid width, that is what I found while having this code in production.

**Comment by kofifus** [comment]
sorry I'm confused .. I don't see any `.slick-header` in the current #160 example. So I don't understand if it's needed or not. Is the example-grid-menu.html you posted breaks auto-resizing ?

**Comment by ghiscoding** [comment]
It's in the [plugin](https://github.com/6pac/SlickGrid/pull/160/files#diff-49b0c1a3f362a16863f5a924d92a7090R94) itself. Your original question was about "How to customize top right square" and all the code I gave you was to configure that. That code is used in the Plugin of the PR, when calling the Plugin you don't have to know about this backend code.

**Comment by kofifus** [comment]
got it, thx

**Comment by ghiscoding** [comment]
FYI, the PR for Grid Menu got merged a day ago.
