### ISSUE TITLE
Horizontal scrolling of header does not work

### ISSUE THREAD

**Issue by johanrd** [6pac/SlickGrid#136]
Ref https://github.com/mleibman/SlickGrid/issues/987

Steps to reproduce:
1. Go here: http://6pac.github.io/SlickGrid/examples/example12-fillbrowser.html
2. Hold your cursor over the header and scroll horizontally – nothing happens
3. Hold your cursor over the content and scroll horizontally – both header and content scrolls

Expected: case 2 to behave like case 3

**Comment by ghiscoding** [comment]
Since there was a PR merged, the issue can probably be closed?

**Comment by 6pac** [comment]
Hi @johanrd , the header scroll handling is causing the horizontal scrolling to be very slow. I can't reproduce the actual original problem. Not sure how you even scroll horizontally over the header - is this a touch-screen thing? Just wondering if you could shed some light, or I might remove this change.

**Comment by erlingur** [comment]
Just wanted to add to this that I'm also experiencing very laggy horizontal scrolling in a grid with many columns after this change. There's a big difference with the jankyness between 2.3.8 and 2.3.9.

**Comment by 6pac** [comment]
I think I'll reverse this. I suspect an HTML solution to the original issue might be a lot more effective anyway.

**Comment by erlingur** [comment]
Sounds good. On a sidenote, I'm making a Rails gem for this fork, I'll post a link to it when it's ready :)

**Comment by 6pac** [comment]
Reversed in https://github.com/6pac/SlickGrid/releases/tag/2.3.16
