### ISSUE TITLE
Combining cellselectionmodel and rowselectionmodel

### ISSUE THREAD

**Issue by codeme** [6pac/SlickGrid#144]
Is there a way to combine these 2 selection models, so that I can achieve what these 2 models do. The requirement i am looking for is, user should be able to select row or multiple rows using a custom checkbox column (using shortcuts ctrl+click and shift+ click) and also able to select multiple cells (using ctrl+click and shift+click). If these 2 models cannot be combined. Is there any other alternative to achieve this?

**Comment by 6pac** [comment]
For these type of custom things, you need to create a new selectionmodel and combine the code from the two. It shouldn't be too hard. I don't think it's a common enough thing to want to do, to make it standard.
