### ISSUE TITLE
How to put Button Inside the slickgrid In new raw.

### ISSUE THREAD

**Issue by smitlad** [6pac/SlickGrid#145]
hi, There 
I want to ask you that how to put button inside the slick grid in new raw.
give me some example so i get some idea.  i want to create slick grid like first raw with data and new raw with button.

**Comment by 6pac** [comment]
The easiest way is to use a formatter to create a link styled like a button.  
Here's one of mine:

    function EditButtonFormatter(rowIndex, cell, value, columnDef, grid, dataProvider) {
      if (value == null || value === "" || !columnDef.hyperlink) { return "-"; }
      return '<div class="' + Slick.preClickClassName + '" onclick="' + columnDef.hyperlink + '(' + value + ')">edit</div>';
    }

**Comment by smitlad** [comment]
Thank you, so much for your help.
