### ISSUE TITLE
checkboxselectcolumn : invalidateRow results in slickgrid lost focus

### ISSUE THREAD

**Issue by codeme** [6pac/SlickGrid#146]
Using a checkboxselectcolumn plugin results in loosing focus on slickgrid. Caused by invalidateRow() statement. Is there a way to retain the focus on the grid?

**Comment by 6pac** [comment]
Probably best to post this kind of thing to StackOverflow. 
In 6pac.github.io/SlickGrid/examples/example-checkbox-row-select.html if I use the keyboard to navigate up and down and space to select/deselect, it works fine. However the grid doesn't have keyboard focus to start with, I have to click on a cell.

**Comment by codeme** [comment]
We are seeing this issue on click of a cell

**Comment by 6pac** [comment]
Have you tried putting ```grid.setActiveCell()``` and ```grid.focus()``` after handling the click event?

**Comment by codeme** [comment]
yes, I did. grid.focus() is not helping. tabbingDirection is "1" and it ends up in else part of setFocus() function.

**Comment by 6pac** [comment]
Pushed a fix. Esentially the last two lines of 

    function toggleRowSelection(row) {
      if (_selectedRowsLookup[row]) {
        _grid.setSelectedRows($.grep(_grid.getSelectedRows(), function (n) {
          return n != row
        }));
      } else {
        _grid.setSelectedRows(_grid.getSelectedRows().concat(row));
      }
      _grid.setActiveCell(row, getCheckboxColumnCellIndex());
      _grid.focus();
    }

and the definition of ```getCheckboxColumnCellIndex```
