### ISSUE TITLE
Example column group (header row grouping) is not working correctly when resizing

### ISSUE THREAD

**Issue by ghiscoding** [6pac/SlickGrid#147]
Trying the various samples and noticed that the [Example Column Group](http://6pac.github.io/SlickGrid/examples/example-column-group.html) is not behaving properly after resizing. After resizing a column from the second row (for example making Title wider), the first row (that is the columnGroup) completely disappears. I found the problem with some width changing, see below for the full explanation.

If this makes any difference, the same example on the [X-Slickgrid fork](http://ddomingues.com/X-SlickGrid/liveDemo/examples/example-group-header.html), it is working correctly there. 

If we take the original example, without resizing anything, the html is the following
![beforeresize](https://user-images.githubusercontent.com/643976/30142644-f5572698-934f-11e7-8a00-2f1cf8af41ab.jpg)

If I resize the "Title" column and make it wider by 20px, the first row disappears. 
![afterresizegrid](https://user-images.githubusercontent.com/643976/30142592-a9f6a548-934f-11e7-8fdc-155763d92025.jpg)

Then we notice the width becomes incorrect at 2 places (the width of 1600px becomes 580px) 
![afterresize](https://user-images.githubusercontent.com/643976/30142662-0e7e1424-9350-11e7-9ba0-9db5f67b7c3a.jpg)

If I manually change the width of the first div and put it back to 1600px, then manually change the width of the 2nd column (which is "Common Factor") to 211px (that is 191px + 20px wider = 211px) then the result is fixed on the screen
![afterresizewithfix](https://user-images.githubusercontent.com/643976/30142749-7a47d028-9350-11e7-82f1-b69659d8085b.jpg)

![afterresizegridwithfix](https://user-images.githubusercontent.com/643976/30142743-7167f80c-9350-11e7-8ab1-2483bef74b5c.jpg)

**Comment by ghiscoding** [comment]
Also the "View Source" from the same example is linked to the incorrect sample. If should be linked to [this](https://github.com/6pac/SlickGrid/blob/master/examples/example-column-group.html)

**Comment by 6pac** [comment]
Just pushed a fix. Thanks for bringing this to my attention!

**Comment by ghiscoding** [comment]
Awesome, thanks for the super fast fix :)
