### ISSUE TITLE
Single click vs double click in header row

### ISSUE THREAD

**Issue by codeme** [6pac/SlickGrid#148]
Is there a way to identify a single click from double click event on header row? Does the plugin support it?

**Comment by 6pac** [comment]
Looks like double clicking is a bit tricky anyway:

   https://github.com/mleibman/SlickGrid/issues/994

   https://stackoverflow.com/questions/11573901/slickgrid-dblclick-click

This is the code from ```slick.grid.js``` where the event is handled. You'd just have to add similar handing to the header element.

    $canvas
        .on("keydown", handleKeyDown)
        .on("click", handleClick)
        .on("dblclick", handleDblClick)

It's kind of expected that Slickgrid needs a bit of tweaking to suit specific use cases.
