### ISSUE TITLE
Copy Text from cell content is broken in non-IE browsers

### ISSUE THREAD

**Issue by ghiscoding** [6pac/SlickGrid#150]
Hello, I'm coming back to SlickGrid (had to move away for UI-Grid with AngularJS in the past 2 years) and I remember that the copy text content wasn't working in Chrome/Firefox in the past and I had to patch it in the slickgrid library. I had to do an extensive search to find back the solution and here it is, it's a [StackOverflow question](https://stackoverflow.com/questions/18397036/slickgrid-cell-text-selection-does-not-work-properly-in-chrome-or-firefox) which points to a [Github patch](https://github.com/ptraca/SlickGrid/commit/f85f023ec945e968d27f11151164d9e9881631a4) of the `slick.grid.js` file.

The patch mentioned was the following (specifically the addition of `options.editable && ` to the `if`)
```diff
function handleClick(e) {
    if (!currentEditor) {
          // if this click resulted in some cell child node getting focus,
          // don't steal it back - keyboard events will still bubble up
-        if (e.target != document.activeElement) {
+        if (options.editable && e.target != document.activeElement) {
            setFocus();
          }
        }
```
and your code, shown below, it doesn't seem to have the patch (on the [handleClick(e)](https://github.com/6pac/SlickGrid/blob/master/slick.grid.js#L2679) function, starting at [line 2674](https://github.com/6pac/SlickGrid/blob/master/slick.grid.js#L2674))
```javascript
function handleClick(e) {
      if (!currentEditor) {
        // if this click resulted in some cell child node getting focus,
        // don't steal it back - keyboard events will still bubble up
        // IE9+ seems to default DIVs to tabIndex=0 instead of -1, so check for cell clicks directly.
        if (e.target != document.activeElement || $(e.target).hasClass("slick-cell")) {
          setFocus();
        }
      }
```

So it looks like the patch is not in your code, would it be possible to add it so that the copy text would work in Chrome/Firefox (at the moment it only works in IE)? Thanks for the great support, I will probably contribute to your repo very soon since I'm back with SlickGrid :)

Note: I haven't tried the patch with your code, but I had it in place with previous version of SlickGrid and it was working at that time. Thanks

**Comment by ghiscoding** [comment]
Actually that doesn't seem to work, this patch was only to remove the selection. I just found out that to make it work in Chrome, I have to right+click on the text and choose copy. If I do Ctrl+C that doesn't work, kinda strange that it doesn't work though in IE it's all fine.

**Comment by 6pac** [comment]
I'm too busy to look at this for a few days, but have you seen the new example http://6pac.github.io/SlickGrid/examples/example-excel-compatible-spreadsheet.html ?
It has ctrl-C and ctrl-V cut and paste.

There are quite a lot of new examples now compared to the MLeibman repo.
http://6pac.github.io/SlickGrid/examples/

**Comment by ghiscoding** [comment]
Yeah I did see that one, I guess that I will implement that instead, it's probably a better solution. Thanks for the quick response. I'll close the issue and look at implementing your other suggestion. You're doing a great job with this project :)
