### ISSUE TITLE
Close Select2 dropdown on selecting an option.

### ISSUE THREAD

**Issue by BilalHalayqa** [6pac/SlickGrid#151]
Referring to this dropdown demo :
http://6pac.github.io/SlickGrid/examples/example-select2-editor.html

How can I close the dropdown on selecting an option instead of selecting outside to apply the selection ?

**Comment by 6pac** [comment]
For me, on Chrome, it closes after clicking on a line in the combo box.
If selecting using the keyboard, <enter> closes the box.

Is this different for you? Browser & OS?
