### ISSUE TITLE
Clearing cell sets the value to 0 incase of editor: Slick.Editors.Float instead of clearing it

### ISSUE THREAD

**Issue by BilalHalayqa** [6pac/SlickGrid#152]
Using :
editor: Slick.Editors.Float

For a column, when clearing the cell, the value 0 is being used and cannot clear the cell.

**Comment by BilalHalayqa** [comment]
I had to edit **slick.editors.js** and added the following :
`if(state == 0){
   state = '';
} ` 

in the applyValue method inside the FloatEditor function.

**Comment by 6pac** [comment]
just released a commit to support this mode.
https://github.com/6pac/SlickGrid/commit/50f9a5a682587dd20f9f1daf9d805dfaf1326f48
