### ISSUE TITLE
(feature) grid auto-resize on window resize

### ISSUE THREAD

**Issue by ghiscoding** [6pac/SlickGrid#154]
Hello, I would like to contribute with a feature that I used for quite a while (auto-resize the grid while the window changes size). It basically takes the available space left from the viewport (it does not take the entire screen, but really only the space it has available, for example if you have a container of 80% width, it will only resize in that area). For this to work, we need to wrap the grid in a `<div>` container and use that container for the resize (we resize the container and the grid takes the available space). 

Perhaps issue #31 is also related to this functionality. 

I already made an example based on the basic grid (see the result below). 
If you want the feature then just let me know and I'll be happy to create a PR for it. 

For a quick explanation:
I mainly use the `$(window).on('resize')`, then calculate the available viewport space and change the grid height/width then finally call a `grid.resizeCanvas();`. 

Thanks again for all the support you give to this project

![2017-09-13_20-56-36](https://user-images.githubusercontent.com/643976/30407421-27d7e0a0-98c6-11e7-8c0d-c3f9a5889223.gif)

**Comment by 6pac** [comment]
a PR on this one would be great. it's a feature that's been needed for a while, but I haven't had the time to look into it.

**Comment by ghiscoding** [comment]
I did the PR, which you merged few hours ago... #155 

Since you merged it, I can now close this issue. Thanks for merging :)

**Comment by ghiscoding** [comment]
Actually I just realized that I had 2 PRs and I made a mistake on the second PR. I deleted the code from the first PR thinking that it was the correct way but I just realized that by doing this, I totally deleted the sample :(

Sorry about the mistake, I'm still learning on the Git side...
Do you want me to create another PR to put it back?

Also, I find that strange that the example of `example-plugin-headermenu.html` seems to still have the old code and is not working with my merged code (the example on the web still has previous functionality not my including changes), however if I click the link [view source on Github](https://github.com/6pac/SlickGrid/blob/master/examples/example-plugin-headermenu.html), it does have my merged code. Did I miss a section or can you fix that?

**Comment by 6pac** [comment]
sorry, that's my fault. I need to regenerate the examples when there's a
change. in a hurry.

  _____

**Comment by ghiscoding** [comment]
Thanks

As for the mistake I made on removing the auto-resize functionality, I created another PR #157. 
Hopefully this is good this time, sorry about the confusion.

**Comment by ghiscoding** [comment]
I left a note in the PR, the last PR I made for auto-resize, does not show up in the Examples list.

**Comment by ghiscoding** [comment]
Never mind, I just realized that I had to simply update the Wiki and now it all works :)
I can close it now, thanks for all.
