### ISSUE TITLE
Validate on edit cancellation or prevent edit cancelation on grid resize

### ISSUE THREAD

**Issue by igayevoy** [6pac/SlickGrid#158]
Some times changing the value of cell needs validation of another cell. And when its value is incorrect than cancellation must be prevented by validation.
I've try to stop propagation of a 'Escape' key event and thats helped. But edit is cancelled when grid resized.

**Comment by 6pac** [comment]
This gets complicated. I think it's better to use a formatter to indicate an error condition, and validate all the information before saving the row or whole grid.
