### ISSUE TITLE
Is there a fixed total row solution within this fork?

### ISSUE THREAD

**Issue by javexpress** [6pac/SlickGrid#16]
While editing the rows i want to show sum of two columns separately in a fixed total rows in bottom. And a second question is; I cant make grouping since the data is still been editing. Is that possible too?

Thank you in advance.

**Comment by 6pac** [comment]
Have you looked at http://6pac.github.io/SlickGrid/examples/example-totals-via-data-provider.html ?

This does similar to what you want.

**Comment by manju-reddys** [comment]
I have implemented fully functional fixed footer (totals plugin) (here)[https://github.com/manju-reddys/SlickGrid]
