### ISSUE TITLE
CheckboxSelectColumn not works if enableAddRow is set to true

### ISSUE THREAD

**Issue by xiaoyuTR** [6pac/SlickGrid#161]
I found that if I set enableAddRow to true in the Slick Grid options, the CheckboxSelectColumn will not work. I checked the source code of checkboxSelectionFormatter and found that there is a condition before return the checkbox element, if the "dataContext" is null,  the checkboxSelectionFormatter will be set to null. When initialize the Grid, and error will pop up like this,
"ERROR TypeError: Cannot read property 'addClasses' of null"

I am not sure why "if (dataContext)" is added in the checkboxSelectionFormatter. Not sure if the checkbox element can return directly.
Or are there any better way to make both the CheckboxSelectColumn  and enableAddRow  automatically work well?

**Comment by 6pac** [comment]
could you pull or download the very latest code from the repo (not the latest release).
i think this was recently fixed, but I may not have got around to a formal release yet.

**Comment by xiaoyuTR** [comment]
I just download the latest code from master,  I find there are some enhances on "slick.checkboxSelectColumn.js", but I still got the above error.

**Comment by 6pac** [comment]
This should be fixed now.
