### ISSUE TITLE
Error in measureScrollbar function 

### ISSUE THREAD

**Issue by Tpona** [6pac/SlickGrid#163]
Hi2all!

I get the error, in file slick.grid.js in function measureScrollbar at this line:
`      var $outerdiv = $('<div class="' + $('.slick-viewport')[0].className + '" style="position:absolute; top:-10000px; left:-10000px; overflow:auto; width:100px; height:100px;"></div>').appendTo($('.slick-viewport'));
`
An error: TypeError: Cannot read property 'className' of undefined
$('.slick-viewport')[0] - undefined

Maybe if to pass $viewport from init function it seems to be better rather than to get it from dom using selector?

`function init() {
//...
      scrollbarDimensions = scrollbarDimensions || measureScrollbar($viewport); // at line 308
//...
}`

then in measureScrollbar

`    function measureScrollbar(_viewport) {
      var $outerdiv = $('<div class="' + _viewport[0].className + '" style="position:absolute; top:-10000px; left:-10000px; overflow:auto; width:100px; height:100px;"></div>').appendTo(_viewport);
// ...
}`

this changes solved my problem.

**Comment by 6pac** [comment]
This is a really weird problem to be having. Wondering why jQuery an't find the viewport. Wondering if you can modify one of the examples to repro this. It's likely some other HTML in your page is interfering with things.

**Comment by madlemur** [comment]
I get it with the explicit initialization example in Chrome Version 64.0.3282.167 (Official Build) (64-bit) on Win 10 Enterprise serving the code via IIS 10. I first thought it was an issue with my popup blocker, but I've greenlighted localhost. Still getting the error:

```
Uncaught TypeError: Cannot read property 'className' of undefined
    at measureScrollbar (slick.grid.js:482)
    at init (slick.grid.js:309)
    at new SlickGrid (slick.grid.js:3975)
    at HTMLDocument.<anonymous> (example-explicit-initialization.html:75)
    at j (jquery-1.11.2.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.2.min.js:2)
    at Function.ready (jquery-1.11.2.min.js:2)
    at HTMLDocument.J (jquery-1.11.2.min.js:2)
```

**Comment by 6pac** [comment]
Can you see if you get the error running a sample locally? 

The code in init() is:

      $viewport = $("<div class='slick-viewport' style='width:100%;overflow:auto;outline:0;position:relative;;'>").appendTo($container);
      $viewport.css("overflow-y", options.autoHeight ? "hidden" : "auto");
      if (options.viewportClass) $viewport.toggleClass(options.viewportClass, true);

      $canvas = $("<div class='grid-canvas' />").appendTo($viewport);

      scrollbarDimensions = scrollbarDimensions || measureScrollbar();

and then measurescrollbar():

    function measureScrollbar() {
      var $outerdiv = $('<div class="' + $('.slick-viewport')[0].className + '" style="position:absolute; top:-10000px; left:-10000px; overflow:auto; width:100px; height:100px;"></div>').appendTo($('.slick-viewport'));
    ....

so the viewport should be defined by the time it's measured. Possibly it's the update time of the DOM, perhaps jQuery is not finding it if the time period is really short. It's not doing it anywhere else I've seen, so a race condition might be a good explanation.

Have you tried the earlier suggestion of using $viewport in measureScrollbar() ?

**Comment by 6pac** [comment]
try

    function measureScrollbar() {
      var $outerdiv = $('<div class="' + $viewport.className + '" style="position:absolute; top:-10000px; left:-10000px; overflow:auto; width:100px; height:100px;"></div>').appendTo($viewport);
    ...

I've committed that to the repo but not done a release yet.

**Comment by madlemur** [comment]
Pushed it down the road a few lines...
```
Uncaught TypeError: Cannot read property 'offsetWidth' of undefined
    at measureScrollbar (slick.grid.js:485)
    at init (slick.grid.js:309)
    at new SlickGrid (slick.grid.js:3975)
    at HTMLDocument.<anonymous> (example-explicit-initialization.html:75)
    at j (jquery-1.11.2.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.2.min.js:2)
    at Function.ready (jquery-1.11.2.min.js:2)
    at HTMLDocument.J (jquery-1.11.2.min.js:2)
```

On a hunch, I changed the following lines in measureScrollbar():
```
      var dim = {
	width: $outerdiv.offsetWidth - $outerdiv.clientWidth,
	height: $outerdiv.offsetHeight - $outerdiv.clientHeight
      };
```
As $outerdiv isn't an array of objects, but a single object.

This no longer throws errors, and a grid displays, but the scale of the scrollbar is a bit off. As in it's scaled to scroll a grid that's multiple orders of magnitude larger than the actual grid being displayed. I don't know if that's an artifact of the changes I made, or a side-effect of the explicit initialization.

**Comment by madlemur** [comment]
Although I now see that it's only displaying items 1-39 of the 50 originally generated (or the 50000 I changed it to generate)... Urgh. I'll have to try to find some time to help you track down the culprit.

**Comment by 6pac** [comment]
I think an essential thing to do at this stage is to put together a reproduce-able example. You are the only person reporting this. I can't make it happen anywhere here.   
In fact it seems logically impossible, looking at the code, unless you're calling something that calls measureScrollbar() before you call init() on the grid.  
It may be some third party library interfering with things.

Get an example from the repo and try modding that to see if you get the behaviour.

Note also that with any jQuery object (often maked with a $ at the start of the var name), if you take $var[0], that returns the original DOM node.
