### ISSUE TITLE
Select entire column on header click

### ISSUE THREAD

**Issue by codeme** [6pac/SlickGrid#166]
Is there way in slickgrid clicking on header selects that column content?

**Comment by ghiscoding** [comment]
You could maybe combine [Header Button](http://6pac.github.io/SlickGrid/examples/example-plugin-headerbuttons.html) functionality with a custom command of your own to do that action you want

**Comment by codeme** [comment]
Thanks for the suggestion. I tried setSelectedRanges on header click event

**Comment by 6pac** [comment]
This would be a customisation.
