### ISSUE TITLE
Latest version has some strict error issues

### ISSUE THREAD

**Issue by ghiscoding** [6pac/SlickGrid#168]
It looks like my latest 2 PRs caused some errors that were not caught while adding them since none of the files (even `slick.grid.js` itself) has the `use strict` mode. Now I see these errors when trying to build with Angular and the latest version of Slickgrid which is now `2.3.9` (previous version in NPM is over a year old `2.3.3` and I will be stuck with that one until this is fixed). 

The errors are basically happening because of the variable missing declaration (with `var` keyword). For example, here's the first error that I see in the console now:
```bash
$close is not defined
```
which come from a Close icon that I added in the Column Picker and the new Grid Menu. Simply adding the `var` keyword in front of each new variables fixes this issue.

I will create a PR to fix these issues, these were detected by compiling the new version with Angular 4. Sorry about this, I will fix it in the coming hour.

**Comment by 6pac** [comment]
no probs. when i ran *jslint* over the code base a while back, it picked up a heap of small errors like this, that hadn't been detected earlier. it's good to bring a higher standard of error checking to the code.

**Comment by ghiscoding** [comment]
Yeah I just feel ashamed since it took me over an hour to figure out what was happening and then realized it was caused by my PRs :(

So the good news is that I just finished my investigation and only the Column Picker and the Grid Menu are the cause of this problem. To test it all out, I re-installed the latest version `2.3.9`, went into the Slickgrid folder (in `node_modules`), manually applied the fixes (adding `var` keyword and `use strict`) and re-built my library with Angular and everything is back to normal... A new PR will come in the next few minutes. Sorry again :'(

**Comment by ghiscoding** [comment]
The PR is done, sorry about the mess I caused. I tested a both the Column Picker and Grid Menu, it all seems fine now. 

If you could make a new version, that would help me in using the new Grid Menu with Angular. Thanks again and sorry for the distraction.
