### ISSUE TITLE
When using multi select with checkboxes there is no way to prevent the row selection.

### ISSUE THREAD

**Issue by javastud** [6pac/SlickGrid#17]
When using CheckBoxColumn selector with RowSelectionModel, there is no way to handle the selection before it occurs. So i cant prevent the selection ie. user selected two suitable rows and clicked a third one. In this case i need to handle the selection to determine whether the selection is ok or not.

Thank you in advance.

**Comment by 6pac** [comment]
Have a look in `plugins/slick.checkboxselectcolumn.js`. You'll need to override the `handleClick` event.

**Comment by javexpress** [comment]
Yes i looked at it. But it has been fired after the checkbox selected. Cant handle it at this method. We need another way.

**Comment by 6pac** [comment]
You can set the value of the checkbox back to its previous value, in the click event, if you want. There are other options, but they are quite complex (onfocus, etc).
