### ISSUE TITLE
Make the method public: scrollTo

### ISSUE THREAD

**Issue by gkraser** [6pac/SlickGrid#171]
Make the method public: scrollTo.
This will make it possible to synchronize 2 grids vertically to simulate frozen columns:

```javascript
grid.onScroll.subscribe(function(e, args) {
  grid2.scrollTo(args.scrollTop)
  grid2.render()
});
```

**Comment by 6pac** [comment]
Done and committed. Will be in the next release (when it occurs).

**Comment by 6pac** [comment]
https://github.com/mleibman/SlickGrid/issues/1171
