### ISSUE TITLE
When showHeaderRow option is enable, and the user navigates with tab key an exception is thrown

### ISSUE THREAD

**Issue by gabrielAnzaldo** [6pac/SlickGrid#172]
When I navigate with tab key and arrive to the first input filter, the following error appear:

`Uncaught TypeError: Cannot read property 'ESCAPE' of undefined
at HTMLDivElement.handleKeyDown (slick.grid.js:2385)
at HTMLDivElement.dispatch (jquery.js:4665)
at HTMLDivElement.$event.dispatch (jquery.event.drag-2.2.js:374)
at HTMLDivElement.elemData.handle (jquery.js:4333)`

**Comment by gabrielAnzaldo** [comment]
I am using 2.2.5 version.

**Comment by 6pac** [comment]
Hi @gabrielAnzaldo was this resolved? If not, can you tell me which example page you were using?

**Comment by gabrielAnzaldo** [comment]
Hi @6pac  I am working with a wrapper of slickGrid, and I realize that the issue is from the wrapper,not from slickGrid itself.

**Comment by 6pac** [comment]
Ah, thanks.
