### ISSUE TITLE
 Cannot read property 'addClasses' of null

### ISSUE THREAD

**Issue by aliramadan8** [6pac/SlickGrid#174]
i always get this error in the grid ,

Uncaught TypeError: Cannot read property 'addClasses' of null
    at appendCellHtml (slick.grid.js:1724)
    at appendRowHtml (slick.grid.js:1687)
    at renderRows (slick.grid.js:2238)
    at render (slick.grid.js:2307)
    at resizeCanvas (slick.grid.js:1943)
    at SlickGrid.finishInitialization [as init] (slick.grid.js:366)
    at Object.success (fcBusServices:876)
    at fire (jquery.js:3317)
    at Object.fireWith [as resolveWith] (jquery.js:3447)
    at done (jquery.js:9272)

and here is my code to define columns 

        var checkboxSelector = new Slick.CheckboxSelectColumn({
            cssClass: "slick-cell-checkboxsel"
        });
        // preapre check box columns
        fcBusServiceCategoriescolumns.push(checkboxSelector.getColumnDefinition()); 
 
     ```
       fcBusServiceCategoriescolumns.push(
     { id: "ID", name: "@Localizer["ID"]", field: "iD" , toolTip: "ID" ,  cssClass: "cell-title", editor: 
    Slick.Editors.Integer           , cannotTriggerInsert: true             , width: 0, minWidth: 0, maxWidth: 0            
    ,cssClass: "reallyHidden", headerCssClass: "reallyHidden"                , resizable: false                , 
    unselectable: true                , sortable: false                , unfiltered: true , validator: requiredFieldValidator 
    , sortable: true},
    { id: "Name", name: "@Localizer["Name"]", field: "name" , toolTip: "Name" ,  cssClass: "cell-title", editor: 
    Slick.Editors.Text    , sortable: true},
    { id: "Description", name: "@Localizer["Description"]", field: "description" , toolTip: "Description" ,  
    cssClass: "cell-title", editor: Slick.Editors.Text    , sortable: true},
    );
```
and to resolve it i need to do the below change in slick.grid line 1724 

 if (formatterResult != null)
      addlCssClasses += (formatterResult.addClasses ? (addlCssClasses ? ' ' : '') + formatterResult.addClasses : '');

is there any thing wrong am doing ???

**Comment by 6pac** [comment]
I think this was raised as an issue a while back and fixed. It's a problem with the default formatter returning ```null``` in some cases. Have you tried updating to the latest release?

**Comment by aliramadan8** [comment]
my version is SlickGrid v2.3.10

**Comment by 6pac** [comment]
https://github.com/6pac/SlickGrid/releases/tag/2.3.11 release now. let me know if there is still a problem.
