### ISSUE TITLE
getFormatter is called before data loaded (breaking custom user formatters)

### ISSUE THREAD

**Issue by dennisvdm** [6pac/SlickGrid#178]
On master, the code is as follows:

`function appendCellHtml(stringArray, row, cell, colspan, item) {
      var value = null;
      if (item) { value = getDataItemValueForColumn(item, m); }
      var formatterResult = getFormatter(row, m)(row, cell, value, m, item);
      ....
}`

In version 2.3.5 [this commit](https://github.com/6pac/SlickGrid/commit/bef3203d722b96853a312929a74121eac15ebed5) has been added.

Before that commit, getFormatter was called within a check on item:
`
if (item) {
      var value = getDataItemValueForColumn(item, m);
      stringArray.push(typeof formatterResult === 'string' ? formatterResult : formatterResult.text);
      stringArray.push(getFormatter(row, m)(row, cell, value, m, item));		
}
`

So, after that commit, the getFormatter is now being called, even if there is no data loaded yet (item == null).
This means that user defined formatter functions will now be called if item is null, and break when those doesn't null-check.

At other places in the code, the getFormatter is still being checked with an check on the existence of the data.

**Comment by 6pac** [comment]
thanks for tracking that one down - you did most of the work!
https://github.com/6pac/SlickGrid/releases/tag/2.3.11
