### ISSUE TITLE
Increase click target for column resize action

### ISSUE THREAD

**Issue by fulldecent** [6pac/SlickGrid#184]
Minimal example:

http://6pac.github.io/SlickGrid/examples/example1-simple.html

To resize a column you must click between two columns and drag. 

The click target is from 4 pixels left of center line to 1 pixel left of center line. The total click target is a width of 4 pixels and the height of the target is the height of the column heading. Currently it is difficult to find this with your cursor.

Competition:

* Google Sheets: 5 pixels width (center line +- 2 pixels)
* Libre Office Mac: 5 pixels width (center line +- 2 pixels)

**Action: increase resize target to 5 pixels width and center on the center line to be consistent with competition.**
  
![67](https://user-images.githubusercontent.com/382183/34569840-ff1d32c6-f137-11e7-827c-cae6edcc3bd0.gif)

**Comment by 6pac** [comment]
I looked into this, and it's all done with CSS.

If you change the ```.slick-resizable-handle``` class, you can set the width and right boundary.
I found 

    width: 9px;
    right: -5px;

worked reasonably well.

**Comment by fulldecent** [comment]
Thank you for checking this out. The above did not work for me, but this did:

```css
.slick-resizable-handle {
    width: 9px;
    right: -5px;
    z-index: 1;
}

.slick-header-column.ui-state-default {
    overflow: visible;
}
```

![66](https://user-images.githubusercontent.com/382183/34569749-b6403e18-f137-11e7-9cb2-5bb903a1af46.gif)


Using Chrome 63.0.3239.84 / macOS 10.13.2 (17C88).

It appears that the cursor is unequally more on the left of the centerline than the right. This is a bug with Chrome and/or macOS.

**Comment by 6pac** [comment]
Ah, good. Yes, I was just looking at mouseover, I didn't try drag.

I was also puzzled by the uneven width. When I took a screenshot and magnified it, it turned out the line was actually two px wide.

Not sure if this is worth adding to an option - given it is CSS an change would be messy. Adding it to the documentation is probably best.

**Comment by fulldecent** [comment]
Without z-index it would not light up when I hover.

**Comment by 6pac** [comment]
Committed to current repo.
