### ISSUE TITLE
Horizontal scrollbar still covers the last row

### ISSUE THREAD

**Issue by xinchao-zhang** [6pac/SlickGrid#194]
I know this is old and many people have claimed that this has been fixed, but i can still see the very same issue on Chrome 64. 
I hope I have missed something, the simplest way to reproduce is:

1. go to this _official_ example: http://6pac.github.io/SlickGrid/examples/example1-simple.html
2. open dev tools and change the **#myGrid** width from 600px to 300px, horizontal scrollbar should appear
3. scroll to the bottom of the grid, the last row is covered by the horizontal scroll bar

**Comment by 6pac** [comment]
Thanks for the heads up. There was an issue a while back around refreshing scrollbar dimensions, I'll check that out soon. It could just be you need to call ```resizeCanvas()``` after resizing the #mygrid element.

**Comment by 6pac** [comment]
Yes. ```grid.resizeCanvas();```

**Comment by 6pac** [comment]
Extra info for this: resizing the div this way doesn't trigger any events unless you hook them up.

I suggest: http://marcj.github.io/css-element-queries/

From this StackOverflow question: https://stackoverflow.com/questions/6492683/how-to-detect-divs-dimension-changed
