### ISSUE TITLE
Addition of AutoColumnSize Plugin

### ISSUE THREAD

**Issue by ghiscoding** [6pac/SlickGrid#198]
This is a reference issue for a Plugin that @SatanEnglish mentioned and he possibly has a PR coming for that later. Here's a quote about the last Auto-Resize Plugin 
> Hay guys really quick example setup.
Example Auto-Resize-Columns
Seems to not work perfectly if using double click on column resize now. (Think there is some change to the nest version that has affected it)
Resize all button works like a charm tho.
Think the issue line in plugin below as I think I read something in the updates that these bits are now editable/variables on grid?
`clone.style.cssText = 'position: absolute; visibility: hidden;right: auto;text-overflow: initial;white-space: nowrap;';`
Anyway have a play.

and here was one of my quote as well
> As for the `AutoColumnSizePlugin`, I tried the example from this [demo page](https://cdn.rawgit.com/naresh-n/slickgrid-column-data-autosize/master/examples/example-1.html) and I'm very interested. Can you make a separate PR for it and I can review it as well. 

I've opened an issue just to avoid having 2 distinct conversation in 1 issue.

**Comment by SatanEnglish** [comment]
Hay guys really quick example setup.
[Example Auto-Resize-Columns](https://github.com/SatanEnglish/SlickGrid/tree/Aucto-Resize-Columns)

Seems to not work perfectly if using double click on column resize now. (Think there is some change to the nest version that has affected it)

Resize all button works like a charm tho.

Think the issue line in plugin below as I think I read something in the updates that these bits are now editable/variables on grid?
`clone.style.cssText = 'position: absolute; visibility: hidden;right: auto;text-overflow: initial;white-space: nowrap;';`

Anyway have a play.

**Comment by SatanEnglish** [comment]
@ghiscoding

Have you had a look at this?
I'll find some time sometime but i'm not going to be rushing on this one sorry.

**Comment by ghiscoding** [comment]
Just tried your branch with the plugin and it doesn't seem to work as good as the [demo page](https://cdn.rawgit.com/naresh-n/slickgrid-column-data-autosize/master/examples/example-1.html). 

The first few observations
1. The [demo](https://cdn.rawgit.com/naresh-n/slickgrid-column-data-autosize/master/examples/example-1.html) doesn't have `forceFitColumns` and it probably doesn't need it either.
2. If I disable the `forceFitColumns: false`, and I refresh the page then double-click on a row, it resizes all columns. So visually it looks like it's doing a force fit column, even though I just disabled it. 
  - the demo doesn't seem to have that problem either

I didn't look at the plugin code at all, these are just observations.

**Comment by 6pac** [comment]
I'll get back to this one at some point - I've actually been thinking about having a column initialisation option for the sizing, with autosize being one of the options. So I'd like to integrate it more closely with the gird if anything.

**Comment by SatanEnglish** [comment]
Fair enough.

My case for using this is that I have dynamic columns.
I need the force fit ON as I want the grid columns to always take up all the space given so I don't have wasted space at the end. e.g.(If you double click a column in the Demo you end up with empty space to the right) 

In my case I don't know the size of the columns as I don't know whats in them so I normally call the resize all after load so that I'm taking up all available space and they are nicely spaced.

**Comment by ghiscoding** [comment]
I personally don't like using the Force Fit Column, it's nice to see the grid automatically take the space on first load but most users gets frustrated to see that expanding 1 column makes another column shrinks. I personally use disable `forceFitColumn` but use `autosizeColumns()` on first page load. Internally the forceFit does use `autosizeColumns`. Basically using just the `autosizeColumns` is the same doing these 3 steps: 1) enable forceFit, 2) load the grid, 3) disable the forceFit through columnPicker

So I'd like to have this auto column resize to work with/without the force fit.

**Comment by SatanEnglish** [comment]
Yer I changed it to use autosizeColumns as it was reloading the grid when it didn't need to with the version that is in the demo.

e.g. it all got invalidated

**Comment by 6pac** [comment]
Check out the new autosize options: https://github.com/6pac/SlickGrid/wiki/Auto-Column-Sizing
