### ISSUE TITLE
Column reorder does not change the selected rows in rowselectionmodel

### ISSUE THREAD

**Issue by andyforever** [6pac/SlickGrid#20]
For example, there are 10 rows in the grid and I use grid.setSelectionModel to select rows. If I select 1,3,5 rows, then I click the column header, rows are reordered, but the selected rows are still 1,3,5.

**Comment by 6pac** [comment]
Have a look [here] (https://github.com/mleibman/SlickGrid/wiki/DataView) under 'Synchronizing selection & cell CSS styles'

**Comment by andyforever** [comment]
Thanks for the tips. "asyncGridSelection" is just what I need.
