### ISSUE TITLE
Keyboard navigation: setting keyboard focus on cell elements

### ISSUE THREAD

**Issue by paraskt** [6pac/SlickGrid#207]
When doing keyboard navigation, I want to set set keyboard focus on buttons inside slickgrid cell.
The idea was to subscribe to Keydown event and if enter or space is pressed then get all the focussable child elements and set the focus on the first one.
I assumed that event.target would be grid cell and I can easily get all the children. **But it appears that event.target does not point to the active cell (on which enter was pressed)**.
Is there a better way to achieve what I am trying to do.
Here is my code:

    grid.onKeyDown.subscribe((event: KeyboardEvent, args: Slick.OnKeyDownEventArgs<T>) => {
        if ((event.keyCode === 13 || event.keyCode === 32)) {
            // get all the element with tabindex != -1
            const cellElement = event.target as HTMLElement;
            const childElements = cellElement.querySelectorAll('[tabindex="0"]');
            if(childElements && childElements.length) {
                const element = childElements[0] as HTMLElement;
                if(element) {
                    element.focus();
                }
            }
        }
    });

**Comment by ghiscoding** [comment]
please use ` ```javascript  ... code... and ending with ``` `
Your code would be much better to read.

**Comment by 6pac** [comment]
Firstly, there is a mechanism for focusing inside cells with Slickgrid, it's bound up with editing. There is an AutoEdit flag that automatically invokes the editor, otherwise you need to hit <Enter> to do so. Edit mode renders an editor and focuses to it.  
In 'view' mode, without editing, I'm not sure but it wouldn't surprise me if the focus stayed on some outer cell container object.

**Comment by paraskt** [comment]
Does it mean that I have to write a custom editor?

**Comment by 6pac** [comment]
Yes, building an editor is the accepted way of interacting with controls inside a cell.

**Comment by paraskt** [comment]
Thank you 6pac. 
Here is what I did,
My Slickgrid cell contains two buttons, I used column formatter. Then I created a custom editor which onInit creates the exact two buttons. And then I put the focus on the first button programmatically.
Things are working fine.
I have just one issue though, when the editor is being shown, if I click on the button, the grid's onClick does not get called (onKeydown works fine).
Is there a way to invoke grid's onClick when I click on custom editor?

Thanks,
Paras

**Comment by ghiscoding** [comment]
@paraskt 
The [official doc](https://github.com/6pac/SlickGrid/wiki/Writing-custom-cell-editors#intercepting-cell-edits) might be helpful. Can you see if that helps.

**Comment by paraskt** [comment]
@ghiscoding : May be not. editCommandHandler is called after editor destroy() and there is no way to know what was clicked.
I think I am not being very clear, apologies. Here is the full story:
I have a Slickgrid with some cells containing two/three buttons and I am trying to make it keyboard accessible.

**Scenario 1:**
User clicks on the button directly. In this case the grid's onClick is called and it knows what event handler to call based on the id/class.

**Scenario 2:**
User navigates(keyboard) to the cell containing the button. The custom editor popsup with first button selected.
User presses enter/space and grid's onKeydown is called and again from there we know what event handler to call.

**Scenario 3:**
User navigates(keyboard) to the cell containing the button. The custom editor popup with first button selected.
User clicks on the button but grid's on click is not called. 
If the custom editor class knew about the event handlers then I could have called those event from the editor's onClick.
**Is there a way to pass custom parameter when editor is being initialized?**

Below is the code for reference.

**a.html**

```javascript
        <app-shared-grid [columns]="columns" [eventHandlers]="eventHandlers" [enableColumnPicker]="true"
            [dataProvider]="pipelineRunDataProvider" [defaultSortColumn]="defaultSortColumn"
            [columnWidths]="columnWidths" [timeZone]="timeZone" (onSort)="onSort($event)" (onFilterApplied)="onFilterApplied($event)"
            [autoEdit]="true" [editable]="true">
        </app-shared-grid>
```

**a.ts**

```javascript
public columns = [
        {
            id: 'actions', name: stringResources.Monitoring_ActionsLabel, field: 'actions', width: this.columnWidths[1], minWidth: 45,
            editable: true, editor: CustomEditor, formatter: (_row: number, _column: number, value: string, columnDef: {}, run: IPipelineRun) => {
                value = value;
                columnDef = columnDef;
                if (run) {
                    return '<div class="monitoringAction">' +
                           '<div id="monitoringActionActivityView" class="svg-i-20x20-ViewRuns"  title="' + stringResources.ViewActivityRuns + '"></div>' +
                           (run && (run.status !== stringResources.InProgress) ? 
				'<div id="monitoringActionReRun" class="svg-i-20x20_Run"  title="' + stringResources.Rerun + '"></div>' :
                            	'<div id="monitoringActionCancel" class="svg-i-20x20-Inactive"  title="' + stringResources.Cancel + '"></div>') +
                           '</div>';
                }
                return value;
            }
        };
eventHandlers = {
            monitoringActionActivityView: this.runActionClickHandler.bind(this),
            monitoringActionReRun: this.rerunActionClickHandler.bind(this),
            monitoringActionCancel: this.cancelActionClickHandler.bind(this)
        };
```

**grid.ts  --> This initializes Slick grid**

```javascript
@Component({
    selector: 'app-shared-grid',
    styleUrls: ['./slick-default-theme.scss', './grid.component.scss'],
    templateUrl: './grid.component.html',
    encapsulation: ViewEncapsulation.None
})

export class GridComponent<T> implements OnInit, OnChanges, OnDestroy {
    @Input() public columns: Array<Slick.Column<T>>;
    @Input() public eventHandlers: { [eventKey: string]: (item: object, event: MouseEvent|KeyboardEvent) => void };
    ....
    ....
    public ngOnInit(): void {
            grid.onClick.subscribe((event: Event, args: Slick.OnClickEventArgs<T>) => {
                const handler = this.eventHandlers[(event.target as HTMLElement).id];
                if (handler) {
                    handler(this.dataProvider.getItem(args.row) as {}, event as MouseEvent);
                }
            });

            grid.onKeyDown.subscribe((event: KeyboardEvent, args: Slick.OnKeyDownEventArgs<T>) => {
                if (KeyboardUtils.IsKeyboardClickEvent(event)) {
                    const handler = this.eventHandlers[(event.target as HTMLElement).id];
                    if (handler) {
                        handler(this.dataProvider.getItem(args.row) as {}, event);
                    }
                    event.preventDefault();
                    event.stopPropagation();
                }
            });
     }
}
```

**Comment by ghiscoding** [comment]
I didn't read the entire post, sorry I'm at work, but from what I quickly read I think your problem is that the `editor` is a simple property reference (not a call) and you want to add extra arguments to it. If that is the case, what you need is [bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind) which allow you to add arguments (bind extra arguments) to a function whenever that function will be called in the future. 

For example, I wanted to add the `dataView` object to the `dataView.setFilter` so I made the following changes
```diff
- dataView.setFilter(this.customLocalFilter);
+ dataView.setFilter(this.customLocalFilter.bind(this, dataView));

- customLocalFilter(dataView: any, item: any, args: any) { 
+ customLocalFilter(item: any, args: any) { 
}
```
Also note that it adds the argument at the beginning of the arguments list, not sure why it does that though. So if the editor is your own custom editor, I believe you can use the `.bind` 


**Note**
I see you are using Angular, is that your own customization of Slickgrid inside Angular or are you by any chance using my [Angular-Slickgrid](https://github.com/ghiscoding/Angular-Slickgrid) repo? Here's the [demo] github page. I also support [Aurelia-Slickgrid](https://github.com/ghiscoding/aurelia-slickgrid) with roughly 90% of the same code from and between both repos (I prefer Aurelia but we use Angulat at work and they let me open source it). I also contribute quite a lot to 6pac repo as well, since my Angular/Aurelia are basically just wrappers.

**Comment by paraskt** [comment]
@ghiscoding Thank you. This works.
We are not using Aurelia-Slickgrid.

**Comment by paraskt** [comment]
Thank you Ben.

**Comment by 6pac** [comment]
Wrote this up a bit more thoroughly at: https://github.com/6pac/SlickGrid/wiki/Writing-custom-cell-editors
