### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by jtokoph** [6pac/SlickGrid#21]
Scrolling quickly on the basic example causes a bunch of javascript errors: http://6pac.github.io/SlickGrid/examples/example1-simple.html

```
slick.grid.js:2321 Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.handleMouseWheel @ slick.grid.js:2321m.event.dispatch @ jquery-1.11.2.min.js:3$event.dispatch @ jquery.event.drag-2.2.js:374m.event.add.r.handle @ jquery-1.11.2.min.js:3
slick.grid.js:2316 Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.handleMouseWheel @ slick.grid.js:2316m.event.dispatch @ jquery-1.11.2.min.js:3$event.dispatch @ jquery.event.drag-2.2.js:374m.event.add.r.handle @ jquery-1.11.2.min.js:3
```

Using Chrome Version 45.0.2454.99 (64-bit)

**Comment by jtokoph** [comment]
It only seems to spam errors when your mouse is over a column. If your mouse is in a blank area of the grid viewport it doesn't have any errors.

**Comment by 6pac** [comment]
I assume you've tried this on the MLeibman branch and it's not happening
there?

If only here, it's probably due to the additional postrender removal code
recently added. I'll check it out.

**Comment by 6pac** [comment]
Hmmm ... looks like a plain old bug ... forgot to delete a row:

Could you try deleting the marked row below (****, it's row 2316 in
slick.grid.js) and see if that fixes it? I'm having laptop issues at the
moment, it will be a week before I get my proper dev environment back. I
can push the fix however if it works.









*        if (zombieRowNodeFromLastMouseWheelEvent &&
zombieRowNodeFromLastMouseWheelEvent != rowNode) {          ****
$canvas[0].removeChild(zombieRowNodeFromLastMouseWheelEvent);          if
(options.enableAsyncPostRenderCleanup &&
zombieRowPostProcessedFromLastMouseWheelEvent) {
queuePostProcessedRowForCleanup(zombieRowCacheFromLastMouseWheelEvent,
zombieRowPostProcessedFromLastMouseWheelEvent);          } else
{
$canvas[0].removeChild(zombieRowNodeFromLastMouseWheelEvent);          }*


On Sat, Sep 26, 2015 at 10:37 AM, Ben McIntyre <email.ben.mcintyre@gmail.com

**Comment by jtokoph** [comment]
That looks to have done the trick. Thanks for the quick investigation and fix. :shipit:

**Comment by 6pac** [comment]
pushed to repo
