### ISSUE TITLE
While in multi-column sort and numbering columns, numbers are clearing correctly - slick-grid...

### ISSUE THREAD

**Issue by smurphdog** [6pac/SlickGrid#212]
There is an "If" check in the 'setSortColumns' function that prohibits removing the sort column counter if it is the last one. The sort column counter should always be removed and then applied in the code that immediately follows.  

To fix the issue... Remove the line **if (numberCols) { sortIndicatorEl.text(''); }**

**Comment by smurphdog** [comment]
... continued....
Then Add the following line  **sortIndicatorEl.text('');**

**Comment by 6pac** [comment]
You are correct again. Just pushed a new commit fixing #211 and #212 plus a few other issues that became clear once I started playing around with the example page

**Comment by ghiscoding** [comment]
@6pac 
I got your latest code and trying it locally, I saw the misbehavior before but forgot to report it.
However, is that normal that the sorting does a multi-sort without even holding the Shift key?
I thought multi-sort should only come in play with the Shift, not without, but that tri-state works with/without Shift key.

**Comment by 6pac** [comment]
Yeah, the docco is not getting updates (mainly my fault!). Any adjustments welcome!
I keep focusing on the 'big picture', but then not getting to it, and it ends up being no picture at all :-(

Sorting seems to be one of those personal things, I hate single column sorts and always want multi column enabled, with no shift key. The numbers and tri-state give complete control.

Not sure of the best way of letting everyone have their own way without a rat's nest of options.

**Comment by ghiscoding** [comment]
lol you're funny, I think it's because we focus on different pictures haha :-P

I'll add some How to Use on that page when I have a chance. No worries
I prefer with Shift key on the computer, however would prefer without on a mobile/tablet. What makes it nice though is that we can probably change that on the fly as a user preference and let the end user choose. It's always good to have multiple flags, more customization to the users, everyone are different. 

Thanks for the fix Ben

**Comment by smurphdog** [comment]
Thank you for you prompt response and resolution. Unfortunately, your addition of "header.children().prepend("<span class='" + sortIndicatorCssClass + "' />");"  now nests the sorting indicator within the header label. This then impacts folks if they want to have the indicator to the left or **to the right** of the header text. I have a header that has a filter button and a sort indicator (to the right of the header text). This left aligns the header text and makes it cleaner when more often than not there is no sort or if you want to enable sorting, the sort indicator location won't shift the column header text. Could you let me know, when you have a chance, how I can now get this indicator to the right (basically the way the grid was working for the past few years. This change has adverse effects on the overall columns layout and screen real-estate.  Thanks again.

**Comment by ghiscoding** [comment]
@smurphdog 
That's a good point, I also have my sorting icons to the bottom right. I currently use this CSS.
Are you using something similar what I have, are you saying that this doesn't work anymore?

```css
      .slick-sort-indicator {
        position: absolute;
        display: inline-block;
        color: #08c;
        width: 8px;
        height: 5px;
        left: auto;
        right: 10px;
        top: 15px;
      }
```
Giving me the result shown in the print screen 
![sorting](https://user-images.githubusercontent.com/643976/36905872-71850644-1e02-11e8-8334-674839a73cc4.png)

**Comment by smurphdog** [comment]
Previously all I had to do for the header was...

The default Grid's CSS that I am pulling in...
.slick-sort-indicator {
  display: inline-block;
  width: 8px;
  height: 5px;
  margin-left: 4px;
  margin-top: 6px;
  float: left;
}


I've overwritten the Grid's CSS with the following
.slick-sort-indicator {
	float: none;
}

In the header, I have (or potentially have) a Header Text, Sort indicator and Filter indicator.  The "alignment/placement" of the sort indicator when I set the header to multiple rows (I only allow 2 rows currently) is not ideal. It just wraps to the end of the text. But it is consistent and takes up minimal real-estate.  I included a screenshot (I renamed my actual column headers) but I show the multi-select column header along with one column that has a filter and another hovered over to show the dropdown that launches the filter window. Fixing the indicator with CSS is not as flexible as just having it come after the header text. Column resizing and filter indicators along both impact position of the sort indicator and where it feels natural.  I didn't want to play around with CSS Position Absolute which might be troublesome in the various scenarios that I am using the grid in. Basically, if the change didn't go in yesterday to next the indicator before the header text. I would be all set.  Thanks for the continued follow up and I apologize if I'm being too particular.


![sampleheader](https://user-images.githubusercontent.com/2333878/36906272-604ae88c-1e2d-11e8-9900-92a5834d38af.png)

**Comment by ghiscoding** [comment]
You're not too particular, I'm also changing the sorting icon position and so I'm interested to know if my code will break too. 

@6pac 
I have reopen the issue, just so that we can review the CSS position. If we can find a way to re-position the sort icon like we used to do in the past, I'll close it back. But considering what @smurphdog wrote [here](/6pac/SlickGrid/issues/212#issuecomment-369938370) is it possible to fix it in another way without impacting the CSS?

**Comment by 6pac** [comment]
Hey guys, sorry about that. I found that the existing example with its left-positioned indicator was being pushed out of position by the previous column name. Of course the same problem would occur with a right positioned indicator after my changes.

As I've said before, I'm less concerned about doing it my way than in making it possible for everyone to do it the way they want with the least amount of pain. We seem to have a good selection of wants here! :-)  So I probably should put the cell back where it was, and perhaps default my examples to the right edge. That said, do either of you know how to make sure that the number and arrow float left or right reliably given the original ```span``` structure? I come from a database background and HTML is my least developed skill, especially responsive HTML. I'm aware for a lot of people it's the other way around.

I'll have a think about some good control options for this. On the hop right now, I'll have more time later in the weekend.

**Comment by ghiscoding** [comment]
I would rather have the icon and the number in their own `span` so that we could change their styling independently but that would require some CSS change. I think the ideal way would be something like below

```html
<span class="slick-column-name">
    <span class="slick-sort-indicator">
        <span class="indicator-asc"></span>
        <span class="indicator-number">1</span>
    </span>
   Start
</span>
```

**Comment by 6pac** [comment]
I think it's better to go back to the original structure where the indicator is after the name - I did have misgivings about changing it. However I'm fine with splitting the indicator.  
So how about:

    <div class="ui-state-default slick-header-column slick-header-sortable" id="slickgrid_619031start" title="" style="width: 71px;">
        <span class="slick-column-name">Start</span>
        <span class="slick-sort-indicator-asc"></span>
        <span class="slick-sort-indicator-number">2</span>
        <div class="slick-resizable-handle"></div>
    </div>

If you're happy with this, do you have any cunning styling tricks to make the spans appear at left or right?

**Comment by 6pac** [comment]
For now, I've reverted the spans back the way they were. Look forward to working out a better visual solution.

**Comment by ghiscoding** [comment]
@6pac 
Going to that structure is fine with me, as long as the count number has it's separate span so that I can customize it's position/font. 

Which span exactly do you want to appear left/right? 

In my implementation, I like to see it bottom right since I use 2 or 3 rows to show the titles, so I usually have enough room at bottom right. To do that, I simply change to `position: absolute` and fix the top/right margin, then the sorting icon is always at the same place. 

But I'm not sure you that is what you were looking for though. In your case, you give enough room on the left to show the sorting icon, but I don't do that in my implementation, do you want to keep that?

**Comment by 6pac** [comment]
Sooooo, I've been playing with putting the numbering indicator in a different span (as suggested above), but I'm finding that I can't stack the ASC/DESC indicator icon and the number top and bottom without using ```absolute```. @smurphdog has stipulated he can't use that, and I'm reluctant to lock us into one option. My only workaround (other than ```absolute```) would be to put both spans into a parent floated div, but that would complicate things quite a bit more than they already are.   

To please everyone, perhaps we need an option for rendering numbering in the same span or a separate span.

@ghiscoding sorry about breaking the getHeaderRow/FooterRow code. It's fixed, just waiting to sort this issue out and then will do a release.

**Comment by ghiscoding** [comment]
@6pac 
What is the final structure that you have at this point? 

@smurphdog 
Any comments on what HTML structure you would like to have for the sorting icon and it's numbering?

**Comment by smurphdog** [comment]
Hello... I would vote for an option (although more options increases overall complexity). I think that there should be an option to keep it as it was so as not to break folks who styled it one way and a new span/div layout proposed by either of you two, defaulting the option to use the current/old way. 

I also would like to keep the sort indicator and number stacked. I have many columns and real estate is always an important consideration. As far as the "new" HTML structure, not to sound flippant, but it doesn't really matter to me. My thought would be something that could allow the indicator and number to be next to each other like @ghiscoding's suggestion .

Cheers.

**Comment by 6pac** [comment]
OK, new option  ```sortColNumberInSeparateSpan```, default to ```false```. 
If ```false```, structure is: 
```html
<div class="slick-header-column slick-header-sortable" id="slickgrid_619031start">
    <span class="slick-column-name">Start</span>
    <span class="slick-sort-indicator-asc slick-sort-indicator-number">2</span>
    <div class="slick-resizable-handle"></div>
</div>
```

If ```true```, structure is: 
```html
<div class="slick-header-column slick-header-sortable" id="slickgrid_619031start">
    <span class="slick-column-name">Start</span>
    <span class="slick-sort-indicator-asc"></span>
    <span class="slick-sort-indicator-number">2</span>
    <div class="slick-resizable-handle"></div>
</div>
```
This is committed and released.

I'm still having trouble with the sorting indicators dropping down below the cell title and being cut off, when the column is quite narrow (too narrow to display the title). Not sure how to fix that.
