### ISSUE TITLE
The active cell's CSS is updating, not honoring the  showCellSelection flag

### ISSUE THREAD

**Issue by smurphdog** [6pac/SlickGrid#213]
## In function "appendCellHtml"
I believe the 'if' check should be
      if (row === activeRow && cell === activeCell **&& options.showCellSelection**)

I believe that the function 'appendCellHtml' should also check the options.showCellSelection flag before setting the CSS for the active cell. Otherwise, the if there is a global CSS style to highlight all grid's active cell but some grids have turned off this flag, there will be a peculiar experience when rows are added to the HTML, sometimes highlighting them and other times not. If the flag were honored, the highlighting would be more deterministic.

**Comment by smurphdog** [comment]
I believe that the function 'appendCellHtml' should also check the options.showCellSelection flag before setting the CSS for the active cell. Otherwise, the if there is a global CSS style to highlight all grid's active cell but some grids have turned off this flag, there will be a peculiar experience when rows are added to the HTML, sometimes highlighting them and other times not. If the flag were honored, the highlighting would be more deterministic.

**Comment by 6pac** [comment]
Not sure about this one. The active cell is not the same as a selected cell. Two different things.

**Comment by smurphdog** [comment]
That's fine and your call. I only point out the discrepancy between when the setActiveCellInternal is called and the showCellSelection is checked (shown below). In this method if true, the "active" class is added to the cell and row nodes. But in the appendCellHtml function, the "showCellSelection" is not checked and the cell and row are set active. This gives weird results when you have a grid that you are adding and deleting rows from the grid. I've worked around it by adding CSS to ignore the grid that I don't want active highlighting in, but honoring this flag on "both" places and not only one would eliminate the need for the CSS... Again, your call. I just wanted to point out irregularities with the honoring of the showCellSelection flag.

Below the "showCellSelection" flag being honored to see if the cell should be set active in "setActiveCellInternal" function. This class allows one to style the active cell and row if desired.
        if (options.showCellSelection) {
        $(activeCellNode).addClass("active");
        $(rowsCache[activeRow].rowNode).addClass("active");
        }

Thanks again...

**Comment by 6pac** [comment]
As usual, you are correct. Thanks for these insightful observations, they are very valuable. Fixed and pushed.

I was fooled by the option, which is badly named. It should be something like ```hilightActiveCell``` rather than ```showCellSelection```.
