### ISSUE TITLE
getFooterRowColumn broken

### ISSUE THREAD

**Issue by taavi-halkola** [6pac/SlickGrid#215]
Commit 9f2c8564b230572e0c99956704672b6245c52b0d is breaking atleast grid.getFooterRowColumn. Most likely also breaking getHeaderRowColumn and getHeaderColumn.

Commit seems to add support for fetching the column elements by column idx but at the same time breaking backwards compatibility by breaking the functionality of fetching the columns with column id as previously intended.

**Comment by muthukumarse** [comment]
@taavi-halkola 
getHeaderColumn - should be 
function getHeaderColumn(columnIdOrIdx) {
      var idx = (typeof columnIdOrIdx === "number" ? columnIdOrIdx : getColumnIndex(columnIdOrIdx));
      var $rtn = $headers.children().eq(idx);
      return $rtn && $rtn[0];
    }

it fixed in #214 

getFooterRowColumn - i tested this function with example-footer-totals.html, its working fine as expected.

getHeaderRowColumn - can you advise me where its been used. I can't find.

**Comment by 6pac** [comment]
Good catch. I have fixed it and issued a commit, will pull #214 once the series of tweaks to it is complete.
I cut and pasted the ```getColumnIndex``` line from another project, hence the error. Some testing would have been good too ;-)

**Comment by muthukumarse** [comment]
Sure 🤙
