### ISSUE TITLE
version 2.3.16 breaks fixed header filters

### ISSUE THREAD

**Issue by ghiscoding** [6pac/SlickGrid#216]
I had to revert back to version `2.3.15` since all my Filters were gone after `2.3.16` update. I will investigate, not sure why yet.

**Comment by ghiscoding** [comment]
Found it, it's caused by `getHeaderRowColumn()`, which I think was fixed in #215 
@6pac can you confirm this was fixed? If so I will wait for the next version.

Thanks

**Comment by taavi-halkola** [comment]
@ghiscoding While waiting for the fix use the column idx instead of the id when calling `grid.getHeaderRowColumn()`.

Quick example assuming you dont want to use fixed idx's: `grid.getHeaderRowColumn(grid.getColumnIndex('column_id'))`

**Comment by 6pac** [comment]
Is fixed now, we are at 2.3.17

I accidentally released 2.4.0 and then removed it, looks like it may be hanging around in NPM.
