### ISSUE TITLE
feature: multilevel header

### ISSUE THREAD

**Issue by vladojr** [6pac/SlickGrid#217]
Hello,

is it possible to add multilevel headers?

![image](https://user-images.githubusercontent.com/18343587/37231337-10fe7884-23eb-11e8-8474-6304ac34cfb2.png)

Thank you

**Comment by ghiscoding** [comment]
Have you looked at all the demos? I think you mean this [Column Group](http://6pac.github.io/SlickGrid/examples/example-column-group.html)

**Comment by vladojr** [comment]
Thank you, yes I saw the demos but obviously I missed this one.
