### ISSUE TITLE
Cellexternalcopymanager plugin and cell editing problem

### ISSUE THREAD

**Issue by taavi-halkola** [6pac/SlickGrid#218]
Not sure if this is a bug or an inconvenience but i doubt it's the expected behavior. Nonetheless it's slowing editing down considerably. SlickGrid version 2.4.0(Not sure why the tags are at 2.3.17? I'm using npm).

When using the slick.cellexternalcopymanager.js plugin and trying to initiate a cell edit with a cell doubleclick, the editor created input is not getting focus. An extra click on the input is required. Initiating the cell edit with enter keypress does not have this problem.

This is propably caused by lines 59-64 and the `_grid.focus();` specifically. Seems like the `selectionModel.onSelectedRangesChanged` event is being fired after the editor init causing the input to lose focus. 

Question:
Why is the` selectionModel.onSelectedRangesChanged` event fired when clicking on a cell without an actual cell or range change? For example clicking(or double clicking to edit) the same cell which is currently active/selected. That might even be the root cause of all this.

Here are the specific lines from the slick.cellexternalcopymanager.js plugin:
```
// we give focus on the grid when a selection is done on it.
// without this, if the user selects a range of cell without giving focus on a particular cell, the grid doesn't get the focus and key stroke handles (ctrl+c) don't work

cellSelectionModel.onSelectedRangesChanged.subscribe(function(e, args){
     _grid.focus();
});
```

Ps. The problem can be seen in this example http://6pac.github.io/SlickGrid/examples/example-excel-compatible-spreadsheet.html

**Comment by 6pac** [comment]
Have just pushed a change to fix this. Hasn't made it into a release yet though.
