### ISSUE TITLE
Can we create bower package

### ISSUE THREAD

**Issue by cajoy** [6pac/SlickGrid#22]
Would be good to have bower.json in repo for easier import

**Comment by 6pac** [comment]
It's a good idea but I'm not familiar with bower packaging. I had a look and there are quite a few of the variant slickgrid repos on bower already. Some of them just have a homepage defined, no install files.

I'm not sure how detailed the 'main' section should be. For example, do we list the main grid files and css, plus all the controls and plugins, AND all the slick-specific image files ?

**Comment by zachgibb** [comment]
@cajoy You should be able to pull in the necessary files to your project even before a bower package gets made officially.

In your `bower.json` you can specify non-bower urls you want to pull in, and then in `overrides` you could specify the specific files needed for your project. For example, when using the dependencies in the [basic example](https://github.com/6pac/SlickGrid/blob/master/examples/example1-simple.html), your `bower.json` might look like this:
```json
// bower.json
"dependencies": {
  "slickgrid": "https://github.com/6pac/SlickGrid.git"
},
"overrides": {
  "slickgrid": {
    "main": [
      "./slick.grid.css",
      "./css/smoothness/jquery-ui-1.11.3.custom.css",
      "./lib/jquery-1.11.2.min.js",
      "./lib/jquery.event.drag-2.2.js",
      "./slick.core.js",
      "./slick.grid.js"
    ]
  }
}
```

Though instead of including `./lib/jquery-1.11.2.min.js` as an override for `slickgrid` you would probably just include that as a dependency in your own project.

**Comment by ajdalshov** [comment]
Please take some time to get this fork on Bower as this should be the new defacto Bower package for SlickGrid. :)

**Comment by 6pac** [comment]
anyone an expert on Bower who can make up a file I can pull? I've had a look and not sure how to deal with the dependencies. Just don't have a lot of time to learn Yet Another New Thing i'm not going to use myself.

**Comment by Custodia** [comment]
To register as a bower component you need to use [semver](http://semver.org/) git tags.

Not an "expert" on bower but I might take a crack at making a bower file.

**Comment by 6pac** [comment]
We're on semver anyway. 
Any bower file attempts would be appreciated, we can workshop it perhaps. 
I can make educated guesses, but being primarily an MS Visual Studio developer the tools do it all for me, I think NuGet is the builtin package manager, and I have no personal need for bower, so I'm not familiar with it.

**Comment by henkli** [comment]
Disclaimer: I don't know if this correct.

Here's one version, can somebody test it? 
https://github.com/gbelmm/SlickGrid/blob/master/bower.json

**Comment by Custodia** [comment]
@henkli that's just the default template and it's pointing to a wrong repository

**Comment by 6pac** [comment]
Thanks everyone for your input. I have read both the suggestions, and also checked out some tutes, and installed bower on my OSX drive. I'll try the suggestions in action and fine tune them.

**Comment by schhunchha** [comment]
Any update?

**Comment by ghiscoding** [comment]
Bower is now deprecated as per an open issue on their [Github](https://github.com/bower/bower/issues/2298), please read the last comment at the end of the discussion. 

So the current issue and open Bower PR #34 should be closed.

Here's the quote from the Bower issue
> @capaj Good idea, I've included the notice in both readme and npm deprecate
>
> I think I'll close this issue now. Please keep in mind that even I don't have much free time, I'll maintain and keep Bower alive, so all current projects that use Bower, will continue to work.
>
> Not to say I'd block anyone if she/he wanted to to take some extra responsibility for Bower's future (i.e. maintaining/developing it). If you feel like so, please e-mail me at: sheerun@sher.pl
>
> If you'd like to discuss something else publicly, please open another issue, this one is a mess.

Also an article on the Bower Blog - [How to migrate away from Bower](https://bower.io/blog/2017/how-to-migrate-away-from-bower/)

**Comment by ghiscoding** [comment]
Closing since as it was in previous post, Bower is deprecated (but still maintained, for now)
