### ISSUE TITLE
[enhancement] Can we expose the "grid" object inside the "groupTotalsFormatter"

### ISSUE THREAD

**Issue by ghiscoding** [6pac/SlickGrid#222]
For i18n (internationalization) purposes and possibly other reasons. It would be great to have the Grid object exposed to the `groupTotalsFormatter` as a 3rd argument on this [line](https://github.com/6pac/SlickGrid/blob/master/slick.groupitemmetadataprovider.js#L66) and from the grid object, we also have access to the grid options which is great.

I'm not sure if the `groupTotalsFormatter` is defined in other line of codes. I can review that later

**Comment by 6pac** [comment]
This is a regular fomatter, I think. The default grid formatter signature is

    function defaultFormatter(row, cell, value, columnDef, dataContext, grid) {

so I think in ```slick.groupitemmetadataprovider.js``` we should change 

    function defaultTotalsCellFormatter(row, cell, value, columnDef, item) {

    function defaultGroupCellFormatter(row, cell, value, columnDef, item) {

to

    function defaultTotalsCellFormatter(row, cell, value, columnDef, item, grid) {

    function defaultGroupCellFormatter(row, cell, value, columnDef, item, grid) {

**Comment by ghiscoding** [comment]
Right good point, I didn't think about that part. However, we still won't have the grid exposed if we just change those lines since the call within is still with only 2 arguments

```javascript
function defaultTotalsCellFormatter(row, cell, value, columnDef, item) {
      return (columnDef.groupTotalsFormatter && columnDef.groupTotalsFormatter(item, columnDef)) || "";
}
```

So in the [grouping example](http://6pac.github.io/SlickGrid/examples/example-grouping.html), it is defining the column definitions with these 2 arguments
```javascript
var columns = [
  {id: "duration", name: "Duration", field: "duration", groupTotalsFormatter: sumTotalsFormatter},
  ...
];

function sumTotalsFormatter(totals, columnDef) {
  var val = totals.sum && totals.sum[columnDef.field];
  if (val != null) {
    return "total: " + ((Math.round(parseFloat(val)*100)/100));
  }
  return "";
}
```

If we had the 6 arguments (just like regular Formatters), then what do you suggest for the `groupTotalsFormatter` call? And on top of that, it has `columnDef` and `item` inversed compare to a regular formatter.

How would you like to proceed?

**Comment by 6pac** [comment]
Good points. I think just add it as the third param, we probably shouldn't overthink!

I suppose technically we don't need to add the grid to the formatter call, as it's a closure. But I added grid objects to everything a while back, so that if there were multiple grids on a page, some objects could be used by multiple grids rather than having to re-declare a new one for each grid.  
Nice to keep it standard.

Happy if you do all this.

**Comment by ghiscoding** [comment]
The good thing about the grid object is that it has everything with a function call away. In my case I pass an i18n service to the grid options and these options I can get from the grid object.
```javascript
let options = grid.getOptions();
let i18nService = options.i18n;
```

I'll create a PR in a few then.
