### ISSUE TITLE
getItemMetaData issues

### ISSUE THREAD

**Issue by GordonJones** [6pac/SlickGrid#224]
Hello. First I want to say what a fine product this is. I've had a trawl looking at lots of tree/grid presentation tools, and this seems by far the best for my purposes.

I am using getItemMetaData to set classes on my rows, and I have encountered 2 problems.
1. The function is called many times for each row, which seems a little excessive.
2. The last call is for a row that does not exist.

In my case I have 5 columns, and getItemMetaData is called 6 times for each row - once when rendering the row, and once for each column. The calls for each column seem to me redundant, since there is no indication in the call parameters as to which column is being rendered. All the column specific meta data can be returned in the first call.

The call for a row index that doesn't exist and is off the end also seems redundant. I cannot work out if this call is for a "special" end row, or is a mistake?

Below is my function, followed by the console log trace.

`  dataView.getItemMetadata = function(rowIndex) {
    var item = dataView.getItem(rowIndex);
    console.log(item, rowIndex);
    if (item) {
      if (item.isMaster) {
        return {cssClasses: item.type}
      } else {
        return {cssClasses: item.type + " " + "slave"}
      }
    }
  };
`

[Log] No message (2) (index.html, line 132)
{title: "Game of Thrones", id: "proj1", type: "project", isMaster: true, expanded: true, …}
0
[Log] No message (2) (index.html, line 132)
{title: "Game of Thrones", id: "proj1", type: "project", isMaster: true, expanded: true, …}
0
[Log] No message (2) (index.html, line 132)
{title: "Game of Thrones", id: "proj1", type: "project", isMaster: true, expanded: true, …}
0
[Log] No message (2) (index.html, line 132)
{title: "Game of Thrones", id: "proj1", type: "project", isMaster: true, expanded: true, …}
0
[Log] No message (2) (index.html, line 132)
{title: "Game of Thrones", id: "proj1", type: "project", isMaster: true, expanded: true, …}
0
[Log] No message (2) (index.html, line 132)
{title: "Game of Thrones", id: "proj1", type: "project", isMaster: true, expanded: true, …}
0
............
[Log] No message (2) (index.html, line 132)
{title: "scene 1.1", id: "15221796807396", type: "scene", isMaster: false, expanded: true, …}
21
[Log] No message (2) (index.html, line 132)
{title: "scene 1.1", id: "15221796807396", type: "scene", isMaster: false, expanded: true, …}
21
[Log] No message (2) (index.html, line 132)
{title: "scene 1.1", id: "15221796807396", type: "scene", isMaster: false, expanded: true, …}
21
[Log] No message (2) (index.html, line 132)
{title: "scene 1.1", id: "15221796807396", type: "scene", isMaster: false, expanded: true, …}
21
[Log] No message (2) (index.html, line 132)
{title: "scene 1.1", id: "15221796807396", type: "scene", isMaster: false, expanded: true, …}
21
[Log] No message (2) (index.html, line 132)
{title: "scene 1.1", id: "15221796807396", type: "scene", isMaster: false, expanded: true, …}
21
[Log] No message (2) (index.html, line 132)
undefined
22

**Comment by 6pac** [comment]
Hi Gordon,
I've had a look and it appears it's by design. I note the first line of the ```getFormatter``` function is 

    function getFormatter(row, column) {
      var rowMetadata = data.getItemMetadata && data.getItemMetadata(row);

so that's going to call ```getItemMetadata```  once for each column with a formatter.
I think the idea is that the grid is rendering only a few rows, so it's OK to be not quite so efficient. In general, the columns are set up to act independently (there's no tight link to the row), so that's why the row value is not read only once. You could notionally set us some kind of cache, but it's probably overkill for the reason mentioned above.

The missing row is likely the 'add row' row, which is kind of a 'ghost row' that hangs around waiting to be used. Just make sure the metadata function can return a null to that without throwing an error.
