### ISSUE TITLE
Why SlickGrid need unique id ?

### ISSUE THREAD

**Issue by nzhtrtlc** [6pac/SlickGrid#226]
Hi, i tested some features with mock data.
Now i am trying to implement real data comes from api.
But in my json object there is no any **id** property. 
SlickGrid says *Each data element must implement a unique 'id' property*

So should i loop in my data array and add **id** property to each object ?

**Comment by 6pac** [comment]
This is just the way the DataView works.  It's not particularly sensible - I have my own private version that doesn't have that requirement.  
However the easiest way forward is definitely just to add an ID column. If you have an int PK in your result set, you can also use that value.

**Comment by nzhtrtlc** [comment]
Here is my solution. I am not sure if it is okay to use like this.
`data = data.map((d, i) => {
         return { id: i, ...d }
      });
`

By the way, is it possible to sorting grouped columns ?
I couldn't find any topic about this.

**Comment by 6pac** [comment]
Usually a loop is used:

    for (var i=0, j=data.length; i < j; i++) {
        data.id = i;
    }

Check out the [examples](https://github.com/6pac/SlickGrid/wiki/Examples), under the 'data-centric' and  'grouping' headings

**Comment by nzhtrtlc** [comment]
Okay thank you. 
We can close this one.
