### ISSUE TITLE
Row detailview handleScroll error with no items in grid

### ISSUE THREAD

**Issue by SatanEnglish** [6pac/SlickGrid#228]
If the rowdetailview.js plugin is used and there is no items in the view.

Then there is a js exception.

            if (topMostItem._parent == undefined)
            {
            }
            
            if(bottomMostItem._parent !== undefined)
            {               
            }

needs to be changed to 

            if (topMostItem && topMostItem._parent == undefined)
            {
            }
            
            if(bottomMostItem && bottomMostItem._parent !== undefined)
            {               
            }

**Comment by SatanEnglish** [comment]
I'll get round to this at some stage when I find some time just wanted to log it

**Comment by 6pac** [comment]
updated and pushed
