### ISSUE TITLE
IntegerEditor validation

### ISSUE THREAD

**Issue by simonzack** [6pac/SlickGrid#23]
Can IntegerEditor have a validator option as well, similar to TextEditor? Use cases including checking whether the integer is positive, negative, above a value, etc. Currently I'm using TextEditor and casting the results myself to an int which isn't really convenient.

btw, thanks for creating and maintaining this fork! Perhaps if slickgrid totally dies you could call it slickgrid 2 or something.

**Comment by zoechi** [comment]
Just provide your custom editor. They are not comlicated. Copy an existing one, customize it and pass it to your column config.

**Comment by simonzack** [comment]
It's indeed not complicated, but that's what validator is for, and it would be nice to have this for integers as well.

**Comment by simonzack** [comment]
@zoechi Even easier to do a PR :)

**Comment by zoechi** [comment]
Sure that's the best option :)
