### ISSUE TITLE
Filter issue

### ISSUE THREAD

**Issue by boobalganesan** [6pac/SlickGrid#233]
Thanks for this amazing tool! I've been extensively using this tool to connect to Oracle DB and use the data for multi user parallel editing using websockets. 

When I try to filter the rows and edit a row (2nd row for example), it actually edits the second row from the data view and not the row I filtered. Not sure if it's a real issue either. I can share my code if necessary.

Thanks,
B

**Comment by boobalganesan** [comment]
[issue code.txt](https://github.com/6pac/SlickGrid/files/1888497/issue.code.txt)


I've attached my entire code incase something else is breaking it.


Thanks!

**Comment by SatanEnglish** [comment]
@boobalganesan 
Have you tried using the Idx instead?
e.g. .dataView().getIdxById(curRowData.id);

**Comment by boobalganesan** [comment]
@SatanEnglish Will test it and update. Thank you for getting back on this!

**Comment by SatanEnglish** [comment]
@boobalganesan
Did it work?
If so you should close this issue. 
THX

**Comment by ghiscoding** [comment]
closing since no feedback were provided, so we'll assume that it's ok
