### ISSUE TITLE
Tree item with children

### ISSUE THREAD

**Issue by RodolfoMota** [6pac/SlickGrid#237]
Its possible create an item with children? I was looking the examples and I didn't see anything like that.

**Comment by 6pac** [comment]
Is this any good: http://6pac.github.io/SlickGrid/examples/example5-collapsing.html ?

**Comment by krozs** [comment]
I saw that, but I can insert an item with children?

**Comment by 6pac** [comment]
I believe so. The essential element of this example is:

    d["id"] = "id_" + i;
    d["indent"] = indent;
    d["parent"] = parent;

If you insert items with the appropriate parent into the data.  Refresh the grid, and you'll get child elements. You'll have to do a little bit of work to get all this operating smoothly. See [the SlickGrid Manifesto](https://github.com/6pac/SlickGrid/wiki/The-SlickGrid-Manifesto)
