### ISSUE TITLE
Copy paste not working

### ISSUE THREAD

**Issue by dcalde** [6pac/SlickGrid#242]
I haven't downloaded the code and tried locally with the latest version yet, but the copy paste examples http://6pac.github.com/SlickGrid/examples/example-spreadsheet.html are not working for me (Chrome 66 & Edge 42).

**Comment by ghiscoding** [comment]
The provided example does not work with Copy and Paste even after reverting (by hand) my code. Was that example ever working with Copy Paste? I mean I went and manually added some data in some of the cells (in the grid) and did a Copy and Pasted in Excel and nothing happens. 

> `example-spreadsheet` is broken in several ways

in what ways?

> but interestingly `example-excel-compatible-spreadsheet` appears to still work.

I have the latest SlickGrid version in my Angular-Slickgrid and the Copy Paste still works correctly. 
I think the `example-spreadsheet` itself is missing something for the Copy and Paste to work

**Comment by 6pac** [comment]
Sorry, should have given more info. ```example-spreadsheet``` is a single-cell copy and paste. I found it works with the reverted version, but not with the new version.

I found the copy paste was broken, and also I was getting the range designators (eg. A3:B6) pasted into cells. That may be a separate issue, but it didn't happen in the reverted version.

**Comment by ghiscoding** [comment]
My PR only has 2 lines of code, it should be easy enough to find which line. But again, if I revert my code manually I don't see it working still

**Comment by 6pac** [comment]
Might add that to the example documentation. I'm not saying this can be fixed - it might be possible that the two use cases are mutually incompatible. If reverting it would only be a case of 'the devil you know'. We'd need to document that to get the editors working, a patch was necessary. Ugly, but until the time or $$ show up to fix the active cell logic, it may be the only way.

Unless, of course, you can fix this. I just not 100% sure this is going to be the only thing broken by that change, though. As I said, I spent about two hours looking at #68 originally, and just found it got more complex the more I looked into it.

**Comment by ghiscoding** [comment]
Well I need the PR #68 to get Row Selection and Editors to work together, without it I cannot work. However, if you want a quick and dirty way to fix this, I suggest to add a grid option flag that we could use enable that 4th argument `suppressActiveCellChangedEvent` that I added to the `setActiveCellInternal` function. You could have that flag disable by default and I would enable it to get my code working with Row Selection and Editor.

**Comment by ghiscoding** [comment]
I think we can close it now since we addressed the issue in latest PR
