### ISSUE TITLE
Persisting column order, visibility and sort direction

### ISSUE THREAD

**Issue by psinghsp** [6pac/SlickGrid#249]
Hi

Is there a way to get from the grid the current column order, column visibility and sort direction and then apply the same config to the grid when the page is refreshed? I could not see an example of this on the examples page.

**Comment by ghiscoding** [comment]
Yes, you need to keep the columns somewhere (like Local Storage) and then use `setColumns()` when you come back on the same page. 

There's a Plugin that was done in another repo (GerHobbelt/SlickGrid), you can take a look at his [html](https://github.com/GerHobbelt/SlickGrid/blob/k0stya-rowspan/examples/example-0070-plugin-state.html) and [plugin](https://github.com/GerHobbelt/SlickGrid/blob/k0stya-rowspan/plugins/slick.state.js)

The plugin uses `onColumnsResized` and `onColumnsReordered` to keep values when they are resized and such, then restores it back with `setSortColumns()`

**Comment by psinghsp** [comment]
Thanks for the prompt response. I will try the plugin.
