### ISSUE TITLE
How to copy cell value from context menu ?

### ISSUE THREAD

**Issue by nzhtrtlc** [6pac/SlickGrid#257]
Hi, i want to copy cell value from context menu. I can already copy the cell value using "cmd + c".
I did look at this example http://6pac.github.io/SlickGrid/examples/example7-events.html
In this example you take the row data by this code;

```
var row = $(this).data("row"); // HOW THIS LINE EVEN WORKS ?
data[row].priority = $(e.target).attr("data");
```

Example source code: https://github.com/6pac/SlickGrid/blob/master/examples/example7-events.html

But there is no data-row attribute in context html element. I don't understand how to i get row data.

![screen shot 2018-06-28 at 14 38 08](https://user-images.githubusercontent.com/17534778/42032085-169005d6-7ae1-11e8-9556-025e62d7824c.png)

**Comment by 6pac** [comment]
The row id is saved when the context menu is activated:

    grid.onContextMenu.subscribe(function (e) {
      e.preventDefault();
      var cell = grid.getCellFromEvent(e);
      $("#contextMenu")
          .data("row", cell.row)
          .css("top", e.pageY)
          .css("left", e.pageX)
          .show();

      $("body").one("click", function () {
        $("#contextMenu").hide();
      });
    });

to copy the value, you'd use:

var row = $(this).data("row"); 
alert(data[row].columnName);

You'd be better off asking this on StackOverflow.

**Comment by nzhtrtlc** [comment]
@6pac By the way, i would be appreciated if you can tell me how to copy to clipboard that value ?
Thanks in advance.

**Comment by 6pac** [comment]
Unfortunately, that is not an easy question to answer. Because it's a security risk, browsers make it very difficult.  Using ctrl-c or right click 'copy' is easy, but programmatic is hard.  
Try this:
https://stackoverflow.com/questions/23211018/copy-to-clipboard-with-jquery-js-in-chrome

The situation may have improved more recently.

**Comment by nzhtrtlc** [comment]
@6pac Actually i want to implement right click 'copy' for context menu. Just like screenshot i shared in first post.
Actually i wrote some js code to copy value but i can not copy the selected range. Can you help me on this?
Here is my code for the single cell not for selection range.

> 
    contextMenuFunctions = {
        downloadCSV: () => {
            this.exportCSV()
        },
        copy: () => {
            const rowIndex = $('#contextMenu').data('row');
            const cellIndex = $('#contextMenu').data('cell');
            const { accessKey } = this.props.columns[cellIndex];
            let value = get(this.props.data[rowIndex], accessKey);
            this.copyToClipboard(value);
            $('.slick-cell.selected').addClass('copied').delay(5000).removeClass('copied');
        }
    }

>
    <ContextMenu>
         <div className="context">
                        <div className="inner-item" onClick={this.contextMenuFunctions.downloadCSV}>
                            <Download/> Download CSV
                        </div>
                        <div className="inner-item" onClick={this.contextMenuFunctions.copy}>
                            Copy
                        </div>
                    </div>
    </ContextMenu>

BTW i can use ctrl-c shortcut with this code

> 
    let cellExternalCopyManager = new Slick.CellExternalCopyManager({
            clipboardCommandHandler: function (editCommand) {
                undoRedoBuffer.queueAndExecuteCommand.call(undoRedoBuffer, editCommand);
            },
            readOnlyMode: true,
            includeHeaderWhenCopying: true
        });

**Comment by 6pac** [comment]
You'll have to take a different approach than the above, since the row and column are stored on right click. You'll need to get the selected range with ```getSelectedRows()``` (returns an array of row indexes). 

Really, put a question on StackOverflow. You'll get much better help. GitHub is for bugs and enhancements, not for usage issues.

**Comment by ghiscoding** [comment]
In the new [Context Menu](https://6pac.github.io/SlickGrid/examples/example-plugin-contextmenu.html) Plugin I created, in that example, there's a demo with a Cell Copy [here](https://github.com/6pac/SlickGrid/blob/master/examples/example-plugin-contextmenu.html#L207). 

So I think we can close this issue
