### ISSUE TITLE
How to render clickable links in grid cells

### ISSUE THREAD

**Issue by tedstrauss** [6pac/SlickGrid#259]
I'd like to render clickable links in grid cells.
Is there a recommended way to do this?
I'm using slickgrid as part of CKAN. Currently when I put a URL into a cell it appears as a link but clicking it doesn't do anything. 
Any tips are appreciated.

**Comment by tedstrauss** [comment]
Found this reference: http://sbkolate.blogspot.com/2015/12/slick-grid-link-formater.html

**Comment by 6pac** [comment]
You need to create a formatter and assign that to the columns. The formatters live in ```slick.formatters.js```.
eg. (note this has no HTML escaping and assumes the value is a valid URL)

    function LinkFormatter(row, cell, value, columnDef, dataContext) {
      return '<a href="' + value  + '">' + value + '</a>';
    }

then add the formatter to the slick namespace at the top of the file, like

    $.extend(true, window, {
      "Slick": {
        "Formatters": {
          "PercentComplete": PercentCompleteFormatter,
          ... 
          "Link": LinkFormatter
        }
      }
    });

Now you can use the formatter in any column:

     {id: "sample_id", name: "Sample Id", field: "sampleid", formatter: Slick.Formatters.Link },

See the [formatters example](http://6pac.github.io/SlickGrid/examples/example2-formatters.html) for more info.
