### ISSUE TITLE
Is there an example of using slick grid with ReactJS?

### ISSUE THREAD

**Issue by DemGiran** [6pac/SlickGrid#266]
Thank you for reading

**Comment by ghiscoding** [comment]
If you do a search, there was this closed [issue](https://github.com/6pac/SlickGrid/issues/80) talking about React

**Comment by nzhtrtlc** [comment]
@DemGiran i used it in my React project. Actually, i do not recommend to use SlickGrid in React.JS if you don't have to use it. You can check react-table for as a pure react component.
SlickGrid has many issues and problems when you want to use it in React.JS
However, if you gonna do that just simply add slickgrid as npm package in your project. And import the all necessary files (jquery, slickgrid core js files and plugins) in your main js file.
Then create a react class and render SlickGrid then use it everywhere like;

<SlickGrid 
columns={this.state.columns} 
data={this.state.data}
gridOptions={{ forceFitColumns: true }}
/>

**Comment by ghiscoding** [comment]
I just released an official port to React, you can visit [Slickgrid-React](https://github.com/ghiscoding/slickgrid-react) for more info and a fully working [Live Demo](https://ghiscoding.github.io/slickgrid-react/) 🚀 

I think we can close this issue
