### ISSUE TITLE
Calculations around viewportH seem to be inconsistent

### ISSUE THREAD

**Issue by budden** [6pac/SlickGrid#269]
At some places, horizontal scroll bar is taken into account like this: 
```
(viewportHasHScroll ? scrollbarDimensions.height : 0)
```
In other places it is not. Maybe this is a feature, but more looks like wrong coding.

**Comment by ghiscoding** [comment]
closing since it's not very clear what the issue was, feel free to contribute any Pull Request. Note that the source code was recently migrated to TypeScript
