### ISSUE TITLE
Ability to set the inclusion of header cells to be copied at runtime

### ISSUE THREAD

**Issue by SabreWolf** [6pac/SlickGrid#272]
For the plugin slick.cellexternalcopymanager located at https://github.com/6pac/6pac.github.io/blob/master/SlickGrid/plugins/slick.cellexternalcopymanager.js please could you create and expose a function to be able to turn on and off the inclusion of the header cells at runtime when copying and pasting. I have included a suggestion for the last few lines of this file below.

```
    **function setIncludeHeaderWhenCopying(includeHeaderWhenCopying) {
        _options.includeHeaderWhenCopying = includeHeaderWhenCopying;
	}**

    $.extend(this, {
      "init": init,
      "destroy": destroy,
      "clearCopySelection": clearCopySelection,
      "handleKeyDown":handleKeyDown,
      **"setIncludeHeaderWhenCopying":setIncludeHeaderWhenCopying,**
      
      "onCopyCells": new Slick.Event(),
      "onCopyCancelled": new Slick.Event(),
      "onPasteCells": new Slick.Event()
    });
  }
})(jQuery);
```

**Comment by ghiscoding** [comment]
this seems to be already part of the code, so it's probably safe to close

https://github.com/6pac/6pac.github.io/blob/3587b3f8818ed8f965177ee88c43e8fe873d5b05/SlickGrid/plugins/slick.cellexternalcopymanager.js#L454-L471
