### ISSUE TITLE
cellexternalcopymanager causes auto scrolling to the top when copying to clipboard

### ISSUE THREAD

**Issue by SabreWolf** [6pac/SlickGrid#273]
Due to the limitations in browsers not being able to copy directly to the clipboard, the external copy manager uses a workaround which causes unusual scrolling events on copy.

Here are the steps to reproduce the issue.

1) Navigate to this example http://6pac.github.io/SlickGrid/examples/example-excel-compatible-spreadsheet.html
2) Reduce the height of your browser window so that when the browser is scrolled to the bottom, only the second table is showing
3) Activate one of the cells in the second grid and press CTRL+C

You should see the browser auto-scroll to the top.

**Comment by 6pac** [comment]
I cannot repro this in chrome. What browser are you using?

**Comment by ghiscoding** [comment]
this is a rather old issue and I cannot replicate the issue when trying the example in Firefox v113 so it's probably safe to close
