### ISSUE TITLE
Adding a dataItemColumnHeaderExtractor just like dataItemColumnValueExtractor to cellexternalcopymanager

### ISSUE THREAD

**Issue by SabreWolf** [6pac/SlickGrid#274]
In the cellexternalcopymanager, there is a plugin option callback dataItemColumnValueExtractor that allows a client to determine the data to be copied into the clipboard. Please can you also add an equivalent dataItemColumnHeaderExtractor.

Right now, the file https://github.com/6pac/6pac.github.io/blob/master/SlickGrid/plugins/slick.cellexternalcopymanager.js simply takes the name field columns[j].name. See line 351.

**Comment by 6pac** [comment]
thanks for this, too busy to deal with it right now but will get to it sometime.

**Comment by 6pac** [comment]
Done

**Comment by SabreWolf** [comment]
Many thanks, much appreciated.
