### ISSUE TITLE
Passing the user event to the cell editor

### ISSUE THREAD

**Issue by SabreWolf** [6pac/SlickGrid#276]
There are times when the cell editor should initialize differently depending on how the cell editor request came about. Whether that be a certain key press or mouse click. (Excel does this)

Please can you include the user event object as a field in the args object that gets passed to the constructor of the cell editor. I am happy to provide a code patch if you think it would be helpful.

**Comment by 6pac** [comment]
Email me the changed files if you like, and I'm happy to patch the hooks in to the repo. What I look for when considering changes is the general usefulness across a range of plugins or use cases, and it sounds like this fits the bill. You may as well send the editor as well, it would be a useful example of how to use this new hook.

**Comment by 6pac** [comment]
I've added these patches and pushed to the repo. Will do a release (NPM etc) soon. Sorry about the really long delay!

**Comment by SabreWolf** [comment]
Many thanks, much appreciated.
