### ISSUE TITLE
Undocumented dependency on jquery-ui?

### ISSUE THREAD

**Issue by Yoten** [6pac/SlickGrid#277]
Per the wiki, jQueryUI is only required when using column reordering. However, in slick.groupitemmetadataprovider.js line 115, there's a reference to "$.ui.keyCode.SPACE" as part of an onKeyDown event handler that I don't think is explicitly linked to column reordering. This will throw an error if you don't have jQueryUI's keyCode part.

If that file isn't supposed to be dependent upon jQueryUI, it might be worth adding SPACE to the local keyCodes defined in slick.core.js.

**Comment by 6pac** [comment]
Done. Thanks for that catch. Will do new release soon.
