### ISSUE TITLE
Show totals when using a dataView grouping

### ISSUE THREAD

**Issue by mpGitHub** [6pac/SlickGrid#28]
I don't see a feature in this version of slickgrid for a fixed overall totals footer.  Is this something that will be explored in the future?

I looked into showing totals via a dataProvider, but I also need to use a dataView technique for grouping and etc.  For some reason this isn't working for me.  Does someone know the proper technique to get something like this working?

Eg. this is for using a dataProvider for totals:

<pre>
      var dataProvider = new TotalsDataProvider(data, columns);
      grid = new Slick.Grid("#myGrid", dataProvider, columns, options);
</pre>

And this is used for grouping and etc:

<pre>
      var groupItemMetadataProvider = new Slick.Data.GroupItemMetadataProvider(options);
      dataView = new Slick.Data.DataView({
        groupItemMetadataProvider: groupItemMetadataProvider,
        inlineFilters: true
      });

    grid = new Slick.Grid("#myGrid", dataView, columns, options);
</pre>

Is it possible to use both at the same time???

Thanks!

**Comment by 6pac** [comment]
Good question! Looking into this.

**Comment by mpGitHub** [comment]
Y - I thought this should be a simple endeavor, but it doesn't seem to work as I expect?  

A colleague of mine added the ability to put a fixed footer at bottom of the grid in the original slickgrid.  I went ahead and merged his changes to this version and it seems to work in this current version.  I had to change quite a few places in these files: 
<pre>
slick.grid.js
slick.groupitemmetadataprovider.js
slick.dataview.js
</pre>
His approach was to basically mimic how the header works and calculate the totals and drop them in.  It works pretty well, but I don't want to deviate too far from your version.  

Let me know what comes of your digging into this.  If you want I can send you the merged changes I used for this and you can see what you think.

Cheers!

**Comment by 6pac** [comment]
yeah, I was thinking the same way. There have been requests for this, but I've held off, viewing it as excessive customisation.
Perhaps it's time.

**Comment by 6pac** [comment]
if you can link to a pull request or list of changes, that would be good. even the old ones before I added the footer code would do.

**Comment by 6pac** [comment]
How's this: http://6pac.github.io/SlickGrid/examples/example-footer-totals.html
