### ISSUE TITLE
Ie8 click the button in the table and report the following error in line 1164. How to solve it

### ISSUE THREAD

**Issue by yuanName** [6pac/SlickGrid#290]
![2wqyo zr8 1wg v_6 84 e](https://user-images.githubusercontent.com/44542104/48928788-4aa1ae00-ef1d-11e8-82bb-349429e8a8d0.png)
![c0p rnxvlmblih sdjfct](https://user-images.githubusercontent.com/44542104/48928790-4c6b7180-ef1d-11e8-8a76-354125739b77.png)

**Comment by andreasmueller92** [comment]
You may not want to hear this, but

> Effective January 12, 2016, Internet Explorer 8 is no longer supported on any client or server version of Windows.

Plus, you should provide a translation of this error. Just pointing at the code does not explain which error occurs.

**Comment by 6pac** [comment]
Yeah, I did have a look, but there is a IE branch in the code, so it should work in theory. Since it isn't working, an error message in English would be handy. The chinese characters are too small for Google Translate.
