### ISSUE TITLE
Mouse movement to each row of the table, the corresponding row background color changes, how to deal with

### ISSUE THREAD

**Issue by yuanName** [6pac/SlickGrid#292]
![image](https://user-images.githubusercontent.com/44542104/49065107-fb7ab680-f257-11e8-9e53-8f78f49bfaed.png)

**Comment by 6pac** [comment]
Hi @yuanName, perhaps this would be better asked on StackOverflow, the issues on GitHub are for bug fixes and design issues, not for use case customisations.
