### ISSUE TITLE
Rows shifting during rowcount updates

### ISSUE THREAD

**Issue by anthonydresser** [6pac/SlickGrid#297]
When dealing with large row counts and when updating the row count, slight rows shifts occur even when the user is not scrolling.
![jumpingrows](https://user-images.githubusercontent.com/4324725/49674496-10f59a80-fa27-11e8-8982-cbe81523e079.gif)

repro: https://jsfiddle.net/r47kqpc9/16/

I've tracked it down to when the row top is calculated https://github.com/6pac/SlickGrid/blob/master/slick.grid.js#L1597 the `offset` value is slightly different after each row count update. That is being caused by this `cj` value slightly changing each time https://github.com/6pac/SlickGrid/blob/master/slick.grid.js#L2027 since it is calculated based on the exact row count (not some modulo of the value).

It seems this cj value has something to do with dealing with the `maxsupportedcss` work around.

Is there some work around to this? Or some way to reduce the visual impact this has?

**Comment by anthonydresser** [comment]
The change tends to be about 1000, in my case, but changes based on the number of rows. Here are some examples I have pulled, (sequential row update calls). (I'm dealing with very large row counts.
![image](https://user-images.githubusercontent.com/4324725/49676141-68970480-fa2d-11e8-9aaa-cae9c4656944.png)
![image](https://user-images.githubusercontent.com/4324725/49676144-70ef3f80-fa2d-11e8-9bfd-059c3ccac8f6.png)
![image](https://user-images.githubusercontent.com/4324725/49676155-79e01100-fa2d-11e8-915b-8c508424a18b.png)

I haven't tried making any fixes yet since I'm not too familiar with this area of SlickGrid. Figured I would ask before I start tinkering.

**Comment by ghiscoding** [comment]
Oh that is quite large of a number, so the `Math.ceil` won't help at all, I don't know of that CSS workaround, this is probably better answered by @6pac 

@anthonydresser I was looking at the Microsoft repo that you're using this grid with, is there a live demo of it with the grid? Just curious about it and I don't have any Azure account.

**Comment by anthonydresser** [comment]
The Microsoft repo is an Electron application rather than web based, so it doesn't require a Azure account. Its an application for managing SQLSever, so we use SlickGrid as our results grid when performing queries. We don't have a "live example" per say, but you can certainly test it for free; if you are interested we have quick start guides for install the application and locally installing a sqlServer instance to connect to:

https://docs.microsoft.com/en-us/sql/azure-data-studio/quickstart-sql-server?view=sql-server-2017

mac specific guide:
https://blogs.msdn.microsoft.com/bobsql/2018/04/24/take-the-sql-server-mac-challenge/

**Comment by ghiscoding** [comment]
Oh that is why it looks like VSCode 😉 
I'll give that a try possibly on Monday. we do use SQL Server (not Azure) at work, so it might be useful

I'm glad to see SlickGrid is used in some Microsoft projects/applications 😄 
It's been my favorite grid for years, even though I used other grids (like UI-Grid), I always came back to it. So last year, I decided to create 2 wrappers on top of it [Angular-Slickgrid](https://github.com/ghiscoding/Angular-Slickgrid) and [Aurelia-Slickgrid](https://github.com/ghiscoding/aurelia-slickgrid), I love this grid. Also, hopefully we can get the frozen/pinning functionality done in the coming month(s) too (ref #26)

@6pac 
Do you have any idea on this issue?

**Comment by anthonydresser** [comment]
@ghiscoding thanks, I'll take a look at those changes.

**Comment by 6pac** [comment]
OK, I've had a long look at this one. Unfortunately, I don't think it's possible to fix. It appears that the offsets are being set correctly, and strangely it's the text that's moving, not the border lines.

I think it's actually that the CSS itself has trouble with the really large offsets.

![image](https://user-images.githubusercontent.com/143957/180895573-ecb9d802-0143-42c2-964e-c6e8530c2c64.png)

I note if I retrieve the 'top' prop from the DOM, it comes back with exponential notation, suggesting that it's losing precision internally. 

One last idea would be to try reducing the MaxCssHeigh with the new defaults. I've run out of time this morning, but will try this later today.

**Comment by 6pac** [comment]
@ghiscoding @anthonydresser pleased to note that knocking a few zeros off the new maxSupportedCssHeight option appears to fix the issue. So in the end it looks like CSS simply being unable to cope with that large an offset accurately (it *nearly* gets there!)

**Comment by ghiscoding** [comment]
ECMAScript 2020 now supports [Big Int](https://github.com/tc39/proposal-bigint) if that helps 🤣 so is it this [commit](https://github.com/6pac/SlickGrid/commit/6f4ae7c56250a923ce0729d65cfed9f00bd02845) that fixed it?

**Comment by 6pac** [comment]
@ghiscoding cool! yup that's the commit, but as far as I can see it's a css/browser issue, not anything to do with js or slickgrid. the 'top' values in the image above come back from the DOM like that - it's not an artefact of js.
