### ISSUE TITLE
Cell edit -> ReferenceError: e is not defined

### ISSUE THREAD

**Issue by TerminalMan** [6pac/SlickGrid#298]
https://github.com/6pac/SlickGrid/blob/0abf4326793bb46c0bb949046bf30e9280fdddf1/slick.grid.js#L3144

The above line is causing a "ReferenceError: e is not defined" error

The example on your webpage uses a 'slick.grid.js'that does not have this line. After removing the line it seemingly works fine.

To test:
git clone the repo and run the "example3b-editing-with-undo.html" example, then try to edit a cell.

**Comment by 6pac** [comment]
Apologies, I didn't test well enough after applying some patches. Fixed, pushed to repo and released new ver.
