### ISSUE TITLE
'Filling the whole window' example does not resize with changes in window size

### ISSUE THREAD

**Issue by MisterAcoustic** [6pac/SlickGrid#31]
Open a browser window to full screen, and load the 'Filling the whole window' example.
Move the vertical scroll thumb to the bottom.
Size the window smaller.
Note that while you can still see the vertical scroll bar, the scroll thumb is out of view, below the current window bottom. Also note that the horizontal scroll bar is completely lost.

I am just considering SlickGrid for use in a project, and I am hopeful that this is just an issue where the sample isn't responding to the necessary events, and calling resize as needed. If someone could confirm or deny this explanation, perhaps along with the code necessary to make it work properly, that would be nice.

Thanks!

**Comment by 6pac** [comment]
I think this is a css issue more than anything. whether the content resizes with a screen size change depends on the css sizing mode. this is said to work in the example text, but doesn't appear to.
I can have a look at this in a week or so.

**Comment by MisterAcoustic** [comment]
I had a chance to mess around with this, and I discovered that you can indeed bind to the window resize event, and in your function call grid.resizeCanvas(). That seems to make it work quite nicely (in my situation, with some other mods). I'll keep listening in case a better way comes up.

**Comment by 6pac** [comment]
i still haven't had a chance to look, but i think this will be the solution.
the example claims to resize the grid on browser page resize, but as far as i can tell, it doesn't.

**Comment by ghiscoding** [comment]
@MisterAcoustic I added a new example for [Grid auto-resize on window browser change](http://6pac.github.io/SlickGrid/examples/example15-auto-resize.html), you should take a look at it and it might close your issue.

**Comment by ghiscoding** [comment]
I think we can close this issue since I provided the [Example - Grid Auto-Resize](http://6pac.github.io/SlickGrid/examples/example15-auto-resize.html)

**Comment by ghiscoding** [comment]
Closing since [Example - Grid Auto-Resize](http://6pac.github.io/SlickGrid/examples/example15-auto-resize.html) was provided. User can follow that example to implement window resize
