### ISSUE TITLE
Padding in parent div causes unfrozen columns to overlap with frozen columns

### ISSUE THREAD

**Issue by michvllni** [6pac/SlickGrid#316]
I have two slickgrids side by side. To differ them, the right one has a padding-left of 3vw. The viewports and their headers seem to inherit this padding-left, even if it is not shown in the properties. If I remove the padding on the parent, it all works as expected. I also tried to force the slick-pane to have a padding of 0px, but that did not help as well.
![The frozen columns](https://user-images.githubusercontent.com/45660891/50677506-8474d280-0ffa-11e9-87da-ce53007bc5fc.PNG)
![The unfrozen columns](https://user-images.githubusercontent.com/45660891/50677514-90609480-0ffa-11e9-97e9-86f3735e0db3.PNG)

As you can see, there is an overlap between the second and third column.

My selected options:
"options": {
      "forceFitColumns": false,
      "rowHeight": 20,
      "multiColumnSort": true,
      "multiSelect": false,
      "frozenColumn": 1
    }

EDIT: As a workaround, using a margin instead of a padding seemed to do the trick. Still very weird.

**Comment by 6pac** [comment]
You'll have to post the css. I don't know how the setting has been applied.
Also, this is probably an implementation issue, not a bug, in which case we prefer that you post to StackOverflow.

**Comment by michvllni** [comment]
I didn't touch the css. I only added the margin to the div in my code via `gridDiv.style.paddingLeft = "3vw";`. The reason i posted it here was that it seemed to be an issue with the new feature.

**Comment by ghiscoding** [comment]
I tried couple of the Frozen examples and we don't see this behavior. So unless, you can reproduce with the examples, it's hard to help you. If you find a working solution, you can always post it or create a PR

**Comment by ghiscoding** [comment]
Might have misunderstood your original question, since your first comment had 2 print screens on the `.slick-pane-left` and `.slick-pane-right`, now your last comment has it on the entire grid itself. If you're trying to add padding there, why don't you go further on the top and add it to the entire wrapper? I mean in the `<div style="width: 600px">`. 

If you really wanted padding, I think you might need to put on the top wrapper or on each of the pane (left/right). Also this code come from the X-Slickgrid repo, that repo probably has the same behavior. Instead of trying to fix the issue, I would try to just find the correct class to add your padding.

**Comment by michvllni** [comment]
The reason i had two screenshots in my first comment was that i wanted to show the overlap. Perhaps i wasn't clear enough with what I wanted to do. In my project I have two slickgrids in the same wrapper, so I tried to differ them from each other by using the padding. As I said in my first comment, I fixed it by using a margin instead of a padding. I just thought it was weird and maybe a bug. It's up to you guys to decide if it's worth fixing as this is a really rare use case i guess. I'd try to fix it myself, but unfortunately I'm still a beginner when it comes to JavaScript. But thanks for your time :)

**Comment by ghiscoding** [comment]
I don't think it's a good idea to have 2 grids with the same wrapper, I always use 1 container (wrapper) per grid and do whatever I want in each container independently. If you try to 2 containers, the problem probably goes away. So I don't think this is a bug per say.

**Comment by michvllni** [comment]
That is indeed a good idea. I think I might do that in the future as well. Thank you!
