### ISSUE TITLE
slick.columnpicker.js seems to be missing checks

### ISSUE THREAD

**Issue by SatanEnglish** [6pac/SlickGrid#317]
@ghiscoding 
I'm having issue with the new slick.columnpicker.js.

Don't want to just go ahead and make changes as I could be wrong.
So here is what I found and you can check if it's what should be done thanks.

1) Missing high level options e.g. missing line
`_options = options`
Then everything should be referencing `_options`

2) line 109 Is missing the extra check that the column Picker exists
` if (_options.columnPicker.headerColumnValueExtractor) {`

Should be

// Checking for both the picker existing and the headerColumnValueExactor 
`if (_options.columnPicker && _options.columnPicker.headerColumnValueExtractor)`

**Comment by ghiscoding** [comment]
what's the issue? is it reproducible? if it's just variable naming, that shouldn't cause much problem.

**Comment by SatanEnglish** [comment]
1) options doesn't exist.
 **My Guess** is that in the example that options is global param on the page.
2) Missing the check that's on all the other if statements `_options.columnPicker`

**Comment by ghiscoding** [comment]
You didn't say or show what your problem is... if you could provide a way to reproduce that would be better. You can always create a PR if you find a fix of whatever your problem is.

**Comment by ghiscoding** [comment]
Try changing

```js
if (options.columnPicker.headerColumnValueExtractor) {
  columnLabel = options.columnPicker.headerColumnValueExtractor(columns[i]);
} else {
  columnLabel = defaults.headerColumnValueExtractor(columns[i]);
}
```
and add more property checks like this 
```js
if (options && options.columnPicker && options.columnPicker.headerColumnValueExtractor) {
  columnLabel = options.columnPicker.headerColumnValueExtractor(columns[i]);
} else {
  columnLabel = defaults.headerColumnValueExtractor(columns[i]);
}
```
At least that is what breaks in the console, since `options.columnPicker` is undefined but `options` is defined.
