### ISSUE TITLE
Need a way of fixing a column

### ISSUE THREAD

**Issue by SatanEnglish** [6pac/SlickGrid#318]
@6pac @ghiscoding 
Hi Guys,

In need of locking a column in place but not as a frozen column.

Can I get your guys input.

I've had a look at how the `setupColumnReorder()` method works and have come up with a bit of a hack.

Need your thought if this would be good enough to put into the implementation or if we can figure out some nicer ideas around it.

Inside the `setupColumnReorder` method inside the loop to reorder the columns I have added:
```
var columnDef = columns[getColumnIndex(reorderedIds[i].replace(uid, ""))];
if (columnDef.fixedPosition && columns.indexOf(columnDef) != i) {
    setColumns(columns);
    return;
}
```
Then in the example that follows I have added `fixedPosition = true` to the first columnDef result as follows.

![2019-01-11_16-36-57](https://user-images.githubusercontent.com/2100563/51011889-47db4500-15bf-11e9-8997-8f1e5c0bba24.gif)

This will only work if the columns are on the outside columns

Thoughts???

PS: Another version showing the scrolling left to right

![2019-01-11_16-43-48](https://user-images.githubusercontent.com/2100563/51012100-57a75900-15c0-11e9-9302-c383dd9311cd.gif)

**Comment by ghiscoding** [comment]
I believe PR #64 was supposed to do that, but this PR is quite old and out of sync

**Comment by SatanEnglish** [comment]
That PR is frozen columns

**Comment by ghiscoding** [comment]
No that PR is to block a column from being part of the column reorder. In other words, if that flag is set to true, user cannot move the specified column.

**Comment by 6pac** [comment]
Don't have a problem with this in principle, but I did raise a number of issues regarding the descriptive  terms and logic in #64.
Terms can maybe be 'pinning'=row or column 'scroll-locking', and 'fixed columns'=column 'drag-locking'.
Re the logic, for example, drag-locking any but the n left or n right columns doesn't make sense, and the logic needs to stop non-drag-locked columns being dragged within or to the outside edge of the locked column block.

**Comment by SatanEnglish** [comment]
@6pac 
I see so you are saying you would want it treat it like the frozen columns.
Something the equivalent to frozenRow: X

e.g
lockedOrderColumnsFromLeft: 2
lockedOrderColumnsFromRigth: 4

Assuming we had 8 columns this would mean only the 3rd and 4th column could be dragged.

Likely safe to say you cannot used frozen and LockedOrder together?

**Comment by ghiscoding** [comment]
So unless I am mistaking, you can already set `enableColumnReorder: false` option to the column you don't want them to be reordered. If that is not what you were looking for then please provide more details but for now I'll go ahead and close the issue. 

Also note that a lot changed since this issue was opened, our whole code structure changed (we removed jQuery/jQueryUI and we migrated to TypeScript). If you think this is still a problem then please provide more details.
