### ISSUE TITLE
Used a wrong keyCode name. PAGEDOWN and PAGEUP

### ISSUE THREAD

**Issue by maxim-s-barabash** [6pac/SlickGrid#32]
In slick.grid.js used keyCode.PAGEDOWN and keyCode.PAGEUP.
But in slick.core.js declared 
"keyCode": {
...
        PAGE_DOWN: 34,
        PAGE_UP: 33,
...
      }

**Comment by 6pac** [comment]
thanks for the catch. i had used PAGEDOWN in my code but later harmonised with jQueryUI which uses PAGE_DOWN
