### ISSUE TITLE
combine functions with frozencolumns and column grouping

### ISSUE THREAD

**Issue by ryoma0701** [6pac/SlickGrid#326]
@6pac 
Can I combine functions with frozencolumns and column grouping?

**Comment by ghiscoding** [comment]
There's only 1 way to find out... try it

**Comment by ryoma0701** [comment]
@ghiscoding 
Could you tell me how?

**Comment by ghiscoding** [comment]
see issue #340

**Comment by ghiscoding** [comment]
closing as this was fixed by #429
