### ISSUE TITLE
Bas cell selection if grid is scrolled

### ISSUE THREAD

**Issue by mpegithub** [6pac/SlickGrid#328]
Hello,
In this example [example-frozen-columns-and-rows-spreadsheet.html](http://6pac.github.io/SlickGrid/examples/example-frozen-columns-and-rows-spreadsheet.html), 
and in the bottom grid, if the grid is scrolled down and a selection is made, this one is incorrect: it looks like the number of scrolled lines are added to the selection...

**Comment by 6pac** [comment]
Can confirm this is fixed in 2.4.3 just released
