### ISSUE TITLE
overflow-scrolling on MacOS (Chrome, Safari) breaks getViewport()

### ISSUE THREAD

**Issue by RobinHansen** [6pac/SlickGrid#332]
After having scrolled to the beginning of a grid and "beyond" (overflow-scrolling) getViewPort() returns NaN for the fields top and bottom.  This only happens on MacOS (Safari 12 and Chrome 71) , while Chrome 71 on Linux is OK.  During normal scrolling the values are fine.

I tracked this to the variable scrollTop being miscalculated in handleMouseWheel()
The mousewheel handler is set with this comment: "Work around http://crbug.com/312427."

This bug report was closed on Mar 2 2017, so possibly the work-around is not needed anymore?  Disabling the mousewheel handler solved the problem in my case. Maybe someone with more insight can confirm?

**Comment by ghiscoding** [comment]
You mention a work around, is that within the `slick.grid.js`? If so, can you please point to the line of code so that we can look into it. However I'm on Windows only on my side, so I won't be able to test anything though

**Comment by RobinHansen** [comment]
In release 2.4.1, line 580 reads: `// Work around http://crbug.com/312427`
I removed the lines 580-584, so that the mousewheel handler is not set (applies to MacOS only). 
There is a good chance that the work around is not needed anymore (well, at least with recent browsers) as the bug apparently has been fixed.

Now, the error - which I must admit I did not look more into - is likely in line 3818:
`scrollTop = Math.max(0, $viewportScrollContainerY[0].scrollTop - (deltaY * options.rowHeight));`
which puts a NaN into scrollTop.

Greetings

**Comment by ghiscoding** [comment]
I'm not familiar with that piece of code, maybe @6pac is more in the know. Here is the [line](https://github.com/6pac/SlickGrid/blob/master/slick.grid.js#L579) of code. The bug report says that it's no longer reproducible since at least March 2017, that is almost 2 years so I wouldn't mind removing the patch if it fixes another this new issue. I'll let @6pac decide though

**Comment by 6pac** [comment]
Think it should be fine to remove that now. The only reason I'm hesitant is that there are a whole bunch or scrolling related issues being resolved just this week and I'm no longer sure of the role ```handleMouseWheel``` plays at the moment. @ghiscoding you're in the thick of it, can you advise if I can just remove this safely?
