### ISSUE TITLE
Enalbling frozenColumn disables cell range selection

### ISSUE THREAD

**Issue by BillyGeat** [6pac/SlickGrid#336]
As stated here https://github.com/6pac/SlickGrid/issues/26#issuecomment-449476041 enabling frozen columns should make also cell range selection working (again).
But I tried a simple example where cell range selection works until I activate frozenColumn. Then it selects only one the first cell clicked and does not select the other (dragged over).

I have also created a detailed StackOverflow post with an jsfiddle example here: https://stackoverflow.com/questions/54574757/enalbling-frozencolumn-disables-cell-range-selection

EDIT / UPDATE
Maybe important info: I just updated my local copy of the repository and now, if I drag to select cells with frozenColumns activated, I get an error:

slick.cellrangedecorator.js:51 Uncaught TypeError: Cannot read property 'top' of null
    at CellRangeDecorator.show (slick.cellrangedecorator.js:51)
    at SlickGrid.handleDragStart (slick.cellrangeselector.js:115)
    at Event.notify (slick.core.js:147)
    at trigger (slick.grid.js:2029)
    at HTMLDivElement.handleDragStart (slick.grid.js:3854)
    at HTMLDivElement.dispatch (jquery-1.11.2.min.js:3)
    at HTMLDivElement.$event.dispatch (jquery.event.drag-2.3.0.js:382)
    at HTMLDivElement.<anonymous> (jquery.event.drag-2.3.0.js:267)
    at Function.each (jquery-1.11.2.min.js:2)
    at m.fn.init.each (jquery-1.11.2.min.js:2)

**Comment by ghiscoding** [comment]
Can you please use latest code, PR #331 got merged yesterday to fix a cell range issue (#329) with frozen grids (with `slick.cellrangeselector.js`). Also note that I know you're not using latest code because the [line 51](https://github.com/6pac/SlickGrid/blob/512f704d4de2e3e6e46b499b9aa109ff225f0a38/plugins/slick.cellrangeselector.js#L51) is a curly brace and so it cannot be an error with `Cannot read property 'top' of null` as you mentioned

**Comment by BillyGeat** [comment]
I am pretty sure, that right now, I have the latest version of the code base...
A curly brace you mention exist in file slick.cellrangeselector.js but the error I got comes from slick.cellrangedecorator.js and there is a "top" property in my copy. Maybe I miss something else?

**Comment by ghiscoding** [comment]
Actually the error came from the `slick.cellrangedecorator.js` while I thought it was the `slick.cellrangeselector.js`. On the other end, the yesterday PR might have introduced a small issue, it doesn't seem to work when you specify only 1 frozen (column or row). So basically if you add `frozenRow: 0` as a temporary patch, that will work... so I'll look into fixing this sometime today but for now you can use the hack I just mentioned

**Comment by ghiscoding** [comment]
Found the issue, the new PR has 2 new variables which were not initialized causing `NaN` to show up in the `slick.cellrangedecorator.js` because that was not a valid number.

Can you please try again, I fixed and merged the code

**Comment by BillyGeat** [comment]
Yes, both issue are now fixed, great! Works without the "frozenRow" workaround and I do not get the JS error in the console anymore (it was driving me crazy, why it worked in my jsfiddle (where scrollbars were visible) and not in my local development version (where I had only horizontal scrolling or no at all).
Thank you!

**Comment by ghiscoding** [comment]
Good thanks for the feedback 😉
