### ISSUE TITLE
Column grouping headers does not work with frozen columns

### ISSUE THREAD

**Issue by 8over8** [6pac/SlickGrid#340]
I have code in place to add column grouping headers to a grid instance. This works perfectly when frozen columns are not turned on. When frozen columns are applied on top, the rendering of the grid is incorrect.

A quick debug of the library seemed to highlighted that the preHeaderPanel is applied to the frozen panel (left panel) but not applied to the unfrozen portion of the grid (right panel).

**Comment by ghiscoding** [comment]
Yeah I'm not surprised, we've never tested the 2 features together and grouping was not part of the Jlynch & X-Slickgrid repos (the later is the one we used to bring frozen feature in here). If you have a fix for the issue, please feel free to make a PR. We should also add an Example demo for that as well

**Comment by 8over8** [comment]
I'll have to look at this next week. It will need some analysis and design if we're to create a pull request. Will get back to you when I've time to better look at this.

**Comment by NemoDima** [comment]
I would really appreciate it if someone could implement this functionality.

**Comment by ghiscoding** [comment]
@NemoDima 
Please be my guest, if you have multiple hours to spend in troubleshooting it, we would surely be happy if you can help in finding the issue

**Comment by 8over8** [comment]
When I looked at this it was too big for the time frame I had to meet some deadlines. At that point the functionality got changed to meet the deadline. I haven't had time to get back to this and probably won't. As @ghiscoding says, please feel to take it on.

**Comment by NemoDima** [comment]
Unfortunately, my qualifications are not enough for this task. I would be very grateful if someone could help. But I understand that this may not be so a priority for the participants.
In any case, thanks for your answers, maybe in future someone else will decide to overcome this problem.
