### ISSUE TITLE
Whether all cells in a row are specified for editing?

### ISSUE THREAD

**Issue by a5414671414** [6pac/SlickGrid#350]
Whether all cells in a row are specified for editing？

**Comment by 6pac** [comment]
Please ask questions like this on StackOverflow. Issues here are for bugs and enhancements.   
In this case:

      var allCellsHaveEditor = true;
      for (var i = 0, ii = columns.length; i < ii; i++) {
          if (!columns[i].editor) { allCellsHaveEditor  = false; break; }
      }
