### ISSUE TITLE
Cannot change ID of an Item using the DataView UpdateItem

### ISSUE THREAD

**Issue by ghiscoding** [6pac/SlickGrid#353]
We found out that the DataView doesn't allow an item to change it's ID, an [issue](https://github.com/ghiscoding/Angular-Slickgrid/issues/149) was opened in my repo for that, and the reason is because `updateItem` checks for ID to exist in the DataView local array of IDs with this [line](https://github.com/6pac/SlickGrid/blob/master/slick.dataview.js#L359)
```js
function updateItem(id, item) {
  if (idxById[id] === undefined || id !== item[idProperty]) {
    throw new Error("Invalid or non-matching id");
  }

```
When user changes the item ID, the DataView is complaining that it doesn't find it in his local array copy.

A similar issue was opened in the mleibman/SlickGrid [#1082](https://github.com/mleibman/SlickGrid/issues/1082) and if we keep scrolling down the issue, we can see that GerHobbelt replied with a fix that he pushed in his own fork with this [commit](https://github.com/GerHobbelt/SlickGrid/commit/d157fd7ec55482e3e7f5990e5bf46aedf65371da). 

@6pac 
Would you be ok to push this [change](https://github.com/GerHobbelt/SlickGrid/commit/d157fd7ec55482e3e7f5990e5bf46aedf65371da) from GerHobbelt into our DataView code? That would allow user to possible change item ID without receiving a error in the console.

**Comment by 6pac** [comment]
Can do. I note 

    // Also update the rows? Nah, `refresh()` blows away the `rows[]` cache and recalculates it via `recalc()`!

I'm inclined to do that update. Opinions? I note I don't really use the DataView, I have a different improved custom data source that I use.

**Comment by ghiscoding** [comment]
I use the DataView, even with backend services api, because of all the features it brings like multi-column grouping for instance. 

> // Also update the rows? Nah, `refresh()` blows away the `rows[]` cache and recalculates it via `recalc()`!

I think that I would tend to agree with his comment, refresh the entire dataset (with `refresh()`) is expensive and is probably not needed since we're only updating 1 row of data.

**Comment by 6pac** [comment]
i was interpreting it as 'won't fix the one line of the rows[] cache because the user will likely call refresh()'.
possibly not safe to make that assumption?

re the datagrid, I've got a much improved version that does a whole bunch of extra stuff, plus doesn't reply on IDs at all (just row indexes). i haven't publicly released it, for complicated reasons, but i would be happy to release it to a trusted few ;-)  it does mean re-tooling the grid for a data provider (to support object, DataView and the new datasource), which I did to my private fork years ago, but not sure if the public version is ready for that either.

**Comment by ghiscoding** [comment]
> i was interpreting it as 'won't fix the one line of the rows[] cache because the user will likely call refresh()'. possibly not safe to make that assumption?

That could be another interpretation, anyhow I don't there's any arm in doing this change, is there? Can I go ahead with a PR?

I wouldn't mind giving a look and possibly a try at your other sub-lib, I might not go all in with my repos though, but worth a try if it's more efficient and has more functionalities.

**Comment by 6pac** [comment]
Sure thing. 

Are you on BitBucket (the place that offers free private repos? :- )

**Comment by ghiscoding** [comment]
Hmm I think I have an account there because we use it at work, but I never used the cloud one. I probably forgot my password too but I can reset it lol. Atlassian suite is nice and it's Aussie :D

**Comment by ghiscoding** [comment]
> > // Also update the rows? Nah, `refresh()` blows away the `rows[]` cache and recalculates it via `recalc()`!

> i was interpreting it as 'won't fix the one line of the rows[] cache because the user will likely call refresh()'. possibly not safe to make that assumption?

Actually looking at the code and testing it, I just found the reason of that comment, if you scroll down the code, the `refresh()` is called 5-6 lines after that, so the guy says.. nahh no need to recalculate since the `refresh()` blows it away anyway. 

I'll submit the PR in a few
