### ISSUE TITLE
No horizontal scrollbar when autoHeight = true

### ISSUE THREAD

**Issue by DarranShepherd** [6pac/SlickGrid#356]
Editing the columns array definition in example11-autoheight.html to the below, the grid can be scrolled horizontally using a trackpad/mouse, no horizontal scrollbar is displayed.
```
columns = [
  { id: "title", name: "Title", field: "title", width: 200 },
  { id: "duration", name: "Duration", field: "duration", width: 200 },
  { id: "%", name: "% Complete", field: "percentComplete", width: 200 },
  { id: "start", name: "Start", field: "start", width: 200 },
  { id: "finish", name: "Finish", field: "finish", width: 200 },
  { id: "effort-driven", name: "Effort Driven", field: "effortDriven", width: 200 }
]
```

![NoHorizontalScroll](https://user-images.githubusercontent.com/5823355/55069053-12e97500-507b-11e9-8d91-d1e80e22b714.PNG)

Is this expected behaviour? If not, could anyone give me a pointer to where I might be able to resolve it?

From my investigation, the scrollbar appears to be there on the viewport, but because the viewport's container, `.slick-pane-top.slick-pane-left`, height is set to the height of the viewport, it's below the bottom of the top left pane. I've experimented with adding the height of the scrollbar to the top pane, but at this stage, `viewportHasHScroll` hasn't yet been calculated, and even when doing so, the canvas appears to have a little extra padding below the final row, so simply adding the height of the scrollbar is insufficient.

![HalfHorizontalScroll](https://user-images.githubusercontent.com/5823355/55070611-9062b480-507e-11e9-9516-3f2dd807cf3b.PNG)

**Comment by 6pac** [comment]
Happy to take a look at this. @ghiscoding and @SatanEnglish, you have been doing a lot of work recently regarding viewport dimensions, do you want to take a look or shall I?

**Comment by ghiscoding** [comment]
The last change we did related to the `autoHeight` was the grid missing some rows on the vertical side, nothing on the horizontal side of it. I'm wondering if it's any related to the frozen feature added, might be useful to try it with previous `2.3.x` version. I don't really have time to look into this myself

**Comment by DarranShepherd** [comment]
I can confirm that the scrollbar is present in version 2.3.23

![HorizontalScrollIn2-3-23](https://user-images.githubusercontent.com/5823355/55222055-d2b4fe80-5202-11e9-932a-d6db106eed24.PNG)

**Comment by 6pac** [comment]
that's a good clue. will try to have a look  on Sunday

**Comment by ghiscoding** [comment]
Pushed a fix #360 since I had a bit more knowledge with autoHeight and frozen feature. You can see animated gif of the fix in PR #360

**Comment by 6pac** [comment]
awesone, thanks @ghiscoding

**Comment by DarranShepherd** [comment]
Sorry for the delayed response, @ghiscoding , @6pac , I was away for the weekend.

This PR fixes my issue perfectly. Thanks so much for such a quick resolution.
