### ISSUE TITLE
Need to change 'idProperty' used in grid

### ISSUE THREAD

**Issue by ninezero90hy** [6pac/SlickGrid#357]
I use Slickgrid very powerfully.
I think many functions are working normally and are grid with good performance such as rendering speed.
But there's one problem that's been bothering me for a very long time.
The value of `idProperty` used in the grid is `id`.
https://github.com/6pac/SlickGrid/blob/f515b9b8cbafc23b0da9cde0705967158219687c/slick.dataview.js#L33
I don't think it's just me.
Let me give you an example that I use.

<img width="1678" alt="스크린샷 2019-03-28 오전 12 24 49" src="https://user-images.githubusercontent.com/41019113/55088941-f176a080-50ef-11e9-9f1e-d8e716579f3a.png">

I'm using a grid in a kind of database tool and I'm using it to express the results of SQL.

I ran a very simple SQL(`select "id", 1, 1, 1;`).

<img width="1680" alt="스크린샷 2019-03-28 오전 12 23 31" src="https://user-images.githubusercontent.com/41019113/55088888-d86def80-50ef-11e9-88f5-8aaebc8eafa9.png">

Reproduce situations where problems can occur.

SQL that can cause grid errors

`select "id", 1, 1, 1`
`union`
`select "id", 2, 2, 2`
`union`
`select "id", 3, 3, 3`

<img width="1680" alt="스크린샷 2019-03-28 오전 12 23 04" src="https://user-images.githubusercontent.com/41019113/55088846-cab86a00-50ef-11e9-8ed2-8c9d2bf0170f.png">

I have given a simple example, but I actually think that the `primary key` of several tables can be 'id'.

What I want to say here is simple.

`Q1`. @6pac Is it possible to change the value of 'idProperty' to a value that will not overlap?

Currently, I am using the value by changing it directly.
That made it difficult for me to use the plugins.
Help me. :)

**Comment by ninezero90hy** [comment]
I spoke on the assumption that @6pac  knew about the database. :)

**Comment by ghiscoding** [comment]
`idProperty` is a variable (in DataView) and can be change, if you want to use another property name, then just change the `idProperty` with the primary key name you wish to use.

**Comment by ninezero90hy** [comment]
Don't you have to modify the source yourself to do that?
I would like to use the 'npm' package as a way to install it.
How not to modify source code!

**Comment by ninezero90hy** [comment]
I understand that the source code cannot be changed unless it is modified directly.
If the information I know is correct, I would like to provide a function so that I can change the `idProperty` from the outside.

**Comment by ninezero90hy** [comment]
@6pac May I send you PR(add a feature to change the value of `idProperty`)?.

**Comment by ghiscoding** [comment]
use `setItems(dataset, objectIdProperty)` like shown in this [line](https://github.com/6pac/SlickGrid/blob/master/slick.dataview.js#L131), that is when you create the DataView instance and you pass it the dataview. The `objectIdProperty` is really how to override the `id` and it's optional, so if you don't pass it, then it will use `id`. So unless I misunderstood, that is the way to go

**Comment by 6pac** [comment]
Yep, agree with @ghiscoding, looks like ```setItems``` is the way to change the ```idProperty```. I don't think a PR is needed, since you're always going to be using ```setItems``` at some point to initialise the data.

**Comment by ninezero90hy** [comment]
@ghiscoding @6pac Thank you. I didn't know how to change it.
