### ISSUE TITLE
SlickGrid can be Accessible or not?

### ISSUE THREAD

**Issue by haneeftaj** [6pac/SlickGrid#37]
Hi Team,

Regarding accessibility of the slickGrid. 
1.    Is the Slick Grid can be accessible with the keyboard? -  Can we do accessibility for the slick grid.
2.    will it work with the JAWS(screen reader).
3.   Can we use controls/formatters inside the slick grid with keyboard.

**Comment by 6pac** [comment]
Hi haneeftaj, the team at the moment is just me - and all of you!
I don't think there has been specific attention to make the grid accessible in the standards-compliant sense. So the answer to your questions are: I don't know, but probably not.
However the great thing about SlickGrid is that it's easy to customise. I have my own heavily customised private branch that incorporates a lot more keyboard control. I will eventually feed many of these changes back to the public project, but I'm too busy at the moment.

If you or someone else wants to contribute changes to enable accessibility, I'm happy to review and commit them.

Ben McIntyre

**Comment by haneeftaj** [comment]
HI Ben/Team,

Thanks for your response. I saw slick grid is made up of "div's". Is there any possibility that we we can change div's into table structure. To be clear each cell can we make it as <td>?. Please let me know the posibility.

Thanks
Haneef

**Comment by haneeftaj** [comment]
HI Ben/Team,

Thanks for your response. I saw slick grid is made up of "div's". Is there any possibility that we we can change div's into table structure. To be clear each cell can we make it as <td>'s? Please let me know the posibility.

Thanks
Haneef

**Comment by haneeftaj** [comment]
Can we make it as td (table data).

**Comment by 6pac** [comment]
I think that's a pretty easy answer: no.
The divs are at the heart of the entire project, it would require major rework to change.
Not to mention, tables are now considered very bad design for applications such as this.

Learn CSS and HTML5 and the divs turn out to be far more flexible than a table.

**Comment by Excelautomation** [comment]
@haneeftaj check out [http://js-grid.com/docs](url) it uses tables instead of div's. If you're more interested in that. :-)

**Comment by sjaveed** [comment]
I'd argue that for truly tabular data, which is what Slick.Grid is mainly used, tables are still the semantic and right thing and can be styled just as easily as divs and spans.  There might be other (legacy) reasons that divs were used in Slick.Grid though and those might still be relevant.

**Comment by 6pac** [comment]
You are possibly right, my comments may be out of date by a few years. HTML5 has brought back semantic design and this is tabular data. However, I thing divs are still heavily embedded in this project and it won't be changing any time soon. With a lot of the new HTML5 styling, the difference between different elements is closing anyway.
