### ISSUE TITLE
Cancel opening detail panel on click

### ISSUE THREAD

**Issue by MrMoronIV** [6pac/SlickGrid#378]
Following this example: http://6pac.github.io/SlickGrid/examples/example16-row-detail.html

Is there a way to cancel the open action after the row is clicked? Or can I toggle if the plugin is active or not on the fly? I want to have one panel open as a maximum and force the user to click [Save] or  [Cancel] in the detail panel before a new one can be opened.

**Comment by ghiscoding** [comment]
Again all the documentation is directly inside the [Row Detail Plugin](https://github.com/6pac/SlickGrid/blob/master/plugins/slick.rowdetailview.js), I assume you can do what you want with the few events available and then stop the event from bubbling up

**Comment by MrMoronIV** [comment]
As far as I can tell this isn't possible since returning false inside these events only avoids the rest of the code below it to be ran, panels are still opening no matter what I do inside these evemt listeners, hence this question :)

**Comment by SatanEnglish** [comment]
`expandedClass`  Think this is the options your looking for though this may be one div deeper than you need.

Alternatively you could after the detailView is opened get from the returned data in the function the `_parent` which would allow you to get the row that you need to put the class on.

Hope this helps

**Comment by SatanEnglish** [comment]
You could use the expandableOverride for stopping others opening
e.g. You have a bool that you update to say if one is open and update the override to hide all the others while it's open.

Not the best way to do it but this is just one way I can think of doing it.

As for stopping the collapse happening removing the `detailView-toggle` from the item while it's being edited should stop it being able to be collapsed. (Not sure what other issues this would cause tho)

Hope this at least gives you somewhere to start looking

**Comment by ghiscoding** [comment]
better late than never, now available in latest version [5.1.0](https://github.com/6pac/SlickGrid/releases/tag/5.1.0) also note that a lot changed since this issue was created, we dropped jQuery/jQueryUI and we migrated to TypeScript
