### ISSUE TITLE
License - is this considered up to date?

### ISSUE THREAD

**Issue by JoshuaSchlichting** [6pac/SlickGrid#380]
Currently, this line sits on the 0th row of the license:
`Copyright (c) 2009-2016 Michael Leibman, http://github.com/mleibman/slickgrid`

It points to the old repo, and shows the Copyright (c) through 2016. Is this considered up to date despite this? I opened this as an issue, because if it isn't considered up to date, I'm wondering if this is stopping some from using this awesome library.

**Comment by 6pac** [comment]
Thanks for bringing that up. I have updated the license file.
