### ISSUE TITLE
Rowspan

### ISSUE THREAD

**Issue by MrMoronIV** [6pac/SlickGrid#381]
I would really like to have rowspan to span the first cell of one row over multiple rows, it seems like this is not supported at the moment or am I missing something? If not, are there any plans to have this implemented?

**Comment by MrMoronIV** [comment]
In addition, I found this thread about it (from 2013):
https://stackoverflow.com/questions/9880178/how-do-i-create-merged-cells-in-slickgrid

Where this fork is mentioned: 
https://github.com/GerHobbelt/SlickGrid/tree/k0stya-rowspan

However, I assume that code can't just be copy pasted without breaking existing functionality of this main branch.

**Comment by 6pac** [comment]
I think this is too specialised to be on our list of plans for the grid. There is a DetailsView plugin (see the examples) which merges several whole rows, but I thinks that's all you'll get.

**Comment by MrMoronIV** [comment]
Thanks for the clarification. DetailsView only puts a div over several dynamically created empty rows below the clicked row, so no merging there either.

**Comment by ghiscoding** [comment]
🔈 Rowspan is now officially supported via the new [v5.15.0](https://github.com/6pac/SlickGrid/releases/tag/5.15.0) release
