### ISSUE TITLE
Using two plugins ( grouping with detail row ) adds X empty rows

### ISSUE THREAD

**Issue by Daaavs** [6pac/SlickGrid#387]
Hello!
I've been using slickgrid(v2.4.3) and wanted to add the Grouping with Row Detail plugins. It works fine alone, but when I try to get this two together, there's a little bug.
I seems that row detail will overlap grouping. Whenever I click to see details, it will add X empty rows on the the grid ( X is the number of panelRows that we define in the row detail plugin).
When I click one of the detail, it will hide the X rows in the grid (although, alone, it doesn't do that, it behaves "normal").

![x](https://user-images.githubusercontent.com/51437515/59017038-8a394300-883a-11e9-8dad-3295ffc85403.png)
![x2](https://user-images.githubusercontent.com/51437515/59017039-8a394300-883a-11e9-950f-07a26cb23b22.png)

**Comment by ghiscoding** [comment]
duplicate of #340

**Comment by Daaavs** [comment]
you are right @ghiscoding  ! Im not using frozen collumns but the issue seems to be the same !
Sorry about it ! Will close this issue !
