### ISSUE TITLE
Remove jQuery objects from row cache

### ISSUE THREAD

**Issue by 6pac** [6pac/SlickGrid#388]
Since the integration of the Frozen columns and rows feature, the row cache objects are now jQuery objects. This makes sense, in that several DOM objects can be wrapped into a single jQuery object and operated on as a group. 

However for performance and 'weight' reasons, it would be better to rewrite the handling code to handle plain DOM objects.

**Comment by ghiscoding** [comment]
We can safely close this one since it was addressed by PR #766 for upcoming [v4.0 - Roadmap](https://github.com/6pac/SlickGrid/discussions/743)
