### ISSUE TITLE
use dateVIew.setItems() not refresh all rows 

### ISSUE THREAD

**Issue by flylone** [6pac/SlickGrid#389]
i use dateVIew.setItems() to update my data, but not all rows updated. the first row is still show old data, only drag the scroll bar can the first row update

**Comment by 6pac** [comment]
Have you tried ```grid.render()``` ?

This is usually done by wiring up the dataView events, as is done in most of the examples:

    dataView.onRowCountChanged.subscribe(function (e, args) {
      grid.updateRowCount();
      grid.render();
    });

    dataView.onRowsChanged.subscribe(function (e, args) {
      grid.invalidateRows(args.rows);
      grid.render();
    });

It's better to ask questions like this on StackOverflow, The issues list is for bugs and enhancements, not questions about usage.
