### ISSUE TITLE
setSelectedRows does not set the activeRow property.

### ISSUE THREAD

**Issue by coreConvention** [6pac/SlickGrid#395]
If you have a row selected and need to programatically change the selected row, calling setSelectedRows does not set the active css class on the rows sent to the function. You have to call setActiveCell to force the grid to apply the css class to the row. Perhaps this is not a bug, as it makes sense to force it to select a specific cell so you maintain context, but then what is the point of setSelectedRows otherwise?

**Comment by SatanEnglish** [comment]
@6pac 
Think this might be to do with the last change to the plugin that I still haven't managed to find time to revert.

**Comment by ghiscoding** [comment]
I think this issue was fixed by latest PR #447 
@coreConvention could you confirm

**Comment by ghiscoding** [comment]
I assume this is fixed by PR #447, feel free to reopen if this is still a bug
