### ISSUE TITLE
always return undefined $el

### ISSUE THREAD

**Issue by aliramadan8** [6pac/SlickGrid#398]
`delta += parseFloat($el.css(val)) || 0;`

this line always return error `$el` is undefined 
```js
function getVBoxDelta($el) {
      var p = ["borderTopWidth", "borderBottomWidth", "paddingTop", "paddingBottom"];
      var delta = 0;
      $.each(p, function (n, val) {
        delta += parseFloat($el.css(val)) || 0;
      });
      return delta;
    }
```
the easy solution i did was to check before calling `$.each`
```js
function getVBoxDelta($el) {
      var p = ["borderTopWidth", "borderBottomWidth", "paddingTop", "paddingBottom"];
        var delta = 0;
        if ($el == undefined)
            return delta;
      $.each(p, function (n, val) {
        delta += parseFloat($el.css(val)) || 0;
      });
      return delta;
    }
```
or there is something else i need to do in my grid definition ???

**Comment by ghiscoding** [comment]
Are you new to the grid? I mean, is it the first time you are trying to use the grid or did you have some grids before and this is a new issue?

**Comment by 6pac** [comment]
So, can you reproduce this by modifying one of the examples?

**Comment by aliramadan8** [comment]
I have been using the grid before, but this is a new issue after latest update 2.4.9 and I updated to 2.4.10 still same issue

**Comment by ghiscoding** [comment]
Can we know what was the version you upgraded from? was it after or before the frozen feature that was introduced with `2.4.x`? Also as 6pac mentioned, can you replicate the issue in 1 of the examples? We need a way to test the issue.
