### ISSUE TITLE
Dependency on momentjs

### ISSUE THREAD

**Issue by ataft** [6pac/SlickGrid#408]
There appears to be a dependency on momentjs, see here:
https://github.com/6pac/SlickGrid/blob/master/slick.grid.js#L2223

There are a few other references to moment. I get an `Uncaught ReferenceError: moment is not defined` error because of it. 

Happy to make a PR and fix it, just wanted to check first.

**Comment by ghiscoding** [comment]
I get that issue as well, it's from the new version of auto column size that @6pac added. I'm not using the new auto size feature yet so I don't have that problem, but basically it's because `moment` is called and expected to be globally loaded, when that can never happen in strict mode. If you have a way to make it available in strict mode and optional, that would be nice to have a PR for that

**Comment by ataft** [comment]
What if we just changed it to:
`              if (window.moment && colDataItem instanceof moment) { colDataTypeOf = "moment"; }
`

**Comment by ghiscoding** [comment]
isn't the `instanceof moment` still gonna throw the error though? You can try by just changing it on your local and see what happens. You might be right, I'm not totally sure on this one

**Comment by ataft** [comment]
No, it will never be reached. It's certainly not pretty and I'd argue that the moment references should be removed, but also understand the need...

**Comment by 6pac** [comment]
Hey, you're perfectly right. Sorry about that. I'll change the repo now as suggested and push.
You'll notice later on I've used 

        if (colDataTypeOf === 'moment' && typeof moment !== 'undefined') {
          autoSize.colValueArray = [ moment([2009, 8, 30, 12, 20, 20]) ]; // Sep 30th 2009, 12:20:20 AM
        }

so I'm aware of the issue, this was just a slip up.
Actually I think 

       if (colDataTypeOf === 'moment' && moment) {
 
and 

      if (moment && colDataItem instanceof moment) { colDataTypeOf = "moment"; }

are sufficient.

**Comment by 6pac** [comment]
Yeah, in a purist approach there should be no references. On the other hand, as long as they are sandboxed, they don't hurt and frankly people need to be encouraged not to use the vanilla date handling in js. This could be put into a plugin, but that just makes things even more complex. I'm happy to support as many date libraries as people want in this fashion. Note that there is not requirement for momentjs to actually be deployed as part of the package.

**Comment by ataft** [comment]
I'm not sure what you mean by 
`  if (moment && colDataItem instanceof moment) { colDataTypeOf = "moment"; }`
being sufficient?

This is where we're getting the error because moment is not defined anywhere. Referencing it as window.moment should fix the problem...

**Comment by 6pac** [comment]
Yeah, I tend to avoid the ```window.``` part by habit because the code might not be run in a browser, for example in NodeJs. Though I think here we probably have a lot of other ```window``` references. It doesn't really matter. In the end, we're testing ```colDataItem instanceof moment``` (not ```colDataItem instanceof window.moment```), so it makes sense to test for the existence of just ```moment``` first. This is what guaranteed short circuit boolean evaluation in js is for.

**Comment by ataft** [comment]
I agree with avoiding window. As @ghiscoding and I are both saying, `if (moment... ` will throw an error, at least in our environments, and probably many others too. What about
`              if (typeof moment!=='undefined' && colDataItem instanceof moment) { colDataTypeOf = "moment"; }
`
?

**Comment by 6pac** [comment]
Hmmm, looks like you're right.  Could have sworn that ```if (foo)``` returned false if foo was not even declared, but it looks like it does throw. Whoops! So I'll change it back to how it was and add the new check as per your comment above.
