### ISSUE TITLE
Feature Request - Fixed Column on Right

### ISSUE THREAD

**Issue by coder0988** [6pac/SlickGrid#410]
Will you looking to provide a support so that we can use frozen column or right? Or the ability to add columns on different canvas?

**Comment by 6pac** [comment]
I'll leave this to @ghiscoding

**Comment by ghiscoding** [comment]
I would reply to this that it will probably never happen. The reason being that we now have the viewport separated into 4 containers and to be able to also do the right side, we would need 6 containers. I think it's just overkill and left frozen columns should suffice for 90% of use case

**Comment by ghiscoding** [comment]
This is not something that we'll do, if anyone can contribute that would be great but for now we'll close as "won't do"
