### ISSUE TITLE
colDef.autoSize defaults are ignored

### ISSUE THREAD

**Issue by ataft** [6pac/SlickGrid#414]
If you set any colDef.autoSize properties, then the columnDefaults.autoSize properties are not used because of this logic:
https://github.com/6pac/SlickGrid/blob/master/slick.grid.js#L2711 

Adding true as the first argument would do a [deep copy](https://api.jquery.com/jquery.extend/#jQuery-extend-deep-target-object1-objectN) and fix this issue:
```
var m = columns[i] = $.extend(true, {}, columnDefaults, columns[i]);
```

I know this is a breaking change, so is not ideal for those who have already worked around this. However, not fixing this means that many people may find out the hard way. I set the `autosizeMode` property and couldn't figure out why rendering was so slow until I looked through the code and found that the default was not being used. I worked around it by setting `widthEvalMode: Slick.WidthEvalMode.CanvasTextSize`, but many people would probably not get this. 

Happy to make a PR...

**Comment by 6pac** [comment]
good catch, happy to push this even though it's breaking, that's a very recent feature and I suspect you are the first to put it through its paces. thanks.
