### ISSUE TITLE
does content menu work (example 7) in dataview?

### ISSUE THREAD

**Issue by longraider007** [6pac/SlickGrid#42]
Hi,

I try to implement example 7 where with the right mouse click you get the content menu. 
In my test I use dataview.  The problem for me is this code:
    grid.onContextMenu.subscribe(function (e) {
      e.preventDefault();
      var cell = grid.getCellFromEvent(e);

While in the example the 'grid.getCellFromEvent(e)' give you the cell and row, I get 'null' in my dataview.

My question is if this context menu works with using dataview in Slickgrid. 

I even tried using args to get the cell and row but it gives you 'undefined' in the alert.

    grid.onContextMenu.subscribe(function (e, args) {
      alert (args.cell);
      e.preventDefault();
      var cell = grid.getCellFromEvent(e);

I have no idea why this doesn't work. The grid.onClick.subscribe(function (e, args)  works in my code while grid.onContextMenu.subscribe(function (e, args) doesn't.

Thanks!!!

**Comment by 6pac** [comment]
I tried adding the menu to example-4-model and it works fine. The dataView and this menu feature aren't related, so there would be no logical conflict between them. Check your code.
I can't assist further without a copy of the code. I'm working on a jsfiddle template for SlickGrid.

BTW, you should be asking these questions on StackOverflow, not here.
