### ISSUE TITLE
Last version 2.4.12 causing a few errors

### ISSUE THREAD

**Issue by ghiscoding** [6pac/SlickGrid#424]
@6pac 
It looks like your lint went a bit too aggressive in some areas, a got a couple of things that are broken after upgrading to latest version. I'll be doing a PR with some of the fixes, but here's a few errors/bugs found caused by the lint (those are only the ones I found, there might be more).

- [x] `var columns` was removed in ColumnPicker & GridMenu but the `columns` is really a valid variable used in the 2 files
- [x] dragging a column to another position throws an error in the console `cannot read limit.start of null`, this is because changing the `if` that wraps it from `if (limit != undefined)` was blocking `null` but no longer blocks it because it's now checking for equal type, the fix if to use `if( limit !== undefined && limit !== null )`, there's a few places where the lint was changed, we need to address them all like I just wrote
- [x] I can no longer switch language/locale on the HeaderMenu plugin, still investigating that one. 

I found all of these with the Cypress E2E that I have my repos, we'll have to add Cypress to SlickGrid as well because this lint change is causing all kind of issues. 

I'm working a PR to address what I found

**Comment by 6pac** [comment]
Hmmm, OK, I did vet each change quite carefully.
FYI:
- var ```columns``` in Columnpicker is a var but also a parameter in the function. I went for the parameter, but perhaps that was wrong?
- I specifically avoided changing ```!= null``` to ```!== null``` because, like you, I often intend to let ```undefined``` or ```null``` slide by. However that was that one ```= undefined``` that I changed under the assumption that it really did mean ```undefined```. the the ```null``` comparisons were changed, that is a mistake
- i did add 'strict mode' to the function declaration for the grid and the dataview

Apologies for the disruption, I can roll it all back if you like and we can tackle it in detail, but if we can get through it I think the codebase will be better for it.

**Comment by ghiscoding** [comment]
For the `undefined`, you can easily replicate the issue, just drag and drop a column into a different position, you'll get the error in the console. 

Don't need to rollback, but might need another version after I push a PR to fix what I found, I'm still trying to understand why the HeaderMenu doesn't work as intended, there's barely any change done in that plugin, the error must be coming from somewhere else. 

And you don't need to apologies, I'm actually happy that the Cypress E2E test that I have in my repo caught the errors, which is why I'd like to add more of them in your repo and make it part of the build.

**Comment by 6pac** [comment]
I think I did include Cypress already? Not sure how to run the tests, though ...?

**Comment by ghiscoding** [comment]
I did had a PR to add Cypress test, it was a simple and basic test just to get it in place. To run it, you first need to install it through NPM, just run `npm install` from the root of SlickGrid repo, that might take couple of minutes since Cypress is not small (it includes Electron which is based on Chrome), once it is install (after npm finished), you can then run the tool via the command `npm run cypress:open`... oh and you'll need NodeJS if you don't already have it. 

Here's the PR #399 that I made for Cypress

**Comment by ghiscoding** [comment]
@6pac 
So I found my last problem of why the HeaderMenu was not working anymore for me, I couldn't switch locale on the fly anymore, it's caused by the deep clone that you added, specifically this line change
```js
var m = columns[i] = $.extend(true, {}, columnDefaults, columns[i]);
```

I was relying on this being a pointer, so that when I change the locale on my repo, it changes the pointer value, but now it's a completely new object since it's deep clone now. That was to address #414, but caused an issue on my side. I'm not sure how I can fix that one on my side, but I'll probably have to resolve to using some other way of translating these header menu values, the thing is that you now deep clone the column definitions and the text are in those column definitions, so I don't know how I can go around this new issue

**Comment by 6pac** [comment]
Maybe I'll rewrite that just to bring over existing column autosize defaults rather than deep cloning. not that hard to do.

**Comment by ghiscoding** [comment]
Would that rewrite still work for #414? The thing in my case is that the HeaderMenu object gets created under each column definition, I think that should be moved somewhere else in the future, thinking about I'm not sure that a plugin should touch the column definition like that at all.

**Comment by 6pac** [comment]
Look, now that you've noticed the problem, I can imagine that the deep clone might cause problems with a lot of code that assumes the column defs are pointing to the original copy. No problems with the rewrite, it's more complex than just switching to a deep clone, but no biggie really.

Would have to look at what the HeaderMenu plugin does, that's a different issue.

**Comment by ghiscoding** [comment]
Yeah I think I would prefer the rewrite without a deep clone then, HeaderMenu might just be one of the plugin that uses this, other plugins might (and I'm sure there are others), so yeah the deep clone probably breaks some other things that I don't have found with my Cypress tests yet. I know the row selection checkbox also modifies the column definitions as well, it adds an extra column at the beginning of the definition to show the checkbox.

**Comment by ghiscoding** [comment]
I updated the Cypress E2E test for the Grid Menu Example to fully cover the Grid Menu, the last test within the suite fails because of the issue mention earlier (the `undefined`). So now we have at lest that E2E test suite... more will come and that should help identify issues earlier.

**Comment by 6pac** [comment]
OK, I've split the ```autoSize``` defaults to a separate object and switched the code in ```updateColumnProps()``` to

        var m = columns[i] = $.extend({}, columnDefaults, columns[i]);
        m.autoSize = $.extend({}, columnAutosizeDefaults, m.autoSize);

I think that should do the trick.

**Comment by ghiscoding** [comment]
Thanks for handling all of these, I'll check the new version a bit later today. By the look of the last few commits & PRs, it looks good now. Have you had a chance to try Cypress E2E tests?

**Comment by ghiscoding** [comment]
I can confirm that it's all good now, thanks for the quick fix 👍
