### ISSUE TITLE
The addition of 'use strict' in 2.4.13/12 is preventing UglifyJS from running

### ISSUE THREAD

**Issue by stephane-rouleau** [6pac/SlickGrid#430]
In my build steps, I now get the following error:

ERROR in [...] from UglifyJs
In strict mode code, functions can only be declared at top level or immediately within another function. [./node_modules/slickgrid/slick.grid.js:4283,0]

I reverted back to 2.4.11 for now.

**Comment by ghiscoding** [comment]
You might be the only one who can find and fix the issue, can you provide a bit info. We don't use UglifyJS so it's hard for us to help you, you need to help us.

**Comment by stephane-rouleau** [comment]
The line number it's giving me makes no sense whatsoever. I'll investigate further and report back.

**Comment by ghiscoding** [comment]
There was a few PRs that got merged since the latest version, so the line number won't align anymore.

**Comment by stephane-rouleau** [comment]
I confirm that removing the `use strict` makes it work with `uglifyjs-webpack-plugin`. 

Rewriting the function so that toggleCellClass is the first thing in flashCell() also fixes the issue. I would assume that moving it out altogether would also solve the issue.

**Comment by ghiscoding** [comment]
If you can create a PR (Pull Request) to fix that issue, that would be really great as we would prefer to stick `use strict` mode.

**Comment by stephane-rouleau** [comment]
I agree with you, use strict is definitely better. I'll probably get around to it over the weekend, right now I'm chasing another issue where some of my grids don't render after moving from 2.3.x to 2.4.x.

**Comment by stephane-rouleau** [comment]
@ghiscoding pull requested created.
