### ISSUE TITLE
The grid menu does not display properly when frozen columns are used with the grid menu

### ISSUE THREAD

**Issue by songjiqiang** [6pac/SlickGrid#436]
When frozen column and grid menu are used together, the menu will be displayed in the left frozen column panel. This seems not normal. When I look at the source code, I find that it is caused by the following code logic
I only set frozenColumn to 0 because I only need to freeze the checkbox column
![image](https://user-images.githubusercontent.com/28054996/65024760-0aa62e80-d968-11e9-9361-bd545dbc99f1.png)
![image](https://user-images.githubusercontent.com/28054996/65024810-201b5880-d968-11e9-81a7-ff62d74f0649.png)

**Comment by ghiscoding** [comment]
Does it work if you change the source code to `... >= 0` ?

**Comment by songjiqiang** [comment]
The default value of frozenColumn is -1. After I changed the source code in this way, the test was fine. Here is my unit test
![image](https://user-images.githubusercontent.com/28054996/65045282-178b4800-d991-11e9-8b48-ff6c5775d8bb.png)
![image](https://user-images.githubusercontent.com/28054996/65045388-443f5f80-d991-11e9-9771-c8938a08ba52.png)


> 如果您将源代码更改为`... >= 0`？
> 
> 这可能会给普通网格带来问题（当不使用frozenColumn时），我不确定网格选项的默认值是什么`frozenColumn`，我们也要检查它...编辑：默认是`-1`这样应该可以改变对`>= 0`，但我想有确认，它的作品。

The default value of frozenColumn is -1. After I changed the source code in this way, the test was fine. Here is my unit test
![image](https://user-images.githubusercontent.com/28054996/65045282-178b4800-d991-11e9-8b48-ff6c5775d8bb.png)
![image](https://user-images.githubusercontent.com/28054996/65045388-443f5f80-d991-11e9-9771-c8938a08ba52.png)

**Comment by ghiscoding** [comment]
Have you tested with a regular grid (without any frozen)?

**Comment by songjiqiang** [comment]
Yes, I didn't set any frozen columns and normal grids work fine. Here are the unit tests I did not set frozen columns
![image](https://user-images.githubusercontent.com/28054996/65045852-1f97b780-d992-11e9-9294-db3caedd9eab.png)

**Comment by ghiscoding** [comment]
Ok good, I'll do a fix later.. unless you want to create a PR (Pull Request) yourself? That would be nice.

Thanks

**Comment by songjiqiang** [comment]
Ok, I will not create PR by myself for the time being. I will upgrade it after your official repair. At present, I temporarily solve this problem by changing the source code.
thank you

**Comment by songjiqiang** [comment]
If frozenColumn is set to 0, this judgment is problematic.For example, if(0) is actually false, then the judgment logic should be deleted, Please check the screenshot of my question, thank you
![图片](https://user-images.githubusercontent.com/28054996/65155671-458b8d80-da60-11e9-86e9-41e3c8df5285.png)

**Comment by ghiscoding** [comment]
oh damn I didn't catch that since you didn't mention it earlier. I'll fix that later today.

**Comment by songjiqiang** [comment]
Ok, thank you. I took a screenshot of this question in the comments yesterday. Thank you
![image](https://user-images.githubusercontent.com/28054996/65156838-550bd600-da62-11e9-93c5-cad908e479aa.png)

**Comment by ghiscoding** [comment]
I raised another PR, removing `frozenColumn` is not ideal the property might not exist. What is best to use `hasOwnProperty('frozenColumn')` and that is what I changed in new PR.

**Comment by songjiqiang** [comment]
OK, you can also solve it in the following way, && _gridOptions.frozenColumn ! = = undefined

**Comment by ghiscoding** [comment]
I already did another PR #439

**Comment by songjiqiang** [comment]
OK，thanks
