### ISSUE TITLE
When the frozen column width is less than 34px, the data rows are not aligned

### ISSUE THREAD

**Issue by songjiqiang** [6pac/SlickGrid#442]
When using frozen columns, when the frozen column width is less than 34px and the data row scrolls to the bottom, the data row is not aligned (frozen column row and non-frozen column row are not aligned).
![图片](https://user-images.githubusercontent.com/28054996/65298308-98b72a80-db9d-11e9-9226-440dcb764ee3.png)

**Comment by ghiscoding** [comment]
If you know how to fix then please go ahead and create a PR (Pull Request), if not I would say this is a really low priority since it would be really rare to use it below 34px wide.

**Comment by songjiqiang** [comment]
Because my grid only needs to freeze the check box column, and the default width of the check box column is 30px, this problem arises in this scenario.

Okay, for the time being, I'll solve this problem by adjusting the width of the frozen column to ensure that the minimum width of the frozen column is greater than or equal to 34px.

**Comment by ghiscoding** [comment]
After re-reading your issue, I see what you mean. The default width is set [here](https://github.com/6pac/SlickGrid/blob/master/plugins/slick.checkboxselectcolumn.js#L21) to `30px` but you can change this width as an option. So you can easily fix this with following code
```js
checkboxSelector = new Slick.CheckboxSelectColumn({
    cssClass: "slick-cell-checkboxsel",
    width: 34
  });
```

**Comment by songjiqiang** [comment]
Yes, that's what I did. I've solved the problem. Thank you
