### ISSUE TITLE
JQuery and JQuery UI compatibility issues

### ISSUE THREAD

**Issue by kienerj** [6pac/SlickGrid#444]
I'm using an autocomplete editor according to [this example](https://6pac.github.io/SlickGrid/examples/example-autocomplete-editor.html). 

However there is a known incompatibility between jquery 3 and jquery-ui 1.11 making this not work properly (error in console + the drop down is displayed at the wrong place). The suggested fix is to use ui 1.12. However ui 1.12 is incompatible with slick grid itself:

`jquery-3.4.1.min.js:2 Uncaught Error: SlickGrid's 'enableColumnReorder = true' option requires jquery-ui.sortable module to be loaded
    at init (slick.grid.js:347)
    at new SlickGrid (slick.grid.js:5874)
    at HTMLDocument.<anonymous> (my.js:251)
    at e (jquery-3.4.1.min.js:2)
    at t (jquery-3.4.1.min.js:2)`

This means for this example to work one is forced to remain on old version of both dependencies. it works ok with jquery 2.2.4 and ui 1.11.3.

Suggested fix would be to make slickgrid compatible with jquery-ui 1.12.

**Comment by 6pac** [comment]
Ah, I hadn't realised 1.12 had been released. Been living under a rock, clearly.

Before I get too excited, are you sure you (or the person you got the build from) haven't just excluded ```sortable``` from the jQueryUI build using the download builder tool?

**Comment by ghiscoding** [comment]
> This means for this example to work one is forced to remain on old version of both dependencies. it works ok with jquery 2.2.4 and ui 1.11.3.

That's not totally true, I use the jQuery UI Autocomplete in [Angular-Slickgrid](https://github.com/ghiscoding/Angular-Slickgrid) repo (which is a wrapper on top of SlickGrid) and it works without any issues, you can see this [example](https://ghiscoding.github.io/Angular-Slickgrid/#/editor)

However please note that I did not use any of the code from the [example](https://6pac.github.io/SlickGrid/examples/example-autocomplete-editor.html) mentioned, I just went on jQuery UI [Autocomplete](https://jqueryui.com/autocomplete/) and followed their code... all that to say, it's probably just the example that might have some code to fix (SlickGrid lib itself is totally fine as I demoed bellow). 

Here's a demo 
![2019-10-09_09-44-33](https://user-images.githubusercontent.com/643976/66486899-70726b80-ea79-11e9-8984-7706bf26a04b.gif)

**Comment by 6pac** [comment]
To reiterate my comment, which fits in with @ghiscoding 's comments, there is a download builder page for jQueryUI where you can include or exclude different modules so as to target just your project's needs and keep build size small. It looks to me as if there is not a problem with 1.12, it's just that you've excluded the ```sortable``` module from the build.

**Comment by ghiscoding** [comment]
I will reiterate again, it works in my lib and I use last jQuery UI from NPM. You probably just need to do some tweaking to fix the example. 

Here's the NPM packages I use
```json
"jquery": ">=3.2.1",
"jquery-ui-dist": "^1.12.1",
```
The example that you showed is still using an old version of jQuery `jquery-1.11.2` which you will need to upgrade so that you can use latest jQuery UI version (there are some version compatibility issues). Again there might be other code changes to apply but the grid core library is totally fine.

**Comment by kienerj** [comment]
Ok. Then I vouch to update the examples so the arw compatible with new versions of jquery and jquery-ui.Am 10.10.2019 15:38 schrieb "Ghislain B." <notifications@github.com>:I will reiterate again, it works in my lib and I use last jQuery UI from NPM. You probably just need to do some tweaking to fix the example.
Here's the NPM packages I use
"jquery": ">=3.2.1",
"jquery-ui-dist": "^1.12.1",
The example that you showed is still using an old version of jQuery jquery-1.11.2 which you will need to upgrade so that you can use latest jQuery UI version (there are some version compatibility issues). Again there might be other code changes to apply but the grid core library is totally fine.

**Comment by 6pac** [comment]
Note that these changes won't propagate to the online examples (github.io) until the next formal release. Also note that 1.12.4 should be the same as the latest 3.x, but it just supports a wider range of browsers.

**Comment by 6pac** [comment]
Doesn't seem to be registering, but I updated all the examples to the latest jQuery and jQueryUI
