### ISSUE TITLE
autosizeColumns issue 

### ISSUE THREAD

**Issue by mayankgirdhar** [6pac/SlickGrid#450]
Hey am getting error sometimes while am trying to use autosizeColumns

Uncaught TypeError: Cannot read property '<Column_Name>' of undefined

I found a solution we have to initialize maxIndex with 0 in slickgrid.grid.js at line number 2347 and 2361.

Please update it as soon as possible 
Thanks in advance

**Comment by 6pac** [comment]
Could you please give me some more information, such as the line number and exact message in the error?
```maxIndex ``` is not used in the code segment at line 2347, and it *is* initialised to 0 in line 2361.

**Comment by 6pac** [comment]
ah. Just looked at your PR, and the code is quite different to the latest version. so quite possibly you are using the latest release, and I haven't updated lately.

Just released 2.4.15, try that.

**Comment by ghiscoding** [comment]
It might have been fixed in this [commit](https://github.com/6pac/SlickGrid/commit/d2eaba8752b993d0a905b89df678dcd54902ebb7)
