### ISSUE TITLE
Is it possible to use SlickGrid with Django Python?

### ISSUE THREAD

**Issue by jdreithel** [6pac/SlickGrid#451]
I've begun trying to implement SlickGrid into a Django Python web applicaiton. I've been able to get it work properly when I do a simple html project in a separate folder but whenever I try and use it within a Django Python project none of the references to the JS and CSS files work. I was curious if anyone had used it in a Python project before with success. Looking for any and all feedback, thanks.

**Comment by jdreithel** [comment]
Ended up figuring it out, needed to change css/js file locations into a Static folder for each type respectively and then reference properly within the html pages using proper static references.

**Comment by ghiscoding** [comment]
so this issue can be closed then?
