### ISSUE TITLE
Add jquery.event.drag as a dependency

### ISSUE THREAD

**Issue by jsmorris** [6pac/SlickGrid#461]
In slick.grid.js, there is this code:

```javascript
if (!jQuery.fn.drag) {
  throw new Error("SlickGrid requires jquery.event.drag module to be loaded");
}
```
Shouldn't slickgrid have a dependency in its package.json on this library?

**Comment by 6pac** [comment]
Slickgrid uses ```jquery.event.drag-2.3.0.js``` and ```jquery.event.drop-2.3.0.js```, originally from ThreeDubMedia (in the lib folder). These are packaged with the grid, however as they are no longer supported externally. The release version was 2.2, but we upgraded them ourselves to be compatible with jQuery 2 and 3, so version 2.3 is our custom release version only.

I note there's also

**Comment by jsmorris** [comment]
I will use the included libraries. Thanks.
