### ISSUE TITLE
Pasting multiple rows, including empty rows, causes rows with values ​​to be aggregated at the top

### ISSUE THREAD

**Issue by Ischca** [6pac/SlickGrid#463]
Copying and pasting multiple cells with empty and non-empty cells changes the order of the cells.
This happens when only one column is copied.

### Steps to Reproduce
1. Empty any cell
1. Select one column with multiple rows containing empty cells
1. Paste in any column

https://6pac.github.io/SlickGrid/examples/example-excel-compatible-spreadsheet.html

**Comment by 6pac** [comment]
thanks for reporting, this was a typo bug.
