### ISSUE TITLE
Multiple column sorting using dataview

### ISSUE THREAD

**Issue by durdenk** [6pac/SlickGrid#469]
I tried to use below example to achieve multiple column sorting using dataview. I am having "args.sortCol.field not defined" error. I think when its multi column sort, we have args.sortCols variable.
Does this example work?

```
grid.onSort.subscribe(function(e, args) {
  var comparer = function(a, b) {
    return (a[args.sortCol.field] > b[args.sortCol.field]) ? 1 : -1;
  }
  dataView.sort(comparer, args.sortAsc);
});
```

**Comment by ghiscoding** [comment]
You should refer to the following 2 examples for SlickGrid with multi-sort
- [Multi Column Sort](https://6pac.github.io/SlickGrid/examples/example-multi-column-sort.html)
- [Multi Column TriState Numbered Sort](https://6pac.github.io/SlickGrid/examples/example-multi-column-tristate-numbered-sort.html)
