### ISSUE TITLE
Error when using with jquery 3.1.0

### ISSUE THREAD

**Issue by mpGitHub** [6pac/SlickGrid#47]
I'm getting an error when using with the latest version of jquery 3.1.0 with the latest version of slickgrid 2.3.2.

I get an exception in jquery.event.drag-2.2.js on fixHooks not being defined.  It looks like this is not present in jquery 3.1.0???  Everything works fine if I use an earlier version of jquery.

Error: is Uncaught TypeError: Cannot set property 'touchcancel' of undefined.
<pre>
// event fix hooks for touch events...
var touchHooks = 
$event.fixHooks.touchstart = 
$event.fixHooks.touchmove = 
$event.fixHooks.touchend =
$event.fixHooks.touchcancel = {
	props: "clientX clientY pageX pageY screenX screenY".split( " " ),
	filter: function( event, orig ) {

</pre>

**Comment by 6pac** [comment]
could you post a simple test page? we tested with all the standard examples, including row-reorder which has drag and drop. looks like you've caught something we missed.

**Comment by jdtemple** [comment]
I thought I'd chime in that I'm having the same problem. I have a client's website that uses quite a few SlickGrid components and was forced to downgrade jquery to avoid this error. I am on Michael Leibman's code, version 2.2. If there's a viable update I can get without having to spend a bunch of time and money switching to another grid product, I'd sure like to.

Rolling back to jquery 2.2.3 avoids the problem.

**Comment by 6pac** [comment]
Can I reiterate that I'd like a sample? It's hard to fix the problem if I don't have a test case. All the standard examples work just fine.

**Comment by jdtemple** [comment]
Let me see what I can do. I can't promise anything because I don't know how much time I am able to devote to it.

**Comment by jdtemple** [comment]
It was easier than I thought it would be. I didn't have to even set up any grids; just set up the script bundles and load a stock MVC project site.

[https://github.com/jdtemple/SlickGridTester](https://github.com/jdtemple/SlickGridTester)

**Comment by 6pac** [comment]
Whoops. that's a bit embarrasingly simple :-) 
My dev env for Slickgrid is just a local copy of the repo. But i suppose there are a million ways to integrate that with server side stuff.
Anyway, I have some fully blown MVC sites in my dev setup, I'll try your sample and them too.

**Comment by jdtemple** [comment]
Awesome. Thanks! Once it's verified working, I'll switch my project over to use your SlickGrid and the latest jquery.

**Comment by 6pac** [comment]
OK, doubly embarrasing. I should have caught this one on reading the first comment.

The jquery.event.drag and .drop files have been updated to 2.3.0 along with the updates to slickgrid. They are in the latest repo.
I need somewhere to advertise this fact, but the logical thing is to duplicate MLeibman's docs and update them all. Then we'll have a complete set of updated docs. Will hopefully get to this soon. Meanwhile I'll post it on the Readme and the wiki.

**Comment by jdtemple** [comment]
I was able to get everything switched over to your repo from mleibman's on jquery 3.1.0 and deployed. Thanks for your help!
