### ISSUE TITLE
Expanding frozen columns outside the viewport makes scrolling impossible

### ISSUE THREAD

**Issue by snickdavis** [6pac/SlickGrid#473]
If frozen columns are enabled on the slickGrid configuration with no max width defined for the columns, it become possible to expand the frozen columns to a width greater than the viewport. In doing so, scrolling doesn't become enabled for the whole grid, and becomes unusable.

This can be replicated on the example for frozen columns found here: [http://6pac.github.io/SlickGrid/examples/example-frozen-columns.html](http://6pac.github.io/SlickGrid/examples/example-frozen-columns.html)

**Comment by ghiscoding** [comment]
We welcome any possible fixes through PR (Pull Request)

**Comment by ghiscoding** [comment]
@snickdavis this is now fixed and merged via PR #607, I also added `frozenRightViewportMinWidth` (default to 100) which you can configure to keep the minimum width to keep for the right section of the frozen grid.
