### ISSUE TITLE
Group sort is done before totals

### ISSUE THREAD

**Issue by ataft** [6pac/SlickGrid#486]
Group aggregation/totals should be computed before sorting is done because the sort function may want to use the totals. As you can see in the code, groups are sorted in `extractGroups()` [here](https://github.com/6pac/SlickGrid/blob/master/slick.dataview.js#L656), which happens before the totals are computed [here](https://github.com/6pac/SlickGrid/blob/master/slick.dataview.js#L1000).

Can I make a PR to simply move the `addTotals()` call before `sort()`?

**Comment by ghiscoding** [comment]
@ataft 
It seems that 6pac is busy these days but I guess it would make sense to fix any such issues. Would you be able to do a before/after print screen showing the issue? It's easier to understand when visually seeing the issue.

**Comment by ataft** [comment]
In the following screen print, "Gold Medals" is sorted ascending and works find for the detail rows, but it is not sorted by the group totals:
![image](https://user-images.githubusercontent.com/11670864/80540718-b1bb6180-895e-11ea-8169-efafc3721474.png)

You have to compute totals prior to sorting so that the grouping definition `comparer: function(a, b)` has access to these totals. For example, I should be able to access `a.totals.total['Gold Medals']`. Then you can properly sort both the detail and group levels, like this:
![image](https://user-images.githubusercontent.com/11670864/80541121-7705f900-895f-11ea-91ba-70d4db69462c.png)

I'll make a PR so you can see the code too. It's a simple no-brainer change.

**Comment by ghiscoding** [comment]
@ataft 
Side note, your PR is now merged

**Comment by ghiscoding** [comment]
@ataft can we close this issue since your PR got merged and we released a new version on NPM already?
