### ISSUE TITLE
Grid menu is shown partially on the left side of the screen when ENTER key is pressed while Grid Menu icon is in focus

### ISSUE THREAD

**Issue by yazhiniHariharan3** [6pac/SlickGrid#490]
I am submitting a BUG report 

**Description** 
When the focus is on the grid menu and the user hits the ENTER button in the keyboard, the Grid menu appears on the left side of the screen. 

**Expected Behavior**
The grid menu should open up in the screen and not at the left side. 

**Current Behavior**
When we hit enter key with focus on the grid menu, the menu shows up on Left side of the screen. The shown menu is ONLY partially visible.

The bug is reproducible in this [page](https://6pac.github.io/SlickGrid/examples/example-grid-menu.html)

![image](https://user-images.githubusercontent.com/18120900/81308518-7d068300-909f-11ea-90cf-18d421129ce6.png)

**Comment by ghiscoding** [comment]
Angular-Slickgrid [issue](https://github.com/ghiscoding/Angular-Slickgrid/issues/447) reference. The Grid Menu gets positioned on this [line](https://github.com/6pac/SlickGrid/blob/master/controls/slick.gridmenu.js#L382) there's probably some code refactoring to do for supporting a keyboard event
