### ISSUE TITLE
resizeCanvas() does not take into account the preHeader height

### ISSUE THREAD

**Issue by xavier-90** [6pac/SlickGrid#493]
I have created a grid with the wollowing options:
```
                        autoEdit: false,
                        editorCellNavOnLRKeys: true,
                        enableAutoResize: true,
                        enableCellNavigation: true,
                        enableColumnReorder: false,
                        enableGrouping: false,
                        frozenColumn: 0,
                        createPreHeaderPanel: true,
                        editable: true,
                        explicitInitialization: true,
                        preHeaderPanelHeight: 25,
                        showPreHeaderPanel: true,
                        autoResize: {
                        containerId: $('#MyGrid')

```
On calling resizeCanavas(), e.g. 
```
                         $(window).resize(function () {
                             grid.resizeCanvas();
                         });

```
the height of the grid is reduced by 25px.

**Comment by ghiscoding** [comment]
Can you try to modify the `slick.grid.js` file and the `resizeCanvas` on [line 3449](https://github.com/6pac/SlickGrid/blob/master/slick.grid.js#L3449) on your side with the following changes and see if that is enough? I don't fully know how to test it, so I would rather you confirm the change works as you intend it.

```diff
function resizeCanvas() {
      if (!initialized) { return; }
      paneTopH = 0;
      paneBottomH = 0;
      viewportTopH = 0;
      viewportBottomH = 0;
+      var preHeaderHeight = options.preHeaderPanelHeight || 0;

  //-- ... code removed for brevity --//

      // The top pane includes the top panel and the header row
+      paneTopH += topPanelH + preHeaderHeight + headerRowH + footerRowH;

      if (hasFrozenColumns() && options.autoHeight) {
        paneTopH += scrollbarDimensions.height;
      }

      // The top viewport does not contain the top panel or header row
+      viewportTopH = paneTopH - topPanelH - preHeaderHeight - headerRowH - footerRowH;
```

**Comment by xavier-90** [comment]
I had to make a minor mods for it to work correctly in my scenario (inside a flex grow column height 100%): The viewportTopH does no need to be included in the preHeaderHeight.

Also made a change to take into account the showPreHeaderPanel value.

```
function resizeCanvas() {
      if (!initialized) { return; }
      paneTopH = 0;
      paneBottomH = 0;
      viewportTopH = 0;
      viewportBottomH = 0;
+      var preHeaderHeight = (options.createPreHeaderPanel && options.showPreHeaderPanel) ? (options.preHeaderPanelHeight || 0) : 0;

  //-- ... code removed for brevity --//

      // The top pane includes the top panel and the header row
+      paneTopH += topPanelH + preHeaderHeight + headerRowH + footerRowH;

      if (hasFrozenColumns() && options.autoHeight) {
        paneTopH += scrollbarDimensions.height;
      }

      // The top viewport does not contain the top panel or header row
      viewportTopH = paneTopH - topPanelH - headerRowH - footerRowH;

```

**Comment by ghiscoding** [comment]
Great thanks for the confirmation, I updated the PR #497 and tested locally too with the auto-resize example, removing that last line doesn't have any impact. Again thanks for confirming.

**Comment by ghiscoding** [comment]
@xavier-90 
So I'm not sure why you said that the 2nd line didn't need the `preHeaderHeight` in the calculation, it really does need it. I found out that adding it only to the first calculation broke my resize in Angular-Slickgrid. So I will have to put back 2nd line.

New behavior 

![image](https://user-images.githubusercontent.com/643976/82492936-12007780-9ab5-11ea-8bab-de8df012c210.png)

When I put back the calculation that I wrote earlier, it fixes my issue
```diff
// The top viewport does not contain the top panel or header row
+ viewportTopH = paneTopH - topPanelH - preHeaderHeight - headerRowH - footerRowH;
```

After that the grid resize is correct

![image](https://user-images.githubusercontent.com/643976/82493040-4bd17e00-9ab5-11ea-8882-a57756fc3fa8.png)


... So I have no choice but to add that line back, since I see that all grids that have a Pre-Header (dragging grouping, column grouping)... is now broken.

**Comment by xavier-90** [comment]
I have done further tests and found that I was actually “barking at the wrong tree”. The issue is with the resizer: If setting the resizer bottom padding to 0 then the grid is rendered with a bottom padding of 20px (the default).
I have logged this as [#504](https://github.com/6pac/SlickGrid/issues/504)

**Comment by ghiscoding** [comment]
ok let's close this issue, the rollback PR was merged, let's discuss it further in the other issue #504
