### ISSUE TITLE
Ability to change multiple column width in one operation

### ISSUE THREAD

**Issue by xavier-90** [6pac/SlickGrid#498]
In some use cases, one may want to offer the ability to resize column width but also ensure that all column width of the same type retain the same width ("linked column width").
I have achieved this by adding an onBeforeColumnsResized event listener in slick.grid.js.
The changes are only applied if the listener returns true.
This could also cover other use cases, e.g. the ability to resize a column within the constraint of an overall grid width.
If you wish to incorporate this feature, the modifications are as follows:

Line 1821:

```diff
	function setupColumnResize() {

	//-- ... code removed for brevity --//
	
            if (options.syncColumnCellResize) {
              applyColumnWidths();
            }
          })
          .on("dragend", function (e, dd) {
+           var triggeredByColumn = $(this).parent().attr("id").replace(uid, "");
+           $(this).parent().removeClass("slick-header-column-active");
+           if (trigger(self.onBeforeColumnsResized, { triggeredByColumn: triggeredByColumn }) === true) {
+             applyColumnHeaderWidths();
+             applyColumnGroupHeaderWidths();
+           }
            var newWidth;
-           // $(this).parent().removeClass("slick-header-column-active");
            for (j = 0; j < columns.length; j++) {
              c = columns[j];
              newWidth = $(columnElements[j]).outerWidth();
              if (c.previousWidth !== newWidth && c.rerenderOnResize) {
                invalidateAllRows();
              }
            }
            updateCanvasWidth(true);
            render();
-           // trigger(self.onColumnsResized, {triggeredByColumn: $(this).parent().attr("id").replace(uid, "")});
+           trigger(self.onColumnsResized, { triggeredByColumn: triggeredByColumn });
            setTimeout(function () { columnResizeDragging = false; }, 300);
          });
      });
    }

```

Line 5798:

```diff
      "onViewportChanged": new Slick.Event(),
+     "onBeforeColumnsResized": new Slick.Event(),
      "onColumnsReordered": new Slick.Event(),

```

An example usage:

```
	grid.onBeforeColumnsResized.subscribe(function (e, args) {
		let grid = args.grid,
			columns = grid.getColumns(),
			newWidth = 0,
			isStdColumn = undefined;
		// Get the column width change
		for (let i = 0; i < columns.length; i++) {
			if (columns[i].width != columns[i].previousWidth) {
				newWidth = columns[i].width - 2;
				isStdColumn = columns[i].columnType == 'STANDARD';
				break;
			}
		}
		if (isStdColumn) {
			return false; // Column not "linked" so carry on as normal
		} else {
			// "Linked" column so alter the width of all linked columns
			columns.forEach(function (column) {
				if (column.resizable && column.columnType != 'STANDARD') {
					column.width = newWidth;
				}
			});
			return true;
		}
	});

```

**Comment by ghiscoding** [comment]
You can prefix your code with ` ```diff ` to show differences, I've updated your comment with it. 

I think we could add the new `onBeforeColumnsResized` event but changing the `triggeredByColumn` is a little bit riskier. We try not to change the core lib as much as possible.

**Comment by 6pac** [comment]
I'm not really that keen on adding this to core. It might be a good plugin. It's quite a specific use case. 
I'd also advocate that the ```columnType``` be empty/null/undefined for standard columns and an arbitrary string for linked columns.  That way you could have multiple types of linked column - some of the columns could be linked as 'DateTime' and others as 'Totals', for example.

**Comment by xavier-90** [comment]
Thanks for the tip re. highlighting differences.

In answer to your specific points:

- I haven't changed _triggeredByColumn_ but simply moved it into a variable at the top since it would be used in 2 separate lines in the code.
- The use of the _columnType_ property in _onBeforeColumnsResized_ is just an example. Users are free to declare any properties in the column meta object. I am not proposing that _columnType_ should become a standard property.

I understand the desire to minimise any changes to the core code, tinkering with the foundation is a dangerous thing to do but in this particular case...

- The proposed code change is small and in my view minimises risk to the stability of the core code
- The proposed code change is for the introduction an additional listener that is generic in nature.
- I suspect that creating a plugin as an alternative would most probably involve repeating many of the existing code already in use in core, future maintenance could become a challenge in itself.

Although a seasoned developer, I have yet to contribute to GitHub. I intend to create a PR & some E2E tests but please bear with me re. timeline...

**Comment by 6pac** [comment]
You are correct. I have pushed your code to the repo, it will be in the next release. The only difference is I have called the event ````onBeforeColumnsResize``` rather then ```onBeforeColumnsResized```

**Comment by xavier-90** [comment]
Thank you for this. I have since progressed with my implementation and wanted to dynamically synchronize the width of the corresponding preheader columns whilst the user is dragging a column. I have added another proposed addition to achieve this as ["issue" 509](https://github.com/6pac/SlickGrid/issues/509).
