### ISSUE TITLE
Cleanup some old backup files

### ISSUE THREAD

**Issue by ghiscoding** [6pac/SlickGrid#499]
@6pac 
I opened my `node_modules` (NPM) folder of SlickGrid and I see a bunch of files that are probably just backup files that were potentially forgotten? Basically I'm talking about all the highlighted files, can we do some cleanup there? Actually what's funny is that a bunch of them aren't actually part of the fork, could they be copies on your local when you run your script? I could add some of them in the `.npmignore` so that they don't get included (like the NuGet file which isn't relevant with NPM). 

![image](https://user-images.githubusercontent.com/643976/82237841-4b45b580-9904-11ea-9ac6-4b32370afd07.png)

**Comment by 6pac** [comment]
OK, these are file I have in the root folder of the Slickgrid master, but they are not in Git hence not in the repo. They must be being detected by npm. I've deleted most of them, if you could add the .nuspec file and *.exe and *.pdb to the ignore list that would be great (theres an exe and a pdb file in there also which are my release scripts, but they don't appear in your list so perhaps they are already ignored).
