### ISSUE TITLE
Clear Items for slick.dataview

### ISSUE THREAD

**Issue by GreggGut** [6pac/SlickGrid#50]
(This is more of a feature request than an issue.)

I think it would be useful to have a clear all for the dataview module.
The use case here would be if you want to remove and replace all of the items in the table. Currently you have to do it one by one using the deleteItem(id) method. Having a clearItems() method would be much more efficient and clearer.

If you think it fits within the scope of this project I can create a pull request with my changes.

**Comment by 6pac** [comment]
There are a couple of options: setItems() sets the data object, which could be new and empty. Alternatively, you could just create a whole new DataView and set the grid to refer to that.
You are correct, however, if you wish to leave the existing objects. It might be a good addition.

I have a different data object I use with my grid, so I don't actually use DataView that much,

**Comment by GreggGut** [comment]
Thanks, setItems() will work great! I'm not sure how I missed it :)!
