### ISSUE TITLE
Change request: Additional onColumnsDrag event 

### ISSUE THREAD

**Issue by xavier-90** [6pac/SlickGrid#509]
In my implementation I am using a preheader and would like to synchronize the width of the corresponding preheader columns when the user is dragging a column. All that would be required is an additional event (minimal change) in slick.grid.js, function setupColumnResize() at the end of the "ondrag":

Proposed code modification:
```diff
            .on("drag", function (e, dd) {
            // ... Existing code removed for readability
            applyColumnGroupHeaderWidths();
            if (options.syncColumnCellResize) {
              applyColumnWidths();
            }
+           trigger(self.onColumnsDrag, { triggeredByColumn: $(this).parent().attr("id").replace(uid, ""), resizeHandle: $(this) });
            })
            .on("dragend", function (e, dd) {
            // ... Existing code removed for readability
```
With a new event:
```diff
+              "onColumnsDrag": new Slick.Event(),
```

**Comment by 6pac** [comment]
Done. Was going to add other events around dragging too, but I notice they are already there...

**Comment by 6pac** [comment]
These changes are in the repo but I haven't done a specific release for them, they will be included in the next one whenever it comes out.

**Comment by xavier-90** [comment]
Thanks, looking forward to reverting my code to the vanilla version.
