### ISSUE TITLE
Grunt deployment issues when date editor has image url hard-coded

### ISSUE THREAD

**Issue by aparmar** [6pac/SlickGrid#51]
I suggest we remove that and put it in the css, like so:

```
.ui-datepicker-trigger {
  background:url("../images/calendar.gif") top left no-repeat;
  width: 16px;
  height: 16px;
}
```

The  button image line can then be removed from the slick.editos.js

Some more context: If it is in the JS file, and you run grunt (where files get moved around), then it will point to the wrong url. The CSS files on the other hand, will likely need to get fixed to account for images moving around.  I do that through grunt search and replace (suspect other folks may be doing that too).

**Comment by 6pac** [comment]
good idea. away at the moment, will fix this on Oct 12th.

**Comment by 6pac** [comment]
done
