### ISSUE TITLE
Stucked in the grid using keyboard navigation when the cells are not editable

### ISSUE THREAD

**Issue by bblwq** [6pac/SlickGrid#511]
Browser: Chrome 80.0.3987.87
Screen Reader: NVDA 2020.1

How to Reproduce the Issue:
1. Open [this example](http://6pac.github.io/SlickGrid/examples/example1-simple.html) with Chrome.
2. Open NVDA Screen Reader and click any cell.
3. The screen reader reads the cell when you mouse over it, but not when you tab over it.

**Comment by 6pac** [comment]
Thanks for the report, @bblwq 

Is it resolved, or why did you close it? I apologise for our slow reaction time, it just depends how busy we are and how directly it relates to our core goals. While we'd like to support screen readers, it's a big feature and I don't think we have the resources to tackle it right now. However we are always happy to accept pull requests.
