### ISSUE TITLE
Group Expand broken after Collapse All

### ISSUE THREAD

**Issue by ataft** [6pac/SlickGrid#512]
After calling dataView.collapseAllGroups(), expand no longer works on Level 2 group items. In the example below, which uses http://6pac.github.io/SlickGrid/examples/example-grouping.html, I click on "Group by duration then effort driven", then "Collapse All Groups", then try to expand Effort Driven and cannot.

![slickgrid_groupbug](https://user-images.githubusercontent.com/11670864/84093281-a4a67f00-a9ae-11ea-86f9-b8ae7c017252.gif)

I tried to figure out what was causing this issue, but could not fix it. I did isolate it to the `toggledGroupsByLevel` variable in slick.dataview.js, which does not appear to be set properly after calling collapseAllGroups().

**Comment by timclutton** [comment]
Just encountered this issue myself.

A possible fix seems to be simply changing `addTotals(groups)` to `addTotals(groups, level)` at [`slick.dataview.js:657`](https://github.com/6pac/SlickGrid/blob/77f0d384cfcb7a5111fd909eb7aeb86a7aa6fe18/slick.dataview.js#L657).

**Comment by ghiscoding** [comment]
@ataft could you try this patch and possible make a PR?

**Comment by ghiscoding** [comment]
So I rollback last few PRs and I could confirmed that the bug started after PR #487 in which @ataft moved the location of the method `addTotals(groups)`, the issue seems to be that at that location in the code, the `level` is also a required 2nd argument for that method to work properly as pointed out by @timclutton (thanks for that)... so I created PR #516 which fixes this issue.

**Comment by Anilima** [comment]
@ghiscoding , This is so wonderful. You saved my day. I pulled the library from git and the expand collapse works fine now. How much time does it take for the npm to be updated?

**Comment by ghiscoding** [comment]
I'm not the one who's making releases (6pac is), you need to be patient...

**Comment by 6pac** [comment]
Sorry all, meant to do this about 12 hour ago, got distracted ...

**Comment by ataft** [comment]
Doh, I reported a bug that I created. Sorry all. I was out of town for a few days, thanks for fixing!

**Comment by ghiscoding** [comment]
haha yeah it's all good, fixed and released already ;)

**Comment by Anilima** [comment]
Thank you all!! Great support.
