### ISSUE TITLE
Filling the whole window we loose the horizontal scroll

### ISSUE THREAD

**Issue by albu77** [6pac/SlickGrid#515]
Using the demo for Filling the whole window and reducing window size show the horizontal scroll out of it .
![image](https://user-images.githubusercontent.com/624802/85925626-ef266780-b899-11ea-9cc7-587c05aaba6a.png)

**Comment by ghiscoding** [comment]
Just use the Resizer Plugin instead [Example - Auto-Resize](https://6pac.github.io/SlickGrid/examples/example15-auto-resize.html)

**Comment by ghiscoding** [comment]
closed by [f20e5c6](https://github.com/6pac/SlickGrid/commit/f20e5c6b677d41937c483562c1dfa226dcae6480)
