### ISSUE TITLE
Performance Issue with multiple slickgrids on the same page

### ISSUE THREAD

**Issue by anthonydresser** [6pac/SlickGrid#52]
I am currently using the older SlickGrid implementation from the main branch (2.2), however, after looking at the problem and looking at the code difference it appears this would still be a problem with the latest version (this fork is also more active).

Essentially the problem is that having 15+ slick grids on the same page can make initialization very slow (exponentially/factorially with the number of slickgrids). I've narrowed the problem down to a rendering issue that slickgrid on init is causing the browser to re-render the page multiple times. Therefore, with more grids, this rendering takes significantly longer.

It is similar to this problem mleibman/SlickGrid#383 however, the suggestion to make them asynchronous would not help in this situation. A screen shot of the problem http://imgur.com/5JrnUlg 

You can see that init and getViewport (the root problem) is causing a lot of rerendering. From my understand, according to https://gist.github.com/paulirish/5d52fb081b3570c81e3a, this is most likely caused by the fact that getviewport is calling div properties a lot, which causes a rerender on the browser each time (thus why this problem can't be solved by an async).

I've sort of worked around this problem by implementing a virtual scrolling type system where only the grids in view get rendered, but the problem is the browser slightly freezes when it gets in the range of rendering a new grid.

My question: is there a good way to work around this problem? My initial idea is to somewhere cache the viewport height and reuse it for each grid (since each grid is guaranteed to be the same size on my webpage), however I don't see a good way of doing this without modifying the slickgrid library itself. Is this a problem someone else has solved?

**Comment by 6pac** [comment]
OK, so have you tried the ['40 grids on a page'](https://github.com/6pac/SlickGrid/blob/master/tests/40%20grids%20on%20a%20page%20test.html) test? Have you checked out [dynamic creation of grids?](http://6pac.github.io/SlickGrid/examples/example-dynamic-filtered-with-jquery-tabs.html)

This re-rendering doesn't sound like Chrome - you need to tell us what the browser type and version is.

**Comment by 6pac** [comment]
I note http://6pac.github.io/SlickGrid/tests/40%20grids%20on%20a%20page%20test.html loads in 1.8 seconds in Chrome for me.
When I turn on profiling it hangs. Perhaps this is an artifact of the profiling?

**Comment by anthonydresser** [comment]
I'll need to take a closer look at that 40 grids test as it is significantly faster in loading than my 15 grid test.

I'm testing on Chrome Version 53.0.2785.101 (64-bit)

**Comment by anthonydresser** [comment]
So I've done some closer look at the call stacks for slick grid init. Here are come captures from the callstack of my application on the init of the 40th grid compared to the SlickGrid test on the 40th grid. 

[Mine](http://imgur.com/Xthq8JI)
[SlickGrid Test](http://imgur.com/a/EFBqX)

As you can see there is a significant difference in the time required to perform the init, and almost all the bottleneck comes from jquery forcing style recalcs.

I'm assuming reason the time difference is so great is just because my page consists of more than just the grids (it's part of an angular2 app) and therefore recalculating the app takes longer. Perhaps I need to look at simplifying everything on my application to increase performance, but my question is: is there a way to avoid alot of this recalculation from the slickgrid that it is re-performing for each grid even though each grid will be the exact same height in my scenario or is there another reason why this might be happening?

**Comment by 6pac** [comment]
firstly, what version of jQuery are you using?

also, i've never used Angular, but that's by choice, because i've been afraid of the auto-magic re-rendering functions doing exactly this. i've heard anecdotally of web pages becoming unmanageable under Angular just through complexity, not even with a grid. these things tend to follow an order n^2 rule, so it gets ugly quickly. apparently angular 3 has improved the situation, but again i have no direct experience, and i don't know what version you're using.

**Comment by anthonydresser** [comment]
I've tried with both JQuery 1.11 (which is the version the 40 grid test uses) and with JQuery 1.7.

**Comment by 6pac** [comment]
Any progress? It would be interesting to remove angular altogether and see what happens to performance. If that's even possible.

**Comment by anthonydresser** [comment]
Unfortunately, the page is pretty hooked into angular, so removing angular would basically be rebuilding the entire page. For now I've just implemented a semi-virtual scrolling system and just kind of have to deal with the ui lockup when a new grid is rendered.

I might look into simplifying the DOM and css at some point to see if I can get any significant performance increase from that.

Thanks for the help with this issue.
