### ISSUE TITLE
Column sizing is not documented properly 

### ISSUE THREAD

**Issue by evlquaker** [6pac/SlickGrid#526]
Hi,
I noticed on the page https://github.com/6pac/SlickGrid/wiki/Auto-Column-Sizing legacy column sizing is specified as:
autosizeColsMode: Slick.GridAutosizeColsMode.Legacy
it should be autosizeColsMode: Slick.GridAutosizeColsMode.LegacyForceFit

**Comment by ghiscoding** [comment]
You're just saying the option name is incorrect right? The full list of available options is [here](https://github.com/6pac/SlickGrid/blob/master/slick.core.js#L49) in the `slick.core.js` file.

**Comment by evlquaker** [comment]
Correct, just the documentation is incorrect. It took me a minute to figure it out. Thanks for writing back

**Comment by ghiscoding** [comment]
I'm not sure if you want to wait for @6pac or simply update it yourself, we don't say it out loud but any user can edit the Wikis

**Comment by 6pac** [comment]
thanks. there are possibly a few discrepancies. I need to feed back some other fixes from my personal repo too, I think, to make the auto-sizing work more smoothly.

**Comment by ghiscoding** [comment]
I've updated the docs, it should be good now so let's close the issue
