### ISSUE TITLE
Can't find the moving row example?

### ISSUE THREAD

**Issue by songjiqiang** [6pac/SlickGrid#531]
Can't find the moving row example?

**Comment by ghiscoding** [comment]
It's in the [Examples](https://github.com/6pac/SlickGrid/wiki/Examples) Wiki but the name is not what you think
- **Row reordering (simple example without delete)**
   - [example9-row-reordering.html](http://6pac.github.io/SlickGrid/examples/example9-row-reordering.html)

and I also did this new one few months ago
- **3 Plugins combo: RowDetail / RowMoveManager / RowMove**
- [example-row-detail-selection-and-move.html](https://6pac.github.io/SlickGrid/examples/example-row-detail-selection-and-move.html)
