### ISSUE TITLE
Are we able to bring this nice to have plugin SlickGantt

### ISSUE THREAD

**Issue by Smilefounder** [6pac/SlickGrid#54]
I found a nice to have plugin here, but don't know how to use it yet... :(
But if we could merge this one to our source then it will be nice 👍 
https://github.com/demsullivan/SlickGantt

**Comment by 6pac** [comment]
Not sure that this one is fully working yet. An example would be nice. But issue #2 on that repo is 'Get Working' and has a list of features that I don't think work yet.

**Comment by 6pac** [comment]
Yep, I put together a basic page using the plugin and it doesn't do anything significant.
