### ISSUE TITLE
remote model documentaion

### ISSUE THREAD

**Issue by kofifus** [6pac/SlickGrid#547]
Hi, Where is the documentation on how to use remote model ? I can't see anything in the wiki ? 
Thanks

**Comment by 6pac** [comment]
Looks like in the grand tradition, there is none. See the examples:
  http://6pac.github.io/SlickGrid/examples/example6-ajax-loading.html

However neither of the Ajax-loading example work - after a few years the third party API they rely on disappears or changes beyond recognition. Needs someone to find a new free working API and rewrite for it.

**Comment by kofifus** [comment]
Thanks! I'm looking at the code and I'm confused about what does `hits` refer to  here:
https://github.com/6pac/6pac.github.io/blob/master/SlickGrid/slick.remotemodel.js#L112

Any help ?

**Comment by 6pac** [comment]
That's part of the return object structure of the octapart API. Here's the reference: https://octopart.com/api/v4/reference#query
- search for 'PartResultSet'. It looks like they have introduces auth tokens, so that's why it's not working.

**Comment by kofifus** [comment]
Thanks! I am trying to understand what does this do:

`data.length = Math.min(parseInt(resp.hits),1000); // limitation of the API`

seems to limit the size of the data .. is that just for the example ? should I take that line off in a real implementation ?
