### ISSUE TITLE
Not so much an issue. More a question: slick.grid.js updateColumnProps - if (!m.resizable)..

### ISSUE THREAD

**Issue by JGFMK** [6pac/SlickGrid#559]
if (!m.resizable) {
          // there is difference between user resizable and autoWidth resizable
          //m.autoSize.autosizeMode = Slick.ColAutosizeMode.Locked;
}

Is there some unfinished business here? If with commented out code...

**Comment by ghiscoding** [comment]
seems like @6pac when he introduced 

![image](https://user-images.githubusercontent.com/643976/100658769-957d0a00-331d-11eb-8480-b9a31a380bf8.png)

**Comment by 6pac** [comment]
I think this can be removed, it's a feature that is still needing a bit of tweaking, so I think I left it in as a memory jogger. Looks like I had it initially assuming that ```!m.resizable``` meant the user wanted a fixed width column, but then realised that it concerns whether the column is user-resizible. So they may want it to be non-user-resizable, but still to have an initial autosize based on the text width.

The autosizing framework does need a bit of developer tweaking of the column autosize options in certain column cases to get good results, so it doesn't always work well in the default 'ContentIntelligent' mode. However, if you don't like it, you can always go back to the old way by using Legacy mode (hint - that does an even worse job!). 

It's not till you try to build it that you realise that autosizing well is pretty hard to automate.

**Comment by ghiscoding** [comment]
that code was removed in the upcoming [v4.0 - Roadmap](https://github.com/6pac/SlickGrid/discussions/743)
