### ISSUE TITLE
Column lazy rendering

### ISSUE THREAD

**Issue by buckelieg** [6pac/SlickGrid#566]
Implement column lazy rendering (just like rows).
Grid gets slow ff the number for columns big (135 in my case)

**Comment by ghiscoding** [comment]
Contributions are welcome, you might be able to do that already with `grid.setColumns(yourColumns)`

**Comment by Rahul7549** [comment]
I am trying to implement the slickgrid  but response value is not  getting fit in table without refreshing the page....
Even response coming for every request....!
what i need to do in order to solve this problem..!

**Comment by 6pac** [comment]
@Rahul7549 - post an issue on StackOverflow and mention which example you are using as a starting point and how you have modified it.

**Comment by ghiscoding** [comment]
we won't be supporting Column Name lazy loading, however our upcoming v4.0 will be written in vanilla JS code and should improve performance, see [Roadmap to v4.0](https://github.com/6pac/SlickGrid/discussions/743)
