### ISSUE TITLE
Discussion: Migration of SlickGrid to TypeScript

### ISSUE THREAD

**Issue by Danielku15** [6pac/SlickGrid#575]
I am following up here the discussion of #572, I think it is worth having an own dedicated issue for that 😉  @6pac @ghiscoding 

It would be worth a consideration to migration SlickGrid to a typescript codebase and try to modernize the codebase by eliminating some dependencies of which some are maybe even unmaintained. 

Some benefits on that: 

- A more modern tech-stack attracts more developers to contribute. Getting new devs bootstrapped and accomodated with the SlickGrid development environment is eaiser this way. 
- Providing libraries for other projects becomes easier (NPM, TypeScript definitions,..)
- Dependency management gets more visible
- Removing jQuery makes it more attractive for new frameworks like Angular, React etc. which usually avoid jQuery. 
- Test infrastructure, documentation etc. is easier to maintain.
- Code quality overall can be improved (TSDoc, TypeSafety, OOP development style, module system compatibility,..)

If there is a strategy in this regards, I could try to prepare a basic infrastructure based on my own project which provides bundling, CI/CD scripts, etc. Or you just peek into my structure as a first idea: 

It might have a bit more than SlickGrid will need. But especially setting up rollup, typescript, karma, incremental compilation etc. took me a bit, but now it's really smooth (to me at least 😁 ). 

- https://github.com/CoderLine/alphaTab/
- https://alphatab.net/docs/contributing

**Comment by ghiscoding** [comment]
@6pac 
Can you open the GitHub "Discussion" tab in your project, I think it would be better use for this

![image](https://user-images.githubusercontent.com/643976/107649098-18d6a800-6c4b-11eb-9510-e3f706dbe178.png)

scroll down to find "Discussion" and enable it

![image](https://user-images.githubusercontent.com/643976/107649159-2ee46880-6c4b-11eb-9cc2-f9ee61ca573f.png)

**Comment by ghiscoding** [comment]
@Danielku15 the Discussion tab is now open, can you move your text in a new Discussion.. oh wait there's a button "Convert to discussion", please do that

![image](https://user-images.githubusercontent.com/643976/107650977-03fb1400-6c4d-11eb-8c9c-35116d072562.png)

**Comment by Danielku15** [comment]
@ghiscoding Only Repository Maintainers can do that 😉 Feel free to move it. 
![image](https://user-images.githubusercontent.com/674916/107660344-71786600-6c88-11eb-9cf8-319a38066f16.png)
