### ISSUE TITLE
Select field that does an AJAX

### ISSUE THREAD

**Issue by bilogic** [6pac/SlickGrid#578]
Hi,

I have a heavily customized SlickGrid based off from mleibman.

One of heavily stuff was implementing a dropdown column that does a database lookup, i.e. a select that list its values based on a lookup back to the database table. 

I looked around but thought it is easier and faster to ask, Is there anything similar in this repo? Thank you.

**Comment by 6pac** [comment]
How about this one? 
http://6pac.github.io/SlickGrid/examples/example-select2-editor.html

**Comment by bilogic** [comment]
Ah ok, I think it's similar to where I first found it. The issue is some tables have huge records, loading them all doesn't make sense, what helped was a search on the database. Maybe we need a `select3` 🤣

**Comment by bilogic** [comment]
I just googled, will this https://select2.org/data-sources/ajax work in http://6pac.github.io/SlickGrid/examples/example-select2-editor.html ?

**Comment by 6pac** [comment]
Certainly.  However you'd need to modify the editor to work with the Select2 Ajax loading code. You could put together a new example and submit it to the repo.

**Comment by bilogic** [comment]
Sure, let me give it shot. Let's leave this issue open first. Thank you.

**Comment by bilogic** [comment]
@6pac I actually finished half the example, but facing an old issue (and I'm not keen to re-visit my old messy code).

What is the best way in your opinion to provide the formatter with the proper values when loading the HTML for the first time?

**Comment by 6pac** [comment]
They approach I have taken in the past is to store the data source for the
dropdown (a DataView or a js object) as a member of the column object.
You could do this for both AJAX and non-AJAX datasources, the only
difference being that the AJAZ datasource would have rows dynamically added
to it by code.
 
  _____

**Comment by ghiscoding** [comment]
The other option is to use jQueryUI [Autocomplete](https://jqueryui.com/autocomplete/) since jQueryUI is a dependency anyway but that would work only for 1 value not multiple.

I'm moving this issue as a "Discussion" (the new GitHub tab) since this is not an issue but really a Discussion
