### ISSUE TITLE
Minor change for handleMenuItemClick

### ISSUE THREAD

**Issue by arthur-clifford** [6pac/SlickGrid#582]
There is a simple change which can be made to allow for more dynamic decisions as to whether to hide the header menu for a given command.

In plugins/headerMenu.js

For the handleMenuItemClick function:

hideMenu() is called prior to checking whether there is a command.

This means every time you click a menu option the menu closes.

If you move hideMenu after the if block and wrap it as follows:
```
if(!e.isDefaultPrevented) {
  hideMenu();
}
```
The result is the menu will only be hidden if a developer doesn't use e.preventDefault() in the onCommand handler.

```
onCommand: (e: Event, args: MenuCommandItemCallbackArgs) => {
   e.preventDefault();
  // do stuff that will not close the window.
}
```

This would also mean a developer's could decide whether to prevent the default depending on the command that is being handled.

**Comment by 6pac** [comment]
OK, have done this. it will be in the next release. @ghiscoding take note, it seemed trivial and a good idea.

**Comment by ghiscoding** [comment]
@6pac go ahead for the changes, please note that it's in 5 different plugins
- grid menu
- header menu
- header button
- cell menu
- context menu

**Comment by 6pac** [comment]
OK, it appears that the code change is just in HeaderMenu.js, the others call that, so it's a flow on effect. It is non-breaking, though.

**Comment by ghiscoding** [comment]
if I look at the Grid Menu, it seems that I added a `leaveOpen` option instead of the prevent default cancellation? It's probably better to add the same prevent default code to the Grid Menu as well, to be more consistent.

https://github.com/6pac/SlickGrid/blob/3991679be77841d1abe86771060b67a1a38d28f2/controls/slick.gridmenu.js#L507-L510

**Comment by 6pac** [comment]
10-4

**Comment by ghiscoding** [comment]
@6pac did you do code change for that or did you wanted me to create a PR? 
Just want to make sure it's not forgotten

Cheers mate

**Comment by 6pac** [comment]
thanks @ghiscoding maybe better if you do it...

**Comment by ghiscoding** [comment]
done... and I went further and applied it to all plugins I found (4 of them) to have such behaviors.
