### ISSUE TITLE
Accessibility: Ensures every form element has a label

### ISSUE THREAD

**Issue by chinthas-mh** [6pac/SlickGrid#587]
Element location
input[data-test="page-number-input"]

Element source
<input type="text" data-test="page-number-input" size="1" class="form-control">

To solve this violation, you need to...
Fix at least one (1) of these issues:
•	aria-label attribute does not exist or is empty
•	aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
•	Form element does not have an implicit (wrapped) <label>
•	Form element does not have an explicit <label>
•	Element has no title attribute
•	Element has no placeholder attribute
•	Element's default semantics were not overridden with role="none" or role="presentation"

**Comment by ghiscoding** [comment]
closed by #764 to be released in next major v4.0
