### ISSUE TITLE
Accessibility: Ensures select element has an accessible name

### ISSUE THREAD

**Issue by chinthas-mh** [6pac/SlickGrid#588]
Element location
#items-per-page-label

Element source
<select id="items-per-page-label">

To solve this violation, you need to...
Fix at least one (1) of these issues:
•	aria-label attribute does not exist or is empty
•	aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
•	Form element does not have an implicit (wrapped) <label>
•	Form element does not have an explicit <label>
•	Element has no title attribute
•	Element's default semantics were not overridden with role="none" or role="presentation"

**Comment by ghiscoding** [comment]
closed by #764 to be released in next major v4.0
