### ISSUE TITLE
Is it has the numeric pagination?

### ISSUE THREAD

**Issue by bakbuz** [6pac/SlickGrid#606]
Hello

I looked the options but I didn't find it. 

Is it has the numeric pagination?

**Comment by 6pac** [comment]
The  pager is a plugin: http://6pac.github.io/SlickGrid/examples/example4-model.html

In future, could you please ask usage questions on StackOverflow? GitHub Issues are for bugs or suggestions.

**Comment by bakbuz** [comment]
> The pager is a plugin: http://6pac.github.io/SlickGrid/examples/example4-model.html
> 
> In future, could you please ask usage questions on StackOverflow? GitHub Issues are for bugs or suggestions.

Sure. Thanks you.
