### ISSUE TITLE
Where is the source branch for jquery.event.drag-2.3.0.js?

### ISSUE THREAD

**Issue by zakimaksyutov** [6pac/SlickGrid#63]
Having troubles locating it. Will appreciate if someone points to it.

Thank you!

**Comment by 6pac** [comment]
check in the code tab under the ```/lib``` folder

**Comment by zakimaksyutov** [comment]
Thank you, yes I found it there.

My question was from where did it come from? In other repositories I found version 2.2.0. But not 2.3.0.

**Comment by 6pac** [comment]
So the 2.2 file originally came from ThreeDubMedia. 
The repo was update to be compatible with jQuery 1.8 onwards, plus  2.x and 3.x by @lfilho https://github.com/6pac/SlickGrid/pull/39
and he also updated the jquery.event.drag library https://github.com/6pac/SlickGrid/pull/44

So this version of the drag and drop libs are exclusive to here.
There have been attempts to rewrite SlickGrid to remove this dependency https://github.com/6pac/SlickGrid/issues/14 but without success.
Recently @DimitarChristoff offered a major rewrite to remove jQuery and jQueryUI dependencies altogether https://github.com/6pac/SlickGrid/issues/41 but I haven't had time to look at that in detail yet.

**Comment by DimitarChristoff** [comment]
I got it to work ok but there are some edgecases when using frozen columns
and reorder.

a colleague of mine is working on it now. will ping him as there needs to
be a few webpack changes but will drop a more stable release soon

**Comment by zakimaksyutov** [comment]
Thank you!
