### ISSUE TITLE
slickgrid initialisation options

### ISSUE THREAD

**Issue by violet313** [6pac/SlickGrid#637]
When instantiating a new `Slick.Grid`, it now seems necessary to provide `options`. even if there are none i wish to specify.
eg. in the current master, commit f12f4cc77268a155059deeaa88e83a1f09800451 `slick.grid.js function init()` :
[Line 319](https://github.com/6pac/SlickGrid/blob/f12f4cc77268a155059deeaa88e83a1f09800451/slick.grid.js#L319) will now cause my codes to bork if no `options` have been supplied.

I suggest the condition on line 319 might be better placed *after* [line 324](https://github.com/6pac/SlickGrid/blob/f12f4cc77268a155059deeaa88e83a1f09800451/slick.grid.js#L324) where  the options are properly initialised from defaults overridden by anything the caller does or does not provide.

```javascript
      if (!options.suppressCssChangesOnHiddenInit) { cacheCssForHiddenInit(); }

      // calculate these only once and share between grid instances
      maxSupportedCssHeight = maxSupportedCssHeight || getMaxSupportedCssHeight();

      options = $.extend({}, defaults, options);
      validateAndEnforceOptions();
```

**Comment by ghiscoding** [comment]
@violet313 would you mind creating a Pull Request for the change? 

BTW and as a side note, I'm not sure if you saw this or not but we created a [Row Detail](http://6pac.github.io/SlickGrid/examples/example16-row-detail.html) plugin based on your technique. So I wanted to say thanks at the same time 😉 
![image](https://user-images.githubusercontent.com/643976/133665927-6b622c96-00ed-4550-a3c1-113757a5cc03.png)

**Comment by violet313** [comment]
^hey that's rly cool. i'm chuffed :smile_cat: 
busy elsewhere atm atm but i shall do the pull..
