### ISSUE TITLE
getRowFromPosition can fail when Mac Chrome browser is zoomed in or out

### ISSUE THREAD

**Issue by ronmichael** [6pac/SlickGrid#647]
I ran into an issue where args.item was sometimes null in the onBeforeEditCell event. The row number would also be blank and the column number would be incorrect. To reproduce it, I had to be using Mac Chrome, and I had to first click on the very last row in the grid. After doing that, onBeforeEditCell would return invalid arguments whenever they clicked anywhere else. 

I've narrowed things down to the _offset_ variable in _slick.grid.js_ being set to null for some reason when the user clicked on that last row. I hacked getRowFromPosition() and added a quick check to set offset to 0 if it was empty and this fixed my problem. 

I know that's probably not a viable solution for everyone. And I couldn't figure out where exactly the code was changing offset to null.

**Comment by 6pac** [comment]
@ronmichael was there any further info on this? Unfotunately if I can't repro it, I can't fix it!

**Comment by 6pac** [comment]
@ronmichael I think this may be fixed, see #674, it looks like the solution is to prevent the grid handling any scroll behaviour when autoheight is set to true.
