### ISSUE TITLE
Getting rid of all the jQuery dependencies

### ISSUE THREAD

**Issue by jscriptcoder** [6pac/SlickGrid#65]
Hi there,

I've been using Slickgrid for a while already in several projects in the last 2 years and a half. I personally find this grid amazing. Probably one of the best out there, and I'd offer myself to contribute with its development... Only thing I find sad is having these, in my personal opinion, unnecesary dependencies. The only reason why I'm including jQuery in those projects is just because of Slickgrid. I've dived many times in the code to change and improve things and I really see no reason at all to use jQuery and jQuery-ui. I don't even think it would take long to do so.

What's the opinion about it?

Thanks

**Comment by 6pac** [comment]
@jscriptcoder, meet @DimitarChristoff 

https://github.com/6pac/SlickGrid/issues/41
