### ISSUE TITLE
Selected rows doesn't update when a  hidden column is shown 

### ISSUE THREAD

**Issue by osnerrebete** [6pac/SlickGrid#661]
It happens when you select some rows.
Then if you change the columns' visibility and a hidden column is changed to visible, it won't mark as selected the new cells.

<img width="635" alt="Screen Shot 2021-12-17 at 1 19 15 PM" src="https://user-images.githubusercontent.com/2625551/146575367-1a21be0a-1cb4-47f6-a524-f2a8f007f3f5.png">

**Comment by 6pac** [comment]
I have fixed the ```setColumns``` method in the grid so that it refreshes the selection. This will be in the next release.  
In the meantime, you can refresh the selection after the call to ```setColumns``` (assuming you are using RowSelectionModel):

      grid.setColumns(showColArr);
      grid.getSelectionModel().setSelectedRows(getSelectedRows());
