### ISSUE TITLE
Fortify Scan Issues

### ISSUE THREAD

**Issue by AbstractAlao** [6pac/SlickGrid#663]
I maintain a system that uses slickgrid and the following items came up on our Fortify Scan for 2.4.42

### Command Injection
slick.grid.js:4781
The method getCellFromNode() in grid.js calls exec() to execute a command. This call might allow an attacker to inject malicious commands.

slick.grid.js:2079
The method getColumnCssRules() in grid.js calls exec() to execute a command. This call might allow an attacker to inject malicious commands.

slick.grid.js:2076
The method getColumnCssRules() in grid.js calls exec() to execute a command. This call might allow an attacker to inject malicious commands.

### Race Condition
slick.grid.js:555
The call to on() in grid.js on line 555 sets a callback that could lead to a race condition.

slick.grid.js:559
The call to on() in grid.js on line 559 sets a callback that could lead to a race condition.

I think the Race conditions are false positives since javascript executes sequentially but as far as the command injections are these real issues?

I'm also going to upgrade to the latest version but not sure if it will resolve the items above.

**Comment by 6pac** [comment]
I don't think any of these are consequential. The ```exec``` is being used to match a RegEx, to to execute code. The 'race conditions' are just setting up of grid rezise and scroll events. I don't think race conditions are a problem in this context.

**Comment by AbstractAlao** [comment]
Thanks, @6pac that is all I needed.  I think the reason the command injection is coming up is that the scanner thinks it is user input that is being supplied into the `exec` command.  Are you pulling the values from the DOM?

**Comment by 6pac** [comment]
even less of a worry than that. it's only the RegEx that's being executed:

    if (matches = /\.l\d+/.exec(selector)) {
