### ISSUE TITLE
Should SlickGrid throw Error and not strings?

### ISSUE THREAD

**Issue by zakimaksyutov** [6pac/SlickGrid#67]
Hello,

When exception occurs (rows have same id), SlickGrid usually (always?) throws them as strings:

 ```
function ensureIdUniqueness() {
      var id;
      for (var i = 0, l = items.length; i < l; i++) {
        id = items[i][idProperty];
        if (id === undefined || idxById[id] !== i) {
          throw "Each data element must implement a unique 'id' property";
        }
      }
    }
```

As a result in try/catch we also get only a string without stack trace and other information. Which makes debugging things harder, especially when it repro's only on user's browser =)

Does it make sense to move towards

`throw new Error("Each data element must implement a unique 'id' property")`

instead?

**Comment by 6pac** [comment]
You're right. Thanks for the heads up.
I just committed these changes.

**Comment by zakimaksyutov** [comment]
Wow, this was fast, thank you very much sir! Looking forward to the next release.
