### ISSUE TITLE
Will slickgrid event drag support for jquery version 3.6.0

### ISSUE THREAD

**Issue by skmusharaf786** [6pac/SlickGrid#671]
I have recently updated the Jquery version to 3.6.0 but i'm facing below issue with slickgrid.event.drag.js

Request you to please help me in resolving the issue.

How can I fix the solution for Uncaught TypeError: Cannot set properties of undefined (setting 'touchcancel') at jquery.event.drag-2.2.js

    $event.fixHooks.touchcancel = {                                                         --> 382
props: "clientX clientY pageX pageY screenX screenY".split( " " ),
filter: function( event, orig ) {
if ( orig ){
var touched = ( orig.touches && orig.touches[0] )
|| ( orig.changedTouches && orig.changedTouches[0] )
|| null;
// iOS webkit: touchstart, touchmove, touchend
if ( touched )
$.each( touchHooks.props, function( i, prop ){
event[ prop ] = touched[ prop ];
});
}
return event;
}
};

// share the same special event configuration with related events...
$special.draginit = $special.dragstart = $special.dragend = drag;
})(jQuery); -->402
![slickgrid](https://user-images.githubusercontent.com/102133924/161265970-117f7279-2791-4868-adbb-69d9cd5c7522.PNG)

**Comment by ghiscoding** [comment]
most probably yes you should use [jquery.event.drag-2.3.0.js](https://github.com/6pac/SlickGrid/blob/master/lib/jquery.event.drag-2.3.0.js), the previous is very old and was probably there for project with jQuery 2.x (I'm only guessing here though)

**Comment by 6pac** [comment]
Yes the 2.3.0 version was specifically upgraded for compatibility with later versions of jQuery. That was the only functionaility updated. You should be using all of the library versions used in the examples. There have been security issues over the last 12 months which the latest versions resolve.

**Comment by skmusharaf786** [comment]
Thankyou so much guys :)
