### ISSUE TITLE
DIsappearing row with auto-height on when grid adds scroll bar to show editor

### ISSUE THREAD

**Issue by genyded** [6pac/SlickGrid#674]
[example-dynamic-filtered-with-jquery-tabs.zip](https://github.com/6pac/SlickGrid/files/8458916/example-dynamic-filtered-with-jquery-tabs.zip)

The attached aip contains a modified version of the example-dynamic-filtered-with-jquery-tabs.html file from the examples folder in your build tree. Extract it, put it into the examples folder of a copy your build tree then open/run it. If you try to edit the 'Relevance' (last) column of one of the last two rows (row 49 or 50). You should see that the entire row disappears from the grid. If you edit any of the higher up rows that do not cause the grid to scroll, then it weeks fine. This only seems to happen when editing a row that causes the grid to scroll when the editor is opened. If you turn auto-height off, the issues does not happen, but we need editable cells with auto height on. We are using v2.4.24 of the grid.

**Comment by 6pac** [comment]
Thanks for the bug report. The solution was to prevent the grid handling the scroll event when autoheight is being used.

    function handleScroll() {
      + // autoheight does not have scrolling, but editors can trigger a scroll, which we should ignore
      + if (options.autoHeight) return;
      
      scrollTop = $viewportScrollContainerY[0].scrollTop;
      scrollLeft = $viewportScrollContainerX[0].scrollLeft;
      return _handleScroll(false);
    }

this will be included in the next release.
