### ISSUE TITLE
Editors Fail With Slick.RowSelectionModel({selectActiveRow: true})

### ISSUE THREAD

**Issue by cpeter0** [6pac/SlickGrid#68]
Modify examples/example-checkbox-row-select.html line 89 to grid.setSelectionModel(new Slick.RowSelectionModel({selectActiveRow: **true**})); causes editing of cells to fail. Works in original SlickGrid.

**Comment by cpeter0** [comment]
Apparently has something to do with line 90 grid.registerPlugin(checkboxSelector); If this is commented out the check boxes appear and are functional except for "select all rows" checkbox in grid header.

**Comment by Aibric** [comment]
I have the same problem ... ...

**Comment by 6pac** [comment]
will try to look at this soon

**Comment by 6pac** [comment]
This is a *really* complicated bug, unfortunately, to do with active cell selection. 
It will probably take 6 to 10 hours to fix at some stage, and will involve reworking all the active cell logic for the grid. 

I can't even work out a quick patch yet, but if I do I'll post it.

**Comment by ghiscoding** [comment]
I have a similar problem but not sure if it's the same issue. If I use `Slick.CheckboxSelectColumn` with any Inline Editor, when I click on a cell that is supposed to be editable the row selection kicks in and cancels out the editor. 

Is there any known workaround for something similar? 
I mainly want to use Inline Editor with Row Selection

**Comment by ghiscoding** [comment]
Found the problem and made a PR in regards to the current issue. Made a fix to master by mistake, please disregard and look instead at the PR #241

**Comment by ghiscoding** [comment]
I believe the original issue was covered in the PR that is now merged and so we should be safe to close the issue. If there's any problem, feel free to write something here or open a new issue. Thanks
