### ISSUE TITLE
updateRowCount does not keep scroll position stable

### ISSUE THREAD

**Issue by yamass** [6pac/SlickGrid#681]
### When does it happen?

* When a slickgrid has a horizontal scrollbar 
* and the user scrolls down to the bottom
* and updateRowCount() is invoked.

This happens a lot when using server-side models that react on scrolling by updating the model.

### Example (minimalistic)

(put this into the examples directory to run)

```
<!DOCTYPE HTML>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <link rel="stylesheet" href="../slick.grid.css" type="text/css"/>
  <link rel="stylesheet" href="../css/smoothness/jquery-ui.css" type="text/css"/>
  <link rel="stylesheet" href="examples.css" type="text/css"/>
</head>
<body>
<div id="myGrid" style="width:300px;height:500px;"></div>

<script src="../lib/jquery-1.12.4.min.js"></script>
<script src="../lib/jquery.event.drag-2.3.0.js"></script>

<script src="../slick.core.js"></script>
<script src="../slick.grid.js"></script>

<script>
  var grid;
  var columns = [
    {id: "a", name: "A", field: "a", width: 500}
  ];

  var options = {
    enableCellNavigation: true,
    enableColumnReorder: false
  };

  $(function () {
    var data = [];
    for (var i = 0; i < 30; i++) {
      data[i] = {a: "a " + i};
    }

    grid = new Slick.Grid("#myGrid", data, columns, options);

    setInterval(() => {
      console.log("updating row count...")
      grid.updateRowCount();
    }, 1000);
  })
</script>
</body>
</html>
```

I will create a fixing pull request for this in a moment...

**Comment by ghiscoding** [comment]
would be nice if your PR can fix long standing issue #297

**Comment by yamass** [comment]
@ghiscoding Unfortunately not.

**Comment by 6pac** [comment]
will have a look this week. will check out #297 too, there seems to be enough detail to reproduce it.

**Comment by yamass** [comment]
@6pac Any news on this?

**Comment by 6pac** [comment]
@sorry, I just get really busy sometimes. I'll get to this on the weekend, I'd say.

**Comment by yamass** [comment]
Awesome! Thank you!

**Comment by 6pac** [comment]
sorry it tooks so long @yamass - I will create a new release tomorrow once I've added another couple of commits.
