### ISSUE TITLE
onClick is not called if there was a grid update between mouse down and mouse up

### ISSUE THREAD

**Issue by zakimaksyutov** [6pac/SlickGrid#69]
My app updates grid values every second. As a result I noticed that if update occurs between mouse down and mouse up then onClick handle is not called.

Is it expected? Or do I update data incorrectly? 

Asking in case someone knows the right approach. Starting looking deeper into it myself as well.

**Comment by zakimaksyutov** [comment]
This is because SlickGrid subscribes on $canvas which gets updated (replaced?).

**Comment by zakimaksyutov** [comment]
More information: subscribing on $viewport didn't help (I guess because "click" is still tracked on individual divs which get rerendered upon update).

The solution which works is to subscribe on mousedown/up events and handle all complexities myself.

I think SlickGrid should expose mousedown/up events and let plugins/clients handle the complexity of wiring them together.

Then for my app (and for dataview extension) it might be that if mousedown/up occurred on the same data item then it should result in click. Then if grid rerenders but rows didn't change order (due to sorting) then click will occur. And order did change then it would not (which I think should be expected).

If I missed easier approach - would love to learn more!

Thoughts?

PS: I can create PR which exposes mousedown/up events.

**Comment by zakimaksyutov** [comment]
Actually for mousedown/up events there is no need to extend SlickGrid, app can subscribe on them via main container:

```
        this._$slickGridContainer.on("mouseup", function(e: DOMEvent){
            let cell: slickgrid.Cell = self._serversInfoGrid.getCellFromEvent(e);
            if (cell && cell.row >= 0 && cell.row < self._data.length) {
                console.log("mouseup for #" + cell.row + " row.");
            }
        });
```

Now it comes the tricky part to reimplement click event based on mousedown/up (same data row, ESC, etc.). 

I'm closing this issue because there is nothing to add to SlickGrid to support this scenario. It might make sense to support it in DataView but if there are no asks then it should be treated as low-pri.

**Comment by 6pac** [comment]
Thanks for your thoughts. Events are always a bit of a hotspot for requests for functionality, and I'd like to sit down and comprehensively review all the options. Even if we don't need to add the mouse events, we should document them for future requests like yours.
I've also written a [manifesto](https://github.com/6pac/SlickGrid/wiki/4-The-SlickGrid-Manifesto) rather than repeatedly type a screed into these forums!

**Comment by zakimaksyutov** [comment]
Absolutely. If there is a way to solve it without bringing additional code into core - that's the right way.

Thank you for your work, amazing control =)
