### ISSUE TITLE
Embedded version string is still 2.1

### ISSUE THREAD

**Issue by kika** [6pac/SlickGrid#7]
https://github.com/6pac/SlickGrid/blob/master/slick.grid.js#L3332

It leads to confusion when switching from the original repo version to yours. I was chasing where do I have old version laying around and why my build picks it up until I decided to look into the code :-)

**Comment by 6pac** [comment]
Thanks for noticing that. I hadn't. Will Update.

**Comment by 6pac** [comment]
Fixed.
