### ISSUE TITLE
slickgrid resize causes scrollbar problem near bottom

### ISSUE THREAD

**Issue by lostinroom** [6pac/SlickGrid#709]
Hi, <br/>
It seems the issue come back<br/>
https://github.com/mleibman/SlickGrid/issues/477<br/>
The version that I use is 2.4.45

**Comment by 6pac** [comment]
Fixed. Thanks for the report.
@ghiscoding , probably time to do another release? Anything you need to put in first?

**Comment by ghiscoding** [comment]
@6pac you can wait until the weekend, I might push changes on the custom tooltip plugin, I'll let you know

**Comment by lostinroom** [comment]
Thanks for quick response, guys

**Comment by ghiscoding** [comment]
@lostinroom the fix was released under latest version `3.0.2`
