### ISSUE TITLE
Text selection over multiple rows is broken

### ISSUE THREAD

**Issue by alexk-z** [6pac/SlickGrid#71]
When enabling text selection for rows and trying to select text on multiple rows at the same - I get broken behavior in Chrome after scrolling up and down. Please see GIF below for the example.

Is there a fix/work-around for this issue?

![Broken selection](http://g.recordit.co/tLPunvTinW.gif)

**Comment by alexk-z** [comment]
From inspecting DOM - rows can be selected continuously, if they appear in order. However, SlickGrid mixes them up and after scrolling up and down rows are not in order in DOM. They appear in order on the screen because they have absolute coordinates.

Is there a way to force/ensure that rows are ordered in DOM model?

**Comment by 6pac** [comment]
Not quite sure of your use case here. Is the above an actual grid, with all the borders etc switched off, or some kind of debug dump?
I don't think SlickGrid was really designed for this. It should allow selection of text in a cell, and also selection of multiple rows. I tend to thing selecting text in multiple rows is an unintended side effect of how the browser selection works.
So short answer, no, I don't think this is going to be possible without a major rework of the core render code.

**Comment by alexk-z** [comment]
Thank you for fast reply!

That is grid with all borders switched off. SlickGrid is used here for virtualization of text entries.

So this is not supported setup. I will look into fixing the order of DOM elements in post-render sequence as a hack for my case.

If you could share any insights on the best approach of doing this hack - that would be really kind of you, given that this is not intended use.

**Comment by 6pac** [comment]
one of the features of slickgrid is that it uses row diffs, so then when the viewport changes, it only replaces rows that have changed. this would be what's causing the out of order DOM nodes. 
one solution would be to disable that and replace all the rows all the time.
invalidateAllRows() might be a start.

**Comment by 6pac** [comment]
Great :-)

**Comment by alexk-z** [comment]
Well, it seems to be working. Closing the issue =)
