### ISSUE TITLE
AutoTooltips not working for word-wrapped columns

### ISSUE THREAD

**Issue by tr4npt** [6pac/SlickGrid#740]
When a column is word-wrapped, and its data goes past the bottom of the cell, tooltips do not work.  Tooltips should display when the data is taller than the cell height, but they currently only display when the data is wider than the cell width.

I've fixed the code, but not sure how to submit a pull request.  I've attached the fixed file.

[slick.autotooltips.js.zip](https://github.com/6pac/SlickGrid/files/11296654/slick.autotooltips.js.zip)

**Comment by ghiscoding** [comment]
Providing code through zip is not at all safe neither secure for us, the easiest for you is probably to just edit the file directly on GitHub

![image](https://user-images.githubusercontent.com/643976/233801719-5c271b48-41ec-4e8f-9364-4b2df3b05a69.png)

**Comment by tr4npt** [comment]
Thanks for the advice.  I have submitted a pull request.
