### ISSUE TITLE
Can't able to get all the selected rows from the slickgrid version 2.2

### ISSUE THREAD

**Issue by nisargparikh1** [6pac/SlickGrid#750]
Can't able to get all the selected rows from the slickgrid version 2.2

tried with below method as well but not working

var selectedData = [],
    selectedIndexes;

selectedIndexes = _grid.getSelectedRows();
jQuery.each(selectedIndexes, function (index, value) {
  selectedData.push(_grid.getData()[value]);
});

getting error stating getSelectedRows is not a function check its dependencies as well but not working

Does any one have idea how to get all the rows data from the slick grid so from the checkbox selection I can get the selected data?
or
Does any one knows how to get selected rows data from slick grid

**Comment by 6pac** [comment]
```getSelectedRows()``` has been the method of getting selected for a long time. I'd suspect that perhaps ```_grid``` is not what you think it is. Find the version of the grid you are using and go to the examples. ```example-checkbox-row-select.html``` is one you should be able to use to test.

**Comment by 6pac** [comment]
Suggest asking on StackOverflow
