### ISSUE TITLE
Q: use radio in SlickGrid

### ISSUE THREAD

**Issue by general687** [6pac/SlickGrid#763]
hi 6pac
i want to use radio in slickGrid but i find it maybe not support this.
I tried to write the source code myself, but it was unsuccessful.
perhaps I can complete my requirements by using checkbox.

**Comment by general687** [comment]
![question](https://user-images.githubusercontent.com/44969627/236754572-50888c36-3192-4732-8852-6cd116fac4fd.png)

**Comment by 6pac** [comment]
I would recommend posting on StackOverflow for this issue. GitHub is for bugs and new features.

You need to write an editor that supports radio buttons (not hard) and a formatted to display radion buttons or some other format to indicate the selection.

**Comment by general687** [comment]
thank for your answer.
i tried write a formatter to display radio buttons, but the button only display the "〇" without "boy/girl".
i do not know how to do.
i will go StackOverflow to search the answer.
