### ISSUE TITLE
using Grid.GotoCell doesn't invoke OnAddNewRow when expected

### ISSUE THREAD

**Issue by mishal153** [6pac/SlickGrid#78]
I have 'enableAddRow' as 'true' in the grid options. If I click on then new row's first cell, edit cell value and move to adjacent cell, then OnAddNewRow handler gets called as expected.
But that doesn't happen if I choose to navigate to new row's first cell using _grid.gotoCell(_grid.getDataLength(), 1, true); and then edit cell value and move to adjacent cell

Any suggestions how to get around this issue ?

**Comment by 6pac** [comment]
I think you may have another bug. I tried modifying ```example3-editing```, adding a button to do ```_grid.gotoCell(_grid.getDataLength(), 1, true);``` and putting an alert at the start of the ```OnAddNewRow``` handler. Works perfectly.
