### ISSUE TITLE
Data not rendering with latest release

### ISSUE THREAD

**Issue by BuyInClub** [6pac/SlickGrid#780]
If you go to the URL , https://buyinclub.github.io/Table1-Details.html, you will notice the table is no longer rendering.
The logic is in this file - https://buyinclub.github.io/handDetails.js
The data is in this file  - https://buyinclub.github.io/Table1-Details.js

I removed the reference to jquery in line 54 of https://buyinclub.github.io/Table1-Details.html, but this did not help.

Have no idea what is going on.

**Comment by BuyInClub** [comment]
I think I figured it out.  The issue is once I commented out jquery, then line 7 was not working in https://buyinclub.github.io/handDetails.js.
I added the line 
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> 
to  https://buyinclub.github.io/Table1-Details.html and things seem fine now.

**Comment by BuyInClub** [comment]
see comment

**Comment by 6pac** [comment]
Not sure what was going on there, but glad you fixed it. This is a brand new breaking release so it is good to test thoroughly before rolling out to production.

**Comment by BuyInClub** [comment]
Thank you.  This issue had nothing to do with SlickGrid.  I was using JQuery functionality, so when I pulled out the reference, things broke.  I still can't figure out the other issue I posted on scrollRowIntoView.
