### ISSUE TITLE
Progressively slower horizontal scrolling

### ISSUE THREAD

**Issue by NHerw** [6pac/SlickGrid#789]
When scrolling horizontally through a grid using shift + mousewheel, the scroll speed gets progressively slower the further I scroll.

Please take a look at the video I attached.

My physical scrolling speed stays the same but the further i scroll towards either end of the grid, the speed in the browser decreases.

https://github.com/6pac/SlickGrid/assets/92430777/e8a13863-61ba-493f-8178-fb96da048a28

This issue doesn't appear on any other scrollable html divs, so I think the issue is with slickgrid. The behavior is the same in firefox and chrome.

I'm using Slickgrid v3.0.4 and Chrome v114.0.5735.134

Unfortunately I have no clue which code is relevant to this issue. But if you have any ideas, I will provide whatever you need.

Thanks :)

Edit:
I noticed that in the ["Fill browser" example from mleibman](https://mleibman.github.io/SlickGrid/examples/example12-fillbrowser.html), the horizontal scrolling works well. 
But in [this repo's example](http://6pac.github.io/SlickGrid/examples/example12-fillbrowser.html), the horizontal scrolling seems to be disabled.

**Comment by ghiscoding** [comment]
if you find the issue and find a fix then feel free to submit a Pull Request. There was this old PR that wasn't merged, not sure if it was related or not #653

**Comment by ghiscoding** [comment]
can you try to remove the `setTimeout` wrapper instead and keep what's inside it, see if that helps. The setTimeout was added to fix a Chrome issue which they have the Chrome team eventually fixed so we could probably remove it now

**Comment by 6pac** [comment]
The probable issue is that there are a cascade of the SetTimeout events which back up. Another approach would be to clear any previous events when setting a new one. This is done in other places in the grid code.

**Comment by NHerw** [comment]
@ghiscoding Removing the setTimeout wrapper seems to work for Chrome! I've also tested it in Firefox, and it doesn't seem to cause any Issues there either.

I'll do a pull request 

@6pac Clearing the setTimeout didn't work for me. Here's how I tried it, maybe that was the wrong approach:

I created a global variable called `scrollTimeout` and assigned the setTimeout function to it. Then I tried clearing the Timeout before and after the setTimeout was started, but neither worked.

First attempt:
```javascript
Window.clearTimeout(scrollTimeout)
scrollTimeout = setTimeout(function () {
          $viewportScrollContainerX[0].scrollLeft = scrollLeft;
          $headerScrollContainer[0].scrollLeft = scrollLeft;
          $topPanelScroller[0].scrollLeft = scrollLeft;
...

```
Second attempt:
```javascript
scrollTimeout = setTimeout(function () {
          $viewportScrollContainerX[0].scrollLeft = scrollLeft;
          $headerScrollContainer[0].scrollLeft = scrollLeft;
          $topPanelScroller[0].scrollLeft = scrollLeft;
...
}
Window.clearTimeout(scrollTimeout)
```
