### ISSUE TITLE
Allow pageup/pagedown/home/end etc during selection

### ISSUE THREAD

**Issue by tomqwpl** [6pac/SlickGrid#794]
The cell selection model allows for selection of range using keyboard, but only left, right, up, down.
Normal navigation can also be done using page up, down, home end etc.

It would be nice of the same keys could be used during selection too.

**Comment by ghiscoding** [comment]
If you want to implement it then Pull Requests are welcome

**Comment by ghiscoding** [comment]
now available in latest version [5.1.0](https://github.com/6pac/SlickGrid/releases/tag/5.1.0), I tested with these 2 live examples:
- [Excel spreadsheet](https://6pac.github.io/SlickGrid/examples/example-spreadsheet.html)
- [Excel spreadsheet with DataView](https://6pac.github.io/SlickGrid/examples/example-spreadsheet-dataview.html) (**new**), this is a new example and is the same as the previous one but with the use of the DataView
