### ISSUE TITLE
The issue on displaying data in the Chrome browser

### ISSUE THREAD

**Issue by athulkrishnauk** [6pac/SlickGrid#798]
In the Chrome browser some cases data is displayed, and in some cases is not displayed. Most of the cases data is not displayed in Chrome browser. But other browsers displayed this same data properly in all cases. 
Mozilla firefox Screenshot
![Screenshot 2023-06-28 123222](https://github.com/6pac/SlickGrid/assets/69037308/0cf9beec-44ec-4efb-8f9f-99635bc6697a)
Google Chrome Screenshot
![Screenshot 2023-06-28 123440](https://github.com/6pac/SlickGrid/assets/69037308/9d287cf4-d6cb-4d5d-9ba3-f30531b37763)

**Comment by 6pac** [comment]
I think this would be better posted on StackOverflow. In any case, you need to provide an example of the behaviour based on one of the SlickGrid examples, so we can reproduce it. (Hint: while you're making that example, 99% chance you'll solve the issue)

**Comment by ghiscoding** [comment]
closing since no repro or even feedback was provided, there isn't much more we can do

**Comment by athulkrishnauk** [comment]
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:p="http://primefaces.org/ui">
	
	<h:outputStylesheet name="slick.grid.css" library="SlickGrid"/>
	<h:outputStylesheet name="style/slick-grid-common.css" library="SlickGrid"/>
	<h:outputStylesheet name="slick-default-theme.css" library="SlickGrid"/> 
	
	<h:outputStylesheet>
		.status_style {
			height: 25px;
			width: 25px;
			border: 1px solid black;
		}
		
		.status_grid {
			border: 1px solid dimgray;
		}
		
		.card_style {		
			background-color: lightgray !important;
			margin-left: 0px;
			margin-right: 0px;
			padding: 5px !important;
			padding-bottom: 5px !important;
			border-radius: 0px !important;
			margin-bottom: 0px !important;
		}
		
		.plan_table_grid {
			border: 1px solid #C0C0C0;
			background-color: white;
			margin-left: 4px;
			margin-top: 5px;
			width: 99.3% !important;
		}
		
		.ui-panelgrid-cell {
			padding-bottom: 0px !important;
		}
		
		.plan_top_bar {
			background-color: dimgray;
			color: white;
			margin: 0px !important;
			border: 2px solid white;
		}
		
		#form\:refreshId {
			padding: 7px !important;
		}
		
		#form\:typeId {
			padding: 7px !important;
		}
		
		#form\:visitTypeId {
			padding: 7px !important;
		}
		
		#form\:genderId {
			padding: 7px !important;
		}
		
		#form\:groupId {
			padding: 7px !important;
		}
		
		#form\:nameId {
			padding: 7px !important;
		}
		
		#form\:tariffClassId {
			padding: 7px !important;
		}
		
		#form\:dayOfServiceId {
			padding: 7px !important;
		}
		
		#form\:exclusionId {
			padding: 7px !important;
		}
		
		#form\:collapseAllGroupsId {
			padding: 7px !important;
		}
		
		#form\:expandAllGroupsId {
			padding: 7px !important;
		}
		
		#form\:removeGroupingId {
			padding: 7px !important;
		}
		
		.plan_loading_style {
			width:98%;
			height:30px;
			border:0px solid #FF0000;
			text-align:center;
			display:none
		}
		
		.loading-indicator {
			display: inline-block;
			padding: 12px;
			background: none;
			-opacity: 0.5;
			color: black;
			font-weight: bold;
			z-index: 9999;
			border: 0px solid #FFFFFF;
			-moz-border-radius: 1px;
			-webkit-border-radius: 1px;
			-moz-box-shadow: 0 0 0px #FFFFFF;
			-webkit-box-shadow: 0px 0px 0px #FFFFFF;
			-text-shadow: 0px 0px 0px white;
			z-index:-1;
		}
		 
		.loading-indicator-img {
			padding-top: 20px; 
			background: url("#{resource['SlickGrid:images/ajax-loader-small.gif']}") no-repeat center left;
			background-position: center; 
		}
		
	</h:outputStylesheet> 
		
	<div class="card card_style">
		<div id="loading" class="loading-indicator plan_loading_style">
			<div class="loading-indicator-img"></div>
			<label>Please wait loading...</label>
		</div>
		<table width="100%">
		  <tr>
			<td valign="top" width="100%">
				<div id="planGrid" class="plan_table_grid" style="width:600px;height:165px;padding: 0px;"></div>
			</td>
		  </tr>
		</table>
	</div>
	
	<h:outputScript name="js/Sortable/Sortable.min.js" library="billing"/>
	
	<h:outputScript name="lib/firebugx.js" library="SlickGrid"/>
	<h:outputScript name="slick.core.js" library="SlickGrid"/>
	<h:outputScript name="slick.grid.js" library="SlickGrid"/>
	<h:outputScript name="slick.dataview.js" library="SlickGrid"/>
	<h:outputScript name="slick.interactions.js" library="SlickGrid"/>

	<h:outputScript name="plugins/slick.rowselectionmodel.js" library="SlickGrid"/>
	<h:outputScript name="slick.groupitemmetadataprovider.js" library="SlickGrid"/>
	<h:outputScript name="plugins/slick.cellrangedecorator.js" library="SlickGrid"/> 
	<h:outputScript name="plugins/slick.cellrangeselector.js" library="SlickGrid"/>
	<h:outputScript name="plugins/slick.cellselectionmodel.js" library="SlickGrid"/>
	
	<script>
		function isIEPreVer9() { var v = navigator.appVersion.match(/MSIE ([\d.]+)/i); return (v ? v[1] &lt; 9 : false); }
		
		var dataView;
		var grid;
		var data = [];
		
		var columns = [
			{id:"id", name:"#", field:"", cssClass:"cell-selection", width:15, resizable:false, selectable:false, focusable:false},
			{id:"type", name:"Type", field:"componentTypeValue", width:80, minWidth:80, cssClass:"cell-title", sortable:true},
			{id:"visitType", name:"Visit Type", field:"visitValue", width:60, minWidth:60, cssClass:"cell-title", sortable:true},
			{id:"gender", name:"Gender", field:"genderValue", width:80, minWidth:120, cssClass:"cell-title", sortable:true},
			{id:"ageRange", name:"Age Bracket", width:80},
			{id:"amountRange", name:"Amount Bracket", width:100},
			{id:"quantityRange", name:"Quantity Bracket", width:100},
			{id:"group", name:"Group", field:"componentGroupName", width:120, minWidth:120, cssClass:"cell-title", sortable:true},
			{id:"name", name:"Name", field:"componentName", width:200, minWidth:120, cssClass:"cell-title", sortable:true},
			{id:"aliasCode", name:"Alias Code", field:"serviceAliasCode", width:120, minWidth:120, cssClass:"cell-title", sortable:true},
			{id:"aliasName", name:"Alias Name", field:"serviceAliasName", width:120, minWidth:120, cssClass:"cell-title", sortable:true},
			{id:"tariffClass", name:"Tariff Class", field:"tariffClassTypeValue", width:160, minWidth:120, cssClass:"cell-title", sortable:true},
			{id:"tariffClassValue", name:"Tariff Value", field:"tariffClassValueOfValue", width:160, minWidth:120, cssClass:"cell-title", sortable:true},
			{id:"dayOfService", name:"Day Of Service", field:"dayTypeValue", width:80, minWidth:80, cssClass:"cell-title", sortable:true},
			{id:"excluded", name:"Excluded",field:"excluded",  width:80, minWidth:20, maxWidth:80, cssClass:"cell-effort-driven", sortable:true},
			{id:"typeOnBase", name:"Type on base", field:"baseValueAddValue",width:160, minWidth:120, cssClass:"cell-title", sortable:true},
		    {id:"patientPercentage", name:"Patient Co-payment", field:"patientPercentage",width:120, minWidth:80, cssClass:"cell-numeric", sortable:true},
			{id:"sponsorPercentage", name:"Sponsor Payment", field:"sponsorPercentage",width:120, minWidth:80, cssClass:"cell-numeric", sortable:true},
			{id:"patientValueAdd", name:"Type On Patient", field:"patientValueAddValue",width:160, minWidth:80, cssClass:"cell-title", sortable:true},
			{id:"sponsorValueAdd", name:"Type On Sponsor", field:"sponsorValueAddValue",width:160, minWidth:80, cssClass:"cell-title", sortable:true},
			{id:"coPaymentValueAdd", name:"Co-payment Type", field:"coPaymentValueAddValue",width:120, minWidth:80, cssClass:"cell-title", sortable:true},
			{id:"status", name:"Status", field:"status", width:80, minWidth:80, cssClass:"cell-title", sortable:true}				
		];
		
		var options = {
			enableCellNavigation: true,
            editable: false,
			autoHeight: false,
			cellHighlightCssClass: "changed"
		};
		
		var sortcol = "title";
		var sortdir = 1;
		var percentCompleteThreshold = 0;
		
		function comparer(a, b) {
			var x = a[sortcol], y = b[sortcol];
			return (x == y ? 0 : (x > y ? 1 : -1));
		}

		$(function(){	
			showIndicator();
			$("#planGrid").css('height','300');
			var groupItemMetadataProvider = new Slick.Data.GroupItemMetadataProvider();
			dataView = new Slick.Data.DataView({
                groupItemMetadataProvider: groupItemMetadataProvider
            });
			grid = new Slick.Grid("#planGrid", dataView, columns, options);

            // register the group item metadata provider to add expand/collapse group handlers
            grid.registerPlugin(groupItemMetadataProvider);

            grid.setSelectionModel(new Slick.CellSelectionModel());

            grid.setSelectionModel(new Slick.RowSelectionModel());
			
			loadData();
			
			dataView.onRowCountChanged.subscribe(function (e, args) {
				grid.updateRowCount();
				grid.render();
			});

			dataView.onRowsChanged.subscribe(function (e, args) {
				grid.invalidateRows(args.rows);
				grid.render();
			});
			
			grid.onClick.subscribe(function(e, args) {
				var item = dataView.getItem(args.row);
				console.log(item.id);
				selectItem([{name: 'param1', value: item.id}]);
			}); 
			
			grid.onSort.subscribe(function (e, args) {
				console.log(args);
				sortdir = args.sortAsc ? 1 : -1;
				sortcol = args.sortCol.field;
				console.log(sortcol);

				if (isIEPreVer9()) { 
				
					var percentCompleteValueFn = function () {
						var val = this["percentComplete"];
						if (val &lt; 10) {
							return "00" + val;
						} else if (val &lt; 100) {
							return "0" + val;
						} else {
							return val;
						}
					};

					dataView.fastSort((sortcol == "percentComplete") ? percentCompleteValueFn : sortcol, args.sortAsc);
				} else {
					dataView.sort(comparer, args.sortAsc);
				}
			});
		});
		
		function loadData(){
			var serverURI = "----------------------------------";
			var planId= $('#planId').val();
			var editMode= $('#editMode').val();

			if(planId>0){
				$.ajaxSetup({cache : false});
				$.ajaxSetup({"error":function(XMLHttpRequest,textStatus, errorThrown) {  
					alert(textStatus); 
					alert(errorThrown); 
					alert(XMLHttpRequest.responseText); 
				}}); 
				$.getJSON(serverURI,{planId: planId,editMode: editMode},
				function(json) {
					data = eval(json);
					
					console.log(data);
			
					dataView.beginUpdate();
					dataView.setItems(data, "planSpecificationId");
					$('#loading').hide(); 
					dataView.endUpdate();
					dataView.refresh();
					grid.invalidateAllRows();
					grid.updateRowCount();
					grid.render();
				});
			}else{
				data = "";
				dataView.beginUpdate();
				dataView.setItems(data);
				$('#loading').hide(); 
				dataView.endUpdate();
				dataView.refresh();
				grid.invalidateAllRows();
				grid.updateRowCount();
				grid.render();
			}
		}
		
		function showIndicator(){
			$('#loading').show(); 
		}
		
	</script>
</ui:composition>
</ui:composition>


This is the source code. I tried to use the slick grid like this way. But in the Chrome browser most of the cases data is not displayed. But other browsers displayed this same data properly in all cases

**Comment by athulkrishnauk** [comment]
> closing since no repro or even feedback was provided, there isn't much more we can do

Can you please open this issue? I put the source code, can you please check?

**Comment by ghiscoding** [comment]
there are a few red flags in your code, you should never use `data = eval(json);` (see [eval](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval) on MDN) it's quite a security risk, instead you should probably use `JSON.parse(...)` to parse string into an object. Inside your `else` section you're passing `data = "";` but data should be an array, not a string, it should be `data = [];`. You're also calling `invalidateAllRows`, then `updateRowCount` and `render`, ... you could replace these 3 lines with `invalidate()` since it does all 3

https://github.com/6pac/SlickGrid/blob/4b06690a2d5d225537deaec943b408bcd555256c/slick.grid.js#L3515-L3519


I'm not sure that will help but still, that is not repro that we can use and test, for us to really be able to do anything it should be a reproducible example that we can try and use on our side, your code is not that kind of repro, we cannot test anything. I also haven't used Java in years and your problem might actually be with Java. It's hard for us to do anything with this code

**Comment by 6pac** [comment]
Steps to create an example we can repro are: 

(1) Start with an example file from the Slickgrid repo examples folder. Copy it and give it a meaningful name.
(2) modify the new example file step by step until it reproduces your issue. Ideally, make changes as minimal as possible while still reporducing the issue.
(3) post the file here as an attachment

Note that the file *must* run when saved into the example folder of the repo, so it can have no external dependencies (though clearly it can reference files in the repo, as the examples do).

And 99% of the time, you'll find the bug while you're doing step 2 and won't need our help at all.
