### ISSUE TITLE
Can these slick.*.js files be packed and compressed into one slick.all.min.js

### ISSUE THREAD

**Issue by andyforever** [6pac/SlickGrid#8]
How to pack and compress these slick.*.js files into slick.all.min.js?
Thx

**Comment by 6pac** [comment]
These days, this is usually done automatically by your framework. ASP .NET MVC does it, a lot of the PHP frameworks do it. You could set up a shell script to concatenate and minify the files. I'm sure there's a million examples out there. 
Frankly, I'm not going to do it. You get the pieces, it's up to you how you assemble them. For example, I've got a bunch of helper js files that also get wrapped up in the script

**Comment by andyforever** [comment]
Thx for the reply.
I will try some Node.js tools such as Yeoman, Grunt.
