### ISSUE TITLE
can I get an example of how to work with slickgrid and ReactJS?

### ISSUE THREAD

**Issue by zachary822** [6pac/SlickGrid#80]
```{jsx}
import Slick from 'slickgrid';

new Slick.Grid(...args);
```
(above is pseudo-code)
this always get me a `Uncaught TypeError: _slickgrid2.default.Grid is not a constructor`.

```{jsx}
import Slick from 'slickgrid/slick.grid-npm';
```
this gets a `Cannot resolve module 'jquery-ui/sortable'`

**Comment by 6pac** [comment]
I'm sorry, but I don't use ReactJs and don't know what its requirements are. 
I've also been asked to integrate with Bower, NuGet and NPM. I don't use any of those. (Well, NuGet a bit, but mainly for C#)

If you'd like to work it out and submit a pull request, I'm more than happy to integrate it into the library.
If you have ```import``` directives indicating dependencies, that should be similar to NPM. There's an NPM version in the ```/npm``` folder in the latest repo.

**Comment by at88mph** [comment]
Further to this.

I noticed that SlickGrid is published [on NPM here](https://www.npmjs.com/package/slickgrid).  When I use it like:

```
require('slickgrid/slick.grid-npm');
```
I also get:

```
Cannot resolve module 'jquery-ui/sortable'
```

If I change the top of `slickgrid/slick.grid-npm.js` to look like:

```
require('jquery-ui/ui/widget');
require('jquery-ui/ui/widgets/mouse');
require('jquery-ui/ui/widgets/sortable');

var Slick = require('./slick.core-npm');
```

Then it seems to work well.

The `slickgrid/slick.dataview-npm.js` needed to have the `Slick` core imported too, so I added this to the top:

```
var Slick = require('./slick.core-npm');
```

Are you maintaining those files?

Thanks!

**Comment by 6pac** [comment]
thanks, yes I don't use react or npm, so I'm putting this together as a community service!
any pointers are welcome. 
a pull request is ideal.
i've had my suspicions that the npm side of things was only partially complete.

**Comment by at88mph** [comment]
Thanks, @6pac.

Are you open to upgrading `jquery-ui` to `1.12.1` if the tests pass?  The reason I ask is because the require statements have changed since `1.10.x`.

**Comment by 6pac** [comment]
yes, as long as it doesn't break backwards compatibility in the non-npm context. At the moment we have a single build that supports jQuery 1.8+, 2.0+, 3.0+, and that makes me reluctant to split builds. But I'd probably be updating soon anyway. UI doesn't change very often, I'd missed that update.

**Comment by at88mph** [comment]
So far so good.  Are the tests automated in some way?  How is everything in the `tests` directory run?

Thanks.

**Comment by 6pac** [comment]
it's just opening the html docs in there. 
nothing is really automated yet apart from updating the files in the npm-specific folder, which is done by a script in the ```scripts``` folder.

feel free to suggest something, but the repo is deliberately kept pretty basic: see the [manifesto](https://github.com/6pac/SlickGrid/wiki/4-The-SlickGrid-Manifesto)

**Comment by at88mph** [comment]
I've been struggling with how to package up the `plugins` and `controls`.  I've managed to simplify the system with a [main.js](https://github.com/at88mph/SlickGrid/blob/master/main.js), so you don't need the `scripts` and `npm` folders with patches.

Do you have suggestions for the `plugins` and `controls`?  I think they ought to be done in such a way that one could write it as:

```
require('slickgrid');
require('slickgrid/plugins/checkboxselector');

// Or just
require('slickgrid/checkboxselector');
```

Thanks,
Dustin

**Comment by 6pac** [comment]
sounds good, I just have no idea how npm works. i'm happy to implement this when you work it out though, especially if I don't need the script folder any more.

**Comment by 6pac** [comment]
@at88mph, any progress here? I really need an NPM guru to come along and set this all in order.

**Comment by at88mph** [comment]
Hi Ben,

I could issue a pull request, but I don’t know if it’s worth rewriting the tests to use the web pack version of the NPM modules.  The core logic is not modified, but it’s just packaged for NPM using the index.js file.  Let me make sure your master is merged in properly, then I will issue a pull request for review.

Dustin


Dustin N. Jenkins 
Tel/Tél: 250.217.4970 | facsimile/télécopieur: 250.363.0045 | Dustin.Jenkins@nrc-cnrc.gc.ca 
National Research Council Canada | 5071 West Saanich Rd, Victoria BC. V9E 2E7 
Conseil national de recherches Canada | 5071, ch. West Saanich, Victoria (C.-B) V9E 2E7 
Government of Canada | Gouvernement du Canada

**Comment by 6pac** [comment]
So @ghiscoding has created a ```package.json``` and we are releasing via NPM.

However I don't think we have NPM dependencies etc in any of the files. It's always been an issue as to how to incorporate this without breaking the non-NPM use case.

Doubly so with SlickGrid being a toolkit - it's not really possible to know ahead of time what plugins etc a user is going to need, and they probably wouldn't appreciate having them all chucked in 'just in case'.

**Comment by at88mph** [comment]
Great!  Thanks for the update.

**Comment by nzhtrtlc** [comment]
First of all @6pac thank you for this repo.
In the react ecosystem we really don't have a full featured grid. Only ag-Grid has one but it has a price of course. I am really interested to develop this grid for react. But i don't have much knowledge and time for that. So for now.. i am just wrapping it in my react project in basic level.
If any one who want to wrap this project completely into React component, create a repository and lead us!
