### ISSUE TITLE
Noisy error on drag.init with jquery.event.drag 2.3 and jQuery 3.1.1 - with proposed fix

### ISSUE THREAD

**Issue by RalphMack** [6pac/SlickGrid#82]
I'm seeing a problem with jquery.event.drag 2.3 on jQuery 3.1.1, but I'm not sure what the appropriate fix might be. The root problem is with the following:

```
             interaction: function( elem, dd ){
                 var offset = $( elem )[ dd.relative ? "position" : "offset" ]() || { top:0, left:0 };
``` 
The element passed from init is from an array that often contains things like booleans. jQuery 2.2.4 sees whether the elem is really an element and simply returns. jQuery 3.3.1 only checks that the elem is truthy and then performs functions that expect this to really be an element, i.e. 3.1.1:

```
		if ( !elem ) {
			return;
		}
```
vs. 2.2.4:
```
		var doc = elem && elem.ownerDocument;
		if ( !doc ) {
			return;
		}

```
I substituted the following code, essentially externalizing the guard code that was previously in jQuery, and it seems to do okay for my purposes:

```
var` offset = (elem && elem.ownerDocument) ? 
$(elem)[dd.relative ? "position" : "offset"]() || { top: 0, left: 0 } : { top: 0, left: 0 };

```
However, jQuery may have a method call more appropriate for outside components to apply the sense of what I'm doing. Is there a more elegant thing that should be done instead?

**Comment by 6pac** [comment]
Looks like the elements passed are controlled by the drag library, rather then jQuery. So your code stands.

Thanks! This has been incorporated into the repo just now. I'm going to be going over the issue backlog and issuing a new release later in the week.
