### ISSUE TITLE
Grid Event is not working in Salesforce

### ISSUE THREAD

**Issue by syless** [6pac/SlickGrid#839]
I introduced it to Salesforce and used it well. I don't know if it's because of the new release of Salesforce, but the Grid event like below is not recognized. How should I take action? It was working fine until recently. A checkbox that selects all rows works normally.

`<div class="fileGrid" onselectedrowschanged={handleRowSelection}></div>`

`handleRowSelection(event){
    console.log('row selection', event.detail.args;
}
`

Thank you.

**Comment by ghiscoding** [comment]
events in SlickGrid are custom SlickGrid events and have no relation with JavaScript Events, unless you're using [Slickgrid-Universal](https://github.com/ghiscoding/slickgrid-universal), which I maintain, and in that project SlickGrid events are re-exported to regular JS events (by subscribing to SG events and triggering JS events) but if that's the case then you're asking your question in the wrong project. For our use case, we do use Slickgrid-Universal in Salesforce by following these instructions that I wrote [Salesforce Installation](https://github.com/ghiscoding/slickgrid-universal/wiki/Installation---Salesforce-(LWC)) and as far as I know it still works in our Salesforce implementation
