### ISSUE TITLE
search doesn't find tree children

### ISSUE THREAD

**Issue by susdu** [6pac/SlickGrid#84]
Is it a bug or just not implemented? can it be easily enabled?

thanks,
David

**Comment by 6pac** [comment]
details: which example? steps to reproduce? i wasn't aware that there was even a tree example

**Comment by susdu** [comment]
http://6pac.github.io/SlickGrid/examples/example5-collapsing.html

try searching for a nested record

**Comment by 6pac** [comment]
that looks like a bug. it's filtering out the nodes correctly, but in some cases they don't have parents or they are activated parents. that filter probably shouldn't be in there.

there would need to be extra features built into the search, eg. if a node matches, include its parents even if they don't match, collapse a node if it no longer has sub nodes.

**Comment by susdu** [comment]
can you point me to the relevant function? I'll fix the incorrect filtering and you can pull it

**Comment by 6pac** [comment]
it's ```myFilter``` in the example file. there's some logic there already, but it may not be what you expect

**Comment by 6pac** [comment]
anything happen here?
