### ISSUE TITLE
Navigating via left/right arrows doesn't work as expected

### ISSUE THREAD

**Issue by YakovL** [6pac/SlickGrid#85]
Hi, first of all, thanks for maintaining this great project, very nice that there's some open-source solution for excel-like interfaces.

I've tested some demos and found some major problems with editing, so in this issue I report the first one:
in Vivaldi (and Chrome)
in http://6pac.github.io/SlickGrid/examples/example3-editing.html
when Auto-edit is ON
there's no way to navigate to a cell to the left/right from the current one using the left/right arrow keys: when all the stuff is selected and when the cursor is in the end of the content, pressing "right" doesn't do a thing (what is expected: jump to the next cell).

PS Though, it's possible to press esc and then navigate, but that's not that convenient, especially when one need to jump several rows to the left/right. Another note is this problem takes place only with cells with certain content type: in the mentioned demo page the problem rises only in the 3 first colomns; %, date and checkbox colomns work nicely.

**Comment by 6pac** [comment]
I'd have to check more closely. I agree, there are some issues with cell navigation in general.
The accepted way to navigate is with the tab key, but one problem is that everyone has a different idea about how navigation 'should' work.
I have tweaked the editors and added some extra hooks in recently to allow more fluid navigation. Will make sure that gets fed back to this repo.

**Comment by YakovL** [comment]
Yeah, you're right in the "everyone has a different idea about how navigation 'should' work" point. What I'm talking about is an excel-like navigation: arrows bring oneself to the next cell (left/right/up/down) but when one starts typing or press F2 (may be adjusted to another hot key), they get inside the editor (overwriting the value unless F2 was pressed). This behaviour is at least familiar to many guys, so may be considered as one of the standart behaviours.

**Comment by 6pac** [comment]
There are some additions to the 6pac repo that make it a lot easier to achieve this.
Firstly, there is a new ```keyCaptureList``` property on an editor.
Set it like

    function MyEditor(args) {
        ...
        this.keyCaptureList = [Slick.keyCode.UP, Slick.keyCode.DOWN, Slick.keyCode.ENTER];

        this.init = function () {
            ...

and then those keys will be captured by the grid before they hit the editor. FYI, here's the grid code that handles the keys:

    function handleKeyDown(e) {
      ...
      if (!handled) {
        if (!e.shiftKey && !e.altKey && !e.ctrlKey) {
          // editor may specify an array of keys to bubble
          if (options.editable && currentEditor && currentEditor.keyCaptureList) {
            if (currentEditor.keyCaptureList.indexOf( e.which ) > -1) {
                return;
            }
          }
         if (e.which == keyCode.ESCAPE) {
            if (!getEditorLock().isActive()) {
              return; // no editing mode to cancel, allow bubbling and default processing (exit without cancelling the event)
            }
            cancelEditAndSetFocus();
          } else if (e.which == keyCode.PAGE_DOWN) {
            navigatePageDown();
            handled = true;
          ... 

Also just now I added the preClick event to the editor. This has to be set up like so with the formatter:

    function CheckboxFormatter(row, cell, value, columnDef, dataContext) {
      return '<img class="slick-edit-preclick" src="../images/' + (value ? "CheckboxY" : "CheckboxN") + '.png">';
    }

then the editor can handle the initial click on the cell before the editor is even opened (this gets 'saved up' the the grid and passed as soon as the editor is initialised). This addition to the editor adds the ability to one-click change the checkbox values:

    function CheckboxEditor(args) {
        ...
      this.preClick = function () {
          $select.prop('checked', !$select.prop('checked'));
      };

I've changed ```Example4-Model``` to use this style of checkbox if you want to check it out.
