### ISSUE TITLE
Implement copying/pasting multiple cells

### ISSUE THREAD

**Issue by YakovL** [6pac/SlickGrid#86]
So I guess this is a major feature request, but it's a key point of an excel-like interface I'm looking for, so..

It will be very useful if it's possible to paste multiple cells from a spreadsheet (or another table) (when pasted as plain text, those are usually tab-separated "cells" in linebreak-separated "rows") and also (less important for me) to copy the selected cells (by pressing ctrl+C) in such format that can be pasted into a spreadsheet (tabs + linebreaks separationg would be good enough for one-liners; for multiple line cells they should be wrapped with double-quots, at least that works with LibreOffice).

(my idea is to combine the interface with DB-like structures in TiddlyWiki)

**Comment by 6pac** [comment]
Whoops! We have an example for that, but it's not listed on the example page!

http://6pac.github.io/SlickGrid/examples/example-excel-compatible-spreadsheet.html

Keep me posted with any enhancements or bugs.

**Comment by YakovL** [comment]
Ah, right, this may be closed than, only it would be nice to have an example where both editing and range copying/pasting may be enabled and tested together.
