### ISSUE TITLE
Add 508 accessibility enhancements suggested by mleibman#616

### ISSUE THREAD

**Issue by lincolngup** [6pac/SlickGrid#87]
Add 508 accessibility enhancements suggested by the GitHub commit documented here: [https://github.com/mleibman/SlickGrid/pull/616](https://github.com/mleibman/SlickGrid/pull/616).

This code adds role attributes that allow the JAWS screen reader (a common accessibility tool) to identify SlickGrid as a table and read the columns and data on the page. I’ve looked at the suggested changes, and although the current 6pac code base has marched forward from the original repo, the current 6pac codebase looks sufficiently (IMHO) similar to the original mleibman codebase to make a migration possible.

Additionally, a single-line change to slick.grid.js  is required to ensure that Chrome’s accessibility tree is generated correctly in some newer versions of Chrome (49+).
The mleibman code, slick.grid.js  line 263:
`$canvas = $("<div class='grid-canvas'/>").appendTo($viewport));`
And the revision:
```
// Chrome 49+ fix issue with grids not reading
$canvas = $("<div class='grid-canvas'/>").appendTo($("<div role='rowgroup'/>").appendTo($viewport));
```

To address the comment by @6pac ([https://github.com/mleibman/SlickGrid/pull/616#issuecomment-52388972](https://github.com/mleibman/SlickGrid/pull/616#issuecomment-52388972)) about suggestions for testing, some possible testing tools include:

- Google Chrome Accessibility Developer Tools – adds an accessibility audit to the Developer Tools
- aXe Chrome extension – accessibility testing based on the axe-core JavaScript library
- WAVE Evaluation Tool – visual feedback of accessibility issues
- NVDA – free screen reader
- JAWS – screen reader, costs money

### Disclaimer
This submission is being made on behalf of the USPTO, an agency of the United States Department of Commerce (DOC), to support the open source community. The United States Department of Commerce (DOC) GitHub project code is provided on an ‘as is’ basis and the user assumes responsibility for its use. DOC has relinquished control of the information and no longer has responsibility to protect the integrity, confidentiality, or availability of the information. Any claims against the Department of Commerce stemming from the use of its GitHub project will be governed by all applicable Federal law. Any reference to specific commercial products, processes, or services by service mark, trademark, manufacturer, or otherwise, does not constitute or imply their endorsement, recommendation or favoring by the Department of Commerce. The Department of Commerce seal and logo, or the seal and logo of a DOC bureau, shall not be used in any manner to imply endorsement of any commercial product or activity by DOC or the United States Government.

**Comment by 6pac** [comment]
Thanks, for progressing this. It's a tricky one. Given that it looks like the adjustments may cause problems (there's the focus/scrolling issue, and even adding div's in might cause problems if people have written code for a particular SlickGrid container structure), either a plugin or an option-based implementation is safest until its mature. No problem with the philosophy of it 'just being built in', but this is a long term goal rather than something we can just do right now.
