### ISSUE TITLE
Grid.onCellChange called after other event

### ISSUE THREAD

**Issue by victor-chang** [6pac/SlickGrid#90]
Hi, Not sure if this is real issue or not, but I subscribe to onCellChange event. After I change a cell value, then immediately click a button to save the change. The onCellChange event is not called before the button click event happen so the change was not recorded. How do I make sure onCellChange event is called before button click event?

**Comment by victor-chang** [comment]
Ok, I guess I can use a work around, in the button click event handler, I call graid.navigateRight() so the update is recoreded

**Comment by 6pac** [comment]
you can also use ```grid.getEditorLock().commitCurrentEdit()```

**Comment by victor-chang** [comment]
Thanks
