### ISSUE TITLE
dataView.onRowsChanged event doesn't always fire when the rows have changed

### ISSUE THREAD

**Issue by granthughes** [6pac/SlickGrid#91]
When filtering rows, the `dataView`'s `onRowsChanged` event does not always get called when the rows have changed. This happens when filtering down the list such that the new rows are the first X rows from the current rows.

For example:
Your data consists of three records in this order: "Task 01", "Task 02", "Task 03"
When filtering on rows with a "0", the `onRowsChanged` event correctly does not fire because all 3 rows are still there.
If I then filter to "01", the `onRowsChanged` event still does not fire even though only 1 row is now showing.
Had I filtered on "02", the `onRowsChanged` event would have fired.

The issue lies in how the `dataView` checks for row changes in its `getRowDiffs` function. At a basic level, this function loops through the newly filtered rows and compares them to the rows before the new filter. As long as the new rows exist in the the original rows in the same order, the function does not report any diffs. It is ignoring that the original row list contains more rows than the new list. All of these additional rows should be considered diffs.

The `getRowDiffs` function affects the `onRowsChanged` event because `dataView.refresh()` calls `recalc()` which ultimately returns an array of row indexes that changed via the `getRowDiffs` function. The `refresh` function will only fire the `onRowsChanged` event if `getRowDiffs()` reports any diffs.

Here is a JSFiddle illustrating this issue: https://jsfiddle.net/bcnap2dm/
I used the code from this example as a starting point: http://6pac.github.io/SlickGrid/examples/example4-model.html
From there, all I did was simplify the data set and add toastr notifications to show when the `onRowsChanged` event is triggered.

**Comment by 6pac** [comment]
hate to say this, but that's what the ```onRowCountChanged``` event is for. several people have commented  that it would be better to have a single event to handle rather than ```onRowCountChanged``` _and_ ```onRowsChanged ```. i've thought about it, but the breaking change and testing all the scenarios is a bit daunting. it's likely that two two distinct events were provided because in some situations they allow more efficient handling of the changes.

**Comment by granthughes** [comment]
Ah, I should have searched closed issues before posting this. This is a duplicate of #2. Sorry about that.

I think it is correct to have the 2 events. The thing that is missing here is documentation to clarify when the events will fire (unless I just can't find the existing documentation). It seems like I am not the only newcomer to this tool that saw the `onRowsChanged` event and assumed it would fire any time any the rows were added to, removed from, or reordered. Instead it will actually fire when the rows in the new collection are not in the same index as in the old collection.

What are your thoughts on creating a wiki page to document the events that consumers of this tool can hook into?

**Comment by tobya** [comment]
Extra documentation is always good 😊

**Comment by 6pac** [comment]
Look, my apologies for this. My thoughts are that I should update my Wiki quite broadly (it hasn't changed since MLeibman). It's been on the TODO list for some time. I've just been too busy.
Will try to get something up in the next month.
Anyone is welcome to document it and make a pull request to the Wiki ... :-)

**Comment by 6pac** [comment]
Still cleaning up the wiki but it's a lot better now. I've brought all the MLeibman wiki pages over.

There are instructions about this issue on the main page of the wiki, probably not a place you'd look.  
I've added the DataView Events page and put it there, and also added comments in the relevant section in Example-4-Model. I think that will help.

Slowly updating the docs.

**Comment by 6pac** [comment]
https://github.com/6pac/SlickGrid/issues/344
