### ISSUE TITLE
Horizontal scrolling causes cells to render in wrong location

### ISSUE THREAD

**Issue by timclutton** [6pac/SlickGrid#914]
Horizontal scrolling a particularly wide SlickGrid causes cell content to be mis-rendered.

This can be seen in [example 1](https://6pac.github.io/SlickGrid/examples/example1-simple.html) by simply dragging the columns wider and then scrolling horizontally:

![Example of horizontal scrolling issue](https://github.com/6pac/SlickGrid/assets/12004437/df0a2fe9-212c-416b-a7ca-0838bb690777)
(Recorded in Firefox Dev Edition 120.0b9; same occurs in Edge 119.0.2151.58)

This seems to have been introduced in 5.5.1 as I can't reproduce with 5.4.2.

**Comment by ghiscoding** [comment]
hmm I'm assuming it was introduced by @JesperJakobsenCIM PR #908, @JesperJakobsenCIM any chance you can take a look at this issue?

**Comment by ghiscoding** [comment]
fixed in release [5.5.2](https://github.com/6pac/SlickGrid/releases/tag/5.5.2), thanks again for the feedback and a simple repro
