### ISSUE TITLE
Cannot set selectionModel

### ISSUE THREAD

**Issue by b-giavotto** [6pac/SlickGrid#927]
this typescript code fails: 

        let sm = new Slick.SlickRowSelectionModel();
        
        grid.setSelectionModel(sm);

the typescript compiler complain about incompatibility between  Slick.SlickRowSelectionModel and the declared prototype of 
setSelectionModel found in slick.grid.ts

setSelectionModel(model: SelectionModel) {
  if (this.selectionModel) {
    this.selectionModel.onSelectedRangesChanged.unsubscribe(this.handleSelectedRangesChanged.bind(this));
    if (this.selectionModel.destroy) {
      this.selectionModel.destroy();
    }
  }

Compiler output:

 TS2345: Argument of type 'SlickRowSelectionModel' is not assignable to parameter of type 'SelectionModel'.
  Type 'SlickRowSelectionModel' is not assignable to type '{ refreshSelections: () => void; onSelectedRangesChanged: SlickEvent<SlickRange[]>; getSelectedRanges: () => SlickRange[]; setSelectedRanges: (ranges: SlickRange[], caller?: string) => void; }'.
    Types of property 'onSelectedRangesChanged' are incompatible.
      Type 'SlickEvent<CellRange[]>' is not assignable to type 'SlickEvent<SlickRange[]>'.
        Type 'CellRange[]' is not assignable to type 'SlickRange[]'.
          Type 'CellRange' is missing the following properties from type 'SlickRange': isSingleRow, isSingleCell, contains

**Comment by ghiscoding** [comment]
it should be fixed in v5.5.5
