### ISSUE TITLE
args.grid.resetActiveCell does not work on column change handler with latest slickgrid version

### ISSUE THREAD

**Issue by simpysodhi1981** [6pac/SlickGrid#93]
args.grid.resetActiveCell does not work on column chnage handler with latest slickgrid version

**Comment by simpysodhi1981** [comment]
I tried your new master repo, but still this issue exists.

thanks

**Comment by 6pac** [comment]
can you post the exact error text, with the line number. 
also, if it's easy to reproduce it on an example, the mods to the example code.

**Comment by simpysodhi1981** [comment]
Hi Sorry for late response. But this issue is not fixed and i noticed there is one more issue: if i trying to call on row selection from Grid A to enable row for Grid2. It actually null the current editor. Means Grid1 is no more editable. This was working with the old Slick grid. Current Editor issue i have with "makeActiveCellEditable" function as well. 

With "makeActiveCellEditable", It throws CurrentEditor is Null
and second issue, what i am reporting, does not throw any error but if CurrentEditor is null, it just return


thanks

**Comment by 6pac** [comment]
can you post the exact error text, with the line number.
also, if it's easy to reproduce it on an example, the mods to the example code.
