### ISSUE TITLE
Bring mleibman wiki over

### ISSUE THREAD

**Issue by alexcroox** [6pac/SlickGrid#94]
If this is the official fork, is it possible to bring over the wiki content from the original repo as I keep having to switch between the 2 to find the right information.

**Comment by 6pac** [comment]
Yeah, that's no hard to do. I have been planning to rewrite and update the repo, but just really busy lately. I'll put it on the high priority list.

**Comment by alexcroox** [comment]
Nice, thank you

**Comment by 6pac** [comment]
Done. Now to document new features and update the reference pages.
