### ISSUE TITLE
applyFormatResultToCellNode incorrectly checks against 'String' when detecting a string

### ISSUE THREAD

**Issue by SethBoyd** [6pac/SlickGrid#98]
It should instead check against 'string' as that's what typeof will return if it is a string

This change occurred in bef3203d722b96853a312929a74121eac15ebed5.

Sorry I'm not sure the best way to create a pull request on a fork or I would have made this change myself.

**Comment by 6pac** [comment]
Good catch. thanks. I corrected it in one place but not the other. Fixed and pushed.
